mozilla-mobile/firefox-android

.taskcluster.yml, taskcluster/ci/config.yml
Now that the repo is public, we don't have to deal with SSH anymore and we can resume using HTTP. This PR just reverts a couple commits we made last month.
=> Stop cloning repo through SSH

taskcluster/ci/build-samples-browser/kind.yml, taskcluster/ci/build/kind.yml, taskcluster/ci/github-release/kind.yml, taskcluster/ci/post-beetmover/kind.yml, taskcluster/ci/post-signing/kind.yml, taskcluster/ci/test/kind.yml
Here's the simplest approach: Just add AC- to the existing treeherder "platform" names. I'm thinking that keeps things looking very similar to the way they do today for the android-components repo. When the other projects are added we can have "Focus-ui-tests" and "Fenix-ui-tests", etc, keeping each project's tests grouped on one line ("platform").
Since these are all in task defaults, the tricky part will come when incorporating focus and fenix. I don't have a clear vision for how that will work out, but I'm sure we can sort something out. Keep it simple for now?
I don't have strong feelings here, as long as we don't end up with a mish-mash of a-c/focus/fenix tasks on treeherder -- happy to hear other suggestions.
=> Bug 1791084 - Add "AC-" to treeherder platform names

monorepo-migration/sync-ac.sh
This fixes the regression I introduced in https://github.com/mozilla-mobile/firefox-android/commit/b1a420d45690890257a87320cebe44f2bae9ac96. This file should be under the `android-components` folder but this folder doesn't (and mustn't) exist until the repo is migrated over. This patch modifies the script to move this file to the right folder.
=> Bug 1789931 - part 5: Fix l10n.toml location in `sync-ac.sh`

.github/workflows/create-release.yml, .github/workflows/update-geckoview.yml, .mergify.yml
Needs to be tested in staging first. It happen once the Mergify app gets added on https://github.com/mozilla-releng/staging-firefox-android. After that, we need to land this on the `main` branch to get this tested. Mergify only takes the config in the `main` into account.
=> Bug 1786785 - Enable mergify bot

.github/workflows/sync-strings.yml
This fixes the path to the strings xml in the sync-strings-action script that was required due to https://github.com/mozilla-mobile/firefox-android/commit/293174cb840491681de4c512f8140f33ae05e60e
=> Bug 1786793 - Bump sync-strings-action to 1.0.3

.github/workflows/sync-strings.yml
Reverts mozilla-mobile/firefox-android#41. We'll land this once we confirm the Sync String action is working as expected.
=> Revert "Temporarily change Sync String actions to run every 15 minutes"

android-components/docs/components.md, android-components/docs/contribute/components_inside_app.md, android-components/docs/contribute/hosting_code_in_repository.md, android-components/docs/contribute/release_checklist.md, android-components/docs/contribute/updating_tracking_protection_lists.md, android-components/docs/contributing.md, android-components/docs/ui/icons.md
Working through "pages build and deployment" errors. Let's see.
We'll need more adjustment to our docs and website, but for now let's fix the links and get the build green.
=> Fix broken links in contributing page docs

.github/workflows/ac-create-release.yml, .github/workflows/ac-sync-strings.yml, .github/workflows/ac-update-geckoview.yml
We're adding an AC prefix to the existing AC GitHub actions filenames and titles to help differentiate the actions. This will be needed when we migrate the remaining Fenix and Focus GitHub actions in the future where it would be otherwise hard to tell what the action is doing if they are named the same or it is unclear which subfolder the action is operating on.
=> Add an AC prefix to GitHub actions that operates on android-components

taskcluster/ac_taskgraph/loader/build_config.py
The decision task was returning an empty set for PRs that needed to run AC build tasks because it was still assuming the old path.
=> Check the correct file path when returning a list of AC files changed in build_config.py

android-components/gradle.properties
Right now, the pom files are still pointing to the old repo.
=> Update the repo URL in gradle.properties

android-components/automation/publish_to_maven_local_if_modified.py
This broke when I removed the now redundant LICENSE file, but it's also surprising to me that we look up the project root based on the LICENSE. It's technically already a convention (and relied on) that this script lives under project-root/automation so we can just rely on it when inferring the project root.
=> Fix local/auto publication to not rely on LICENSE file

android-components/components/browser/storage-sync/build.gradle, android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/GlobalPlacesDependencyProvider.kt, android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt, android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageWorker.kt, android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesStorage.kt, android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/RemoteTabsStorage.kt, android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/StorageExtensions.kt, android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/StorageMaintenanceWorker.kt, android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/GlobalPlacesDependencyProviderTest.kt, android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt, android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageWorkerTest.kt, android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/Storage.kt, android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/StorageMaintenanceRegistry.kt, android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProviderTest.kt, android-components/components/feature/session/src/test/java/mozilla/components/feature/session/HistoryDelegateTest.kt, android-components/samples/browser/src/main/java/org/mozilla/samples/browser/BrowserActivity.kt, android-components/samples/browser/src/main/java/org/mozilla/samples/browser/SampleApplication.kt, docs/changelog.md
WorkManager's Worker is created for periodically running storage maintenance operation on places database. DB size limit is exposed from A-S that indicates the maximum DB size to aim for, in bytes. If the database exceeds this size, a small number of visits will be pruned. This operation is done periodically by a periodic work request that, optimally, will run once a day as long as the worker constraints are met.
WorkManager's periodic worker is running in A-C. Testing the feature is a bit tricky: see [pruning logic in A-S](https://mozilla.github.io/application-services/book/rust-docs/src/places/storage/history.rs.html#415-428)
As seen from the code snippet, we are pruning the elements starting from earliest 7 days ago.
Worker initialization is not enabled in SampleApplication in this PR …
=> Bug 1795903 - Introduce StorageMaintenanceWorker in A-C that runs periodically to prune places storage.

android-components/components/ui/autocomplete/src/main/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditText.kt, android-components/components/ui/autocomplete/src/test/java/mozilla/components/ui/autocomplete/InlineAutocompleteEditTextTest.kt, docs/changelog.md
Immediately after the user modified it's input text to something that doesn't match the current autocompleted text the autocompletion will be removed.
| Initial problem 25% speed | Fixed version 25% speed | Fixed version 100% speed |
| --- | --- | --- |
| <video src="https://user-images.githubusercontent.com/11428869/199284462-fb8612fe-139e-4043-ab94-a248ee7b1c2a.mov" /> | <video src="https://user-images.githubusercontent.com/11428869/199284532-16b2570d-6ce0-40ca-8e72-4b34acadffb0.mp4" /> | <video src="https://user-images.githubusercontent.com/11428869/199284609-c3fc3e57-e30b-4765-8d59-a5e3462baba9.mp4" /> |
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in …
=> Bug 1794933 - Remove autocomplete when not applicable anymore

android-components/automation/publish_to_maven_local_if_modified.py
Our current working directory is already guaranteed to be the root of the A-C project (the `android-components` folder). To capture changes to untracked files `git ls-files -o -exclude-standard"` (see [L70](https://github.com/mozilla-mobile/firefox-android/compare/main...csadilek:firefox-android:autopublish-hash-fix?expand=1#diff-62202bc6673751b5ccd03ae9865070d9de88eb143fdca34efe569e560cd59f70L71)) already does the right thing and only list files below it. 
We can switch calculating the diff from `git status -v -v` to just `git diff HEAD .` to capture changes to tracked files, both staged and unstaged. This is essentially the same as before, but makes sure we're NOT recording hash changes if files outside the android-componets directory change e.g., in `/firefox-android` or …
=> A-C auto publication only needs to hash changes under android-components

android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/SystemReducer.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/ContentState.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/SystemActionTest.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt, android-components/components/browser/tabstray/src/main/java/mozilla/components/browser/tabstray/TabViewHolder.kt, android-components/components/browser/tabstray/src/test/java/mozilla/components/browser/tabstray/DefaultTabViewHolderTest.kt, android-components/components/browser/thumbnails/src/main/java/mozilla/components/browser/thumbnails/ThumbnailsMiddleware.kt, android-components/components/browser/thumbnails/src/test/java/mozilla/components/browser/thumbnails/ThumbnailsMiddlewareTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt, android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/ext/TabSessionState.kt, android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/tabstray/Tab.kt, docs/changelog.md
This reverts commit d9028ef2b230a03459fe20ab56bdce0acdce3aea.
Fails UI test `openRecentlyClosedItemTest`:
```
androidx.test.uiautomator.UiObjectNotFoundException: UiSelector[RESOURCE_ID=org.mozilla.fenix.debug:id/toolbar]
at androidx.test.uiautomator.UiObject.click(UiObject.java:416)
at org.mozilla.fenix.ui.robots.HomeScreenRobot$Transition.openNavigationToolbar(HomeScreenRobot.kt:445)
at org.mozilla.fenix.ui.SmokeTest.openRecentlyClosedItemTest(SmokeTest.kt:480)
``` …
=> Revert "Bug 1795105 - Don't store thumbnails in BrowserState"

taskcluster/ci/test/kind.yml
Follows up #91.
Depends on https://phabricator.services.mozilla.com/D161278.
=> Bug 1797997 - part 7: Enable test tasks on trusted github-pull-requests

taskcluster/ci/test/kind.yml
Fixes up #113. This patch makes the tests run on ~~https://github.com/mozilla-mobile/firefox-android/pull/81~~ https://github.com/mozilla-mobile/firefox-android/pull/117
=> Bug 1797997 - part 8: Fix nit on event name

monorepo-migration/sync-focus.sh
Depends on https://github.com/mozilla-mobile/firefox-android/pull/121. ~~Only the changes in `monorepo-migration/sync-focus.sh` are worth reviewing here.~~ (#121 was merged)  
I tested the changes locally by just running the script from my branch and then have a look at the `focus-prep`, `focus-prep-107`, and `focus-prep-106` branches. For each branch, the merge looked fine:
* `git rev-list --parents -n 1 HEAD` showed 3 commits: the merge commit itself, the tip of the main/release branch on the monorepo, then the tip of the main/release branch of focus-android
* `git log` of each of the commits above shows the right history, including the modified one on focus. 
* The PR/issues numbers got replaced. I didn't find any number that didn't get replaced when I looked that up with that search …
=> Bug 1798878 - Let `sync-focus.sh` port the last 2 release branches too

taskcluster/ac_taskgraph/transforms/complete.py, taskcluster/ci/complete/kind.yml
A few years ago the owner and branch names for these bumps changed, so the notification would never actually happen.
Now we look for:
- the complete-pr task
- on the relbot/upgrade-geckoview-ac-main branch of the base repository
Since the branch name no longer includes the geckoview build id, we no longer include it in the email subject and replace it with the PR number.
=> Bug 1796658 - fix notifications on failure of geckoview nightly bumps

android-components/buildSrc/src/main/java/Dependencies.kt
Changelog:
https://square.github.io/leakcanary/changelog/#version-210-2022-11-10
=> Update leakcanary to version 2.10

taskcluster/ac_taskgraph/loader/build_config.py
=> Bug 1800542 - Bug fix for part 4

.github/workflows/ac-create-release.yml, .github/workflows/ac-update-geckoview.yml
Let's use https://github.com/mozilla-mobile/relbot/pull/93 to bump Geckoview on release branches too. 
Follows up:
* https://github.com/mozilla-mobile/firefox-android/pull/148 (the regressing PR)
* https://github.com/mozilla-mobile/firefox-android/pull/171
* https://github.com/mozilla-mobile/firefox-android/pull/173
* https://github.com/mozilla-mobile/firefox-android/pull/177
=> Bug 1800542 - part 5: Bump relbot from 4.0.0 to 4.0.1

android-components/plugins/dependencies/src/main/java/Gecko.kt
This (automated) patch updates GV Nightly on main to 109.0.20221118094451.
=> Update to GeckoView Nightly 109.0.20221118094451 on main

android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt, android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt
history.canAddUri() previously treated a URL with an empty scheme as valid, but application-services does not.
While I can't work out an STR to make Fenix actually try and add history using such a URL, I have verified that if it did, we'd end up with an error as reported in https://github.com/mozilla/application-services/issues/5235.
=> Don't try and record history for URLs with an invalid scheme.

android-components/components/support/rustlog/src/main/java/mozilla/components/support/rustlog/RustLog.kt, android-components/components/support/rustlog/src/test/java/mozilla/components/support/rustlog/RustLogTest.kt
The new system was merged in #12266 and we have started using it for all components in app-services.  I've been checking the Sentry reports and it seems like it's working, so let's remove the old one.
=> Removed code to report Sentry errors for Rust `log::error` calls

android-components/components/lib/crash-sentry-legacy/build.gradle, android-components/components/lib/crash-sentry-legacy/src/test/java/mozilla/components/lib/crash/sentry/legacy/SentryServiceTest.kt, android-components/components/lib/crash-sentry/src/main/java/mozilla/components/lib/crash/sentry/SentryService.kt, android-components/components/lib/crash-sentry/src/test/java/mozilla/components/lib/crash/sentry/SentryServiceTest.kt, android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/CrashReporter.kt, android-components/components/lib/crash/src/test/java/mozilla/components/lib/crash/BreadcrumbTest.kt, docs/changelog.md
Couple of fixes for Sentry breadcrumbs that I think will improve the app-services error reports.
Hopefully the issue with the timestamps was simply that we were recording them, but not copying them to the Sentry breadcrumb class.
The issue with duplicate items looks like it could be a threading issue to me and AFAICT when multiple threads report breadcrumbs, we are currently mutating the array without any synchronization.
I added a changelog entry that says "Bug fixed", although that's a little optimistic.  We won't know until this hits nightly and we can see the new reports.
- **Breaking …
=> Bug 1801349 - Sentry breadcrumb fixes

android-components/components/lib/publicsuffixlist/build.gradle, android-components/components/support/ktx/build.gradle, android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt, android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/StringTest.kt, docs/changelog.md
Added String.toShortUrl to support-ktx.
=> Bug 1796379 - Upstream String.toShortUrl to support-ktx

taskcluster/ac_taskgraph/loader/build_config.py
Fixes [1] which occurs in https://github.com/mozilla-mobile/firefox-android/pull/200:
```
[task 2022-11-21T15:12:58.228Z] 2022-11-21 15:12:58,217 - INFO - Looking for changed files to rebuild the modified components only...
[task 2022-11-21T15:12:58.228Z] 2022-11-21 15:12:58,227 - ERROR - Error loading tasks for kind build:
[task 2022-11-21T15:12:58.228Z] Traceback (most recent call last):
[task 2022-11-21T15:12:58.228Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/generator.py", line 309, in _run
[task 2022-11-21T15:12:58.228Z]     new_tasks = kind.load_tasks(
[task 2022-11-21T15:12:58.230Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/generator.py", line 58, in load_tasks
[task 2022-11-21T15:12:58.230Z]     inputs = loader(self.name, …
```
=> Bug 1800542 - part 9: Ensure decision task runs when the gradle config is changed

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/cookiebanners/GeckoCookieBannersStorage.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/cookiebanners/GeckoCookieBannersStorageTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/cookiehandling/CookieBannersStorage.kt, docs/changelog.md
🔴  Requires to land first https://bugzilla.mozilla.org/show_bug.cgi?id=1797581
=> Bug 1797605 - Add API support for ignoring sites for cookie banner handling

android-components/components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/DefaultTopSitesStorage.kt, android-components/components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/ext/TopSite.kt, android-components/components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/DefaultTopSitesStorageTest.kt, android-components/components/feature/top-sites/src/test/java/mozilla/components/feature/top/sites/ext/TopSiteTest.kt, docs/changelog.md
Add a new filter when getting top frecent sites to prevent duplicate frecent site with same host/domain as a provided top site.
https://user-images.githubusercontent.com/32488956/202701303-59f6255f-94be-44fb-8137-9c724a29610c.mp4
=> Bug 1801285 - Add filter by host/domain to frecent top sites

android-components/components/feature/contextmenu/src/main/AndroidManifest.xml, android-components/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuCandidate.kt, android-components/components/support/ktx/src/main/AndroidManifest.xml, android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/Context.kt, android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/content/Intent.kt, docs/changelog.md
Behavior Before:
https://user-images.githubusercontent.com/32488956/199718372-f4a7640c-0502-4580-b7ef-f217cd5e8d53.mp4
Behavior After:
https://user-images.githubusercontent.com/32488956/199718569-7b91e0e0-6fbf-478b-8a00-d41d250ca85c.mp4
=> Bug 1798873 - Exclude current app from share text targets

android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/AwesomeBar.kt, android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Reverts mozilla-mobile/firefox-android#183
Reverting due to perma-failures in UI tests:
* https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d4[…]057345840453/executions/bs.23ac7503c0cc9045/testcases/5
* https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d4[…]057345840453/executions/bs.15866a6549025185/testcases/3
```
java.lang.AssertionError: Failed: assertExists.
Reason: Expected exactly '1' node but could not find any node that satisfies: (Text + EditableText contains 'Google' (ignoreCase: false))
at androidx.compose.ui.test.SemanticsNodeInteraction.fetchOneOrDie(SemanticsNodeInteraction.kt:145)
at androidx.compose.ui.test.SemanticsNodeInteraction.assertExists(SemanticsNodeInteraction.kt:120)
at …
```
=> Revert "Upgrade Jetpack Compose to latest version (1.3.1)"

taskcluster/ac_taskgraph/gradle.py, taskcluster/ac_taskgraph/loader/build_config.py, taskcluster/ac_taskgraph/transforms/build.py, taskcluster/ac_taskgraph/transforms/gradle_optimization.py, taskcluster/ac_taskgraph/transforms/ui_tests.py, taskcluster/ci/build-samples-browser/kind.yml, taskcluster/ci/build/kind.yml, taskcluster/ci/test/kind.yml
Depends on https://github.com/mozilla-mobile/firefox-android/pull/243
I've had this PR at the back of my mind for many months. We optimized the number of build jobs we spawn in https://github.com/mozilla-mobile/android-components/pull/7617. That said, at that time we knew we implemented a hack. I left more details in [bug 1803141 comment 0](https://bugzilla.mozilla.org/show_bug.cgi?id=1803141#c0). 
Basically, this PR removes the hack and makes the logic more generic. This enable UI tests as well as `samples-browser` to be scheduled only when necessary. Before then, they were run for any type of change. In addition to that, we **won't schedule all A-C jobs on pushes to `main` anymore**. The reason is: with Focus coming to the monorepo soon, it doesn't make sense to run all these jobs even …
=> Bug 1803141 - part 1-6: Build/test components only when they change

android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml, android-components/components/browser/toolbar/src/main/res/values-ldrtl/dimens.xml, android-components/components/browser/toolbar/src/main/res/values/dimens.xml
• Add `paddingEnd` for RTL layouts, we could add padding for LTR as well and set it directly in the layout, but the idea was to preserve the space in `OriginView` for the title/url.
• No tests since only RTL layout was affected.
| Hebrew as RTL example | English as LTR example - unchanged | Desktop RTL |
|------|-----|----|
|![Screenshot_20221206_141521](https://user-images.githubusercontent.com/38040960/205922468-ffb040b6-b47d-4b47-9ad4-519932e76346.png)|![Screenshot_20221206_132722](https://user-images.githubusercontent.com/38040960/205920159-26772ae2-f1f1-4c01-9fd8-c3cc41db2885.png)|<img width="1728" alt="Screen Shot 2022-12-07 at 10 45 34 AM" src="https://user-images.githubusercontent.com/1190888/206226392-d536f2ab-3125-491a-8698-2fad45facca4.png">|
- **Milestone**: Make sure issues …
=> Bug 1796301 - Add paddingEnd in OriginView for RTL config

android-components/components/support/rusthttp/src/main/java/mozilla/components/support/rusthttp/RustHttpConfig.kt
– To allow emulator to access network of the host machine sidestepping the TLS error
– Application Services exposing the method --> https://github.com/mozilla/application-services/issues/5214
Once this is reviewed and released, will create a PR for `fenix` to enable this in debug builds.
=> Bug - 1804690 Expose allowEmulatorLoopback 

android-components/components/browser/state/src/main/java/mozilla/components/browser/state/search/SearchEngine.kt, android-components/components/feature/search/src/main/java/mozilla/components/feature/search/ext/SearchEngine.kt, android-components/components/feature/search/src/main/java/mozilla/components/feature/search/storage/SearchEngineReader.kt, android-components/components/feature/search/src/test/java/mozilla/components/feature/search/ext/SearchEngineKtTest.kt, android-components/components/feature/search/src/test/java/mozilla/components/feature/search/storage/SearchEngineReaderTest.kt, docs/changelog.md
=> Bug 1804594 - Differentiate search engines between "general" and "topic specific" when they are loaded

android-components/components/feature/prompts/src/main/AndroidManifest.xml, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/MimeType.kt, android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/FilePickerTest.kt, docs/changelog.md
=> Bug 1802579 - Add extra granular media permissions for devices with Android 13 and above.

focus-android/settings.gradle
No reason to run the linter on A-C when building Focus. Let's see what the difference is in ⏲️ .
=> Bug 1805438 - Don't lint components when building Focus

.taskcluster.yml
scriptworker's chain of trust verification expects a decision task's MOBILE_HEAD_REPOSITORY to match the repository URL in metadata.source. For pull requests that means we shouldn't set metadata.source to the base repo.
=> Bug 1805629: fix chain of trust verification failure on pull requests

README.md
This is a bit mechanical, and we likely want to make this much nicer in the future. Possibly inline some of the other README sections. However, let's fix it first and reflect the Focus migration.
=> No issue: Update README to reflect Focus migration

android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt, android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt, android-components/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt, android-components/components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt, android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt, android-components/components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt, android-components/components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt, docs/changelog.md
Added optional parameter `cursorPlacement` to `editMode` function which allows clients to specify where the cursor should be placed when switching to URL edit mode.
=> Bug 1804260 - Add method to specify the cursor placement when switching to URL editing mode

focus-android/build.gradle, focus-android/quality/detekt-baseline.xml, focus-android/quality/detekt.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1806170
=> Bug 1806170 - Align detekt config between Focus and Android Components

android-components/components/browser/state/src/main/java/mozilla/components/browser/state/selector/Selectors.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/selector/SelectorsKtTest.kt, android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt, android-components/components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt, docs/changelog.md
• Add `BrowserState.findNormalOrPrivateTabByUrlIgnoringFragment` extension function to find tabs which have the same url except the fragment/anchor part - [The part after `# ` in the url that's always at the end](https://datatracker.ietf.org/doc/html/rfc3986#section-3).
• Add `ignoreFragment` param in the `SelectOrAddUsecase` so callers can specify - defaults to false.
https://user-images.githubusercontent.com/38040960/207867953-dc434a0e-5047-47f2-b388-810171b82232.mp4 …
=> Bug 1796319 - Add functionality in SelectOrAddUsecase to ignore the fragment identifier part of the url

focus-android/app/src/androidTest/java/org/mozilla/focus/activity/SettingsGeneralTest.kt
Because UI Automator can't scroll the entire Compose list, and mixing Compose test rule with UIautomator/Espresso was too buggy in this case, I decided to avoid the need to scroll the list just to work around those issues.
=> Bug 1802610: Change Focus locale UI test to select a language above the fold

taskcluster/android_taskgraph/target_tasks.py, taskcluster/ci/beetmover/kind.yml, taskcluster/ci/config.yml, taskcluster/ci/push-apk/kind.yml, taskcluster/test/params/main-repo-push-beta.yml
Must be landed at the same time as https://github.com/mozilla-releng/shipit/pull/1238
`taskgraph target-graph -p taskcluster/test/params/main-repo-promote-beta.yml --diff HEAD~1` returns: 
```diff
--- target_task_graph@ba3f26b9c64c
+++ target_task_graph@bug-1806432
@@ -1,126 +1,20 @@
-beetmover-release-browser-domains
-beetmover-release-browser-engine-gecko
-beetmover-release-browser-engine-system
-beetmover-release-browser-errorpages
-beetmover-release-browser-icons
-beetmover-release-browser-menu
-beetmover-release-browser-menu2
-beetmover-release-browser-session-storage
-beetmover-release-browser-state
-beetmover-release-browser-storage-sync
-beetmover-release-browser-tabstray
-beetmover-release-browser-thumbnails
-beetmover-release-browser-toolbar
-beetmover-release-compose-awesomebar …
```
=> Bug 1806432 - Upload android-components to maven.mozilla.org in the `push` graph

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
Newer ZXing releases require Android 7 or higher, but we still support Android 5.
=> Bug 1804844 - Downgrade ZXing to version 3.3.3.

.taskcluster.yml
I don't know when we regressed https://github.com/mozilla-mobile/fenix/pull/17489 and https://github.com/mozilla-mobile/android-components/pull/9421. 
This patch was tested in staging. 
Pushes on main still work:
Pushes to a release branch too: 
Mergify PRs don't run `push` graphs (tested in https://github.com/mozilla-releng/staging-firefox-android/pull/22):
But they used to (tested in https://github.com/mozilla-releng/staging-firefox-android/pull/20): 
More info on why this is important to fix this today in [bug 1806444](https://bugzilla.mozilla.org/show_bug.cgi?id=1806444#c0)
=> Bug 1806444 - Do not run tasks for mergify branches on git-push

taskcluster/android_taskgraph/transforms/build.py, taskcluster/android_taskgraph/transforms/gradle_optimization.py, taskcluster/ci/build-components/kind.yml, taskcluster/ci/test-components/kind.yml, taskcluster/ci/test-focus/kind.yml, taskcluster/ci/ui-test-focus/kind.yml
Tested with this [parameters file](https://firefoxci.taskcluster-artifacts.net/AD67L8BPRaeqT_bqfcfTbQ/0/public/parameters.yml). `taskgraph optimized -p parameters.yml --diff upstream/main` returns this diff which is what I expected.
```diff
--- optimized_task_graph@ab473bfe7ee8
+++ optimized_task_graph@bug-1806601
@@ -1,18 +1,10 @@
-build-apk-focus-android-test-debug
-build-apk-focus-debug
build-docker-image-android-build
build-docker-image-base
build-docker-image-ui-tests
-build-samples-browser-gecko
-build-samples-browser-system
complete-pr
complete-pr-1
complete-pr-2
fetch-android-sdk-3859397
-signing-apk-focus-android-test-debug
-signing-apk-focus-debug
-test-focus-debug
toolchain-linux64-android-gradle-dependencies
toolchain-linux64-android-sdk-linux-repack
-ui-test-focus-arm-debug …
```
=> Bug 1806601 - Don't always run `sample-browser` and tests on `focus-debug` 

android-components/components/support/utils/src/main/java/mozilla/components/support/utils/ext/Bundle.kt, android-components/components/support/utils/src/test/java/mozilla/components/support/utils/BundleTest.kt
=> Bug 1805832 - Add additional checked casts when converting Array<Parcelable>

android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/share/ShareDownloadFeature.kt, android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/share/ShareDownloadFeatureTest.kt, docs/changelog.md
https://user-images.githubusercontent.com/32488956/208445056-f8343b50-dac7-480a-9ff8-3c00f1b7d02a.mp4
=> Bug 1806411: Remove image link from message when sharing an image

.mergify.yml
Per https://docs.mergify.com/actions/queue/#queue-action, this option is deprecated and due to be removed in a couple of months.  Besides, we were setting it to `none` which was the default.
=> Bug 1808179 - mergify: remove rebase_fallback option from queue action config

focus-android/app/src/main/res/layout/dialog_add_to_homescreen2.xml
This adds margins and constraints according to the initial [design](https://www.figma.com/file/2V6wgf9fRFdYfLaf5c3oPj/Product-UI?node-id=2133%3A282824&t=TFcwwSOB4oYYtlBa-0) .
Also added margin to dialog buttons to avoid text overlapping (Figma design does not have margins, the buttons even overlap).
**BEFORE:**
English / German (long text) / RTL
**AFTER:**
English / German (long text) / RTL
=> Bug 1805840 - Fix layout for add to home screen  with ETP warning.

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/cookiebanners/GeckoCookieBannersStorage.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/cookiebanners/GeckoCookieBannersStorageTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/cookiehandling/CookieBannersStorage.kt, docs/changelog.md
=> Bug 1806924 - Add the API to allow to persist cookie banner handling exceptions in private

android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/ui/CrashListAdapter.kt, docs/changelog.md
Allow share links from crash dumps to be accessible using Talkback.
https://user-images.githubusercontent.com/35462038/209953453-69f6304f-1e58-4ceb-9605-4dd8a60f8eaa.mp4
It is worth noting that the chime sound is also played before every link, as explained [here](https://support.google.com/accessibility/android/answer/6378148?hl=en).
=> Bug 1802975 - Allow crash dumps to be shared using Talkback

focus-android/app/src/androidTest/java/org/mozilla/focus/activity/EnhancedTrackingProtectionSettingsTest.kt, focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt, focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsPrivacyMenuRobot.kt, focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/ThreeDotMainMenuRobot.kt
=> Bug 1802607: UI tests workaround for ETP not loading on first run

docs/contribute/release_checklist.md
There's almost certainly more updates that need to be made to this as we continue to migrate to the monorepo, but this at least better covers the current state of things for the upcoming merge day.
=> Bug 1808596 - Update release checklist documentation for AC/Focus

focus-android/app/src/androidTest/java/org/mozilla/focus/activity/OldFirstRunTest.kt, focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/HomeScreenRobot.kt, focus-android/app/src/androidTest/java/org/mozilla/focus/screenshots/FirstRunScreenshots.kt
Bug 1802604 - Fix flaky `firstRunOnboardingTest` UI test ✅ successfully passed 100x on Firebase.
=> Bug 1802604 - Fix flaky firstRunOnboardingTest UI test

.github/workflows/bugzilla-format.yml
When checking if the commit messages are using the correct format, we want to ignore commit messages that are created by mergify that starts with "Merge". Changes are https://github.com/gabrielluong/bugzilla-format/commit/5991a8b033042fc641d96bb79351d8a7d77a049e
https://bugzilla.mozilla.org/show_bug.cgi?id=1808364
=> Bug 1808364 - Part 2: Bump bugzilla-format action to ignore commit messages that starts with "Merge"

focus-android/app/src/androidTest/assets/etpPages/adsTrackers.html, focus-android/app/src/androidTest/assets/etpPages/analyticsTrackers.html, focus-android/app/src/androidTest/assets/etpPages/otherTrackers.html, focus-android/app/src/androidTest/assets/etpPages/socialTrackers.html, focus-android/app/src/androidTest/assets/storage_check.html, focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt
For https://mozilla-hub.atlassian.net/browse/MTE-453
The BrowserRobot verifyPageContent() method was changed during the API 30 updates, but an assertion was omitted, which is needed to validate the test result. Since this method is widely used in our tests, it is important to have it return the correct results.
Added the assertion and the retries in case of failure, to ensure the stability is not affected. …
=> Bug 1809609 - adds UI test page content assertion and retries

.mergify.yml, .taskcluster.yml, taskcluster/android_taskgraph/transforms/complete.py, taskcluster/ci/complete/kind.yml
Reverts mozilla-mobile/firefox-android#542
The branch protection rule requires complete-pr on main, so we need to coordinate a change to that rule before we can re-land this.
https://bugzilla.mozilla.org/show_bug.cgi?id=1810150
=> Revert "Bug 1810150 - don't run pull-request task graphs when we already have a push graph"

focus-android/app/src/main/res/values/strings.xml
Adjusting the moz:RemovedIn version to 111 in https://github.com/mozilla-mobile/firefox-android/commit/d07784c0b3827561394768b601bf6592319b3ba1 which landed today. Current Nightly is 111 https://whattrainisitnow.com/
https://bugzilla.mozilla.org/show_bug.cgi?id=1809972
=> Bug 1809972 - Part 2: Use the correct moz:RemovedIn version for cookie banner CFR strings

focus-android/app/src/main/res/values/strings.xml
https://github.com/mozilla-l10n/android-l10n/pull/583#discussion_r1073896504. We removed the localization string comments in https://github.com/mozilla-mobile/firefox-android/commit/d07784c0b3827561394768b601bf6592319b3ba1. However, each string must have a localization note. This PR adds back those deleted localization note
https://bugzilla.mozilla.org/show_bug.cgi?id=1809972
=> Bug 1809972 - Part 3: Re-add the removed localization string comments for the cookie banner CFR

taskcluster/ci/ui-test-focus/kind.yml
For [bug](https://bugzilla.mozilla.org/show_bug.cgi?id=1811280)
Under the Focus worker (Fenix has this), we should retry on exit 20 for if a Firebase Test Lab infrastructure error occurs (e.g, [here](https://github.com/mozilla-mobile/firefox-android/runs/10740656576)
https://firebase.google.com/docs/test-lab/ios/command-line#script-exit-codes
See: https://github.com/mozilla-mobile/fenix/blob/main/taskcluster/ci/ui-test/kind.yml#L100
For worker in https://github.com/mozilla-mobile/firefox-android/blob/main/taskcluster/ci/ui-test-focus/kind.yml#L28
https://bugzilla.mozilla.org/show_bug.cgi?id=1811280
https://bugzilla.mozilla.org/show_bug.cgi?id=1811280
=> Bug 1811280 - Add worker retry on Firebase infrastructure error

focus-android/app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingController.kt, focus-android/app/src/main/java/org/mozilla/focus/fragment/onboarding/OnboardingSecondFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1806066
=> Bug 1806066 - Finish onboarding when Focus is set as default browser from OS settings.

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/utils/EngineVersion.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/utils/EngineVersionTest.kt, docs/changelog.md
This will help conditionally execute code depending on the GeckoView release channel which may have different functionalities enabled at compile time.
https://bugzilla.mozilla.org/show_bug.cgi?id=1811448
=> Bug 1811448 - Expose the GeckoView release channel in EngineVersion utils

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt, docs/changelog.md
Added method to handle non-digit step values passed with `DateTimePrompt.stepValue`. Can be tested using https://codepen.io/alexp7777/pen/YzavNYg.
https://bugzilla.mozilla.org/show_bug.cgi?id=1811183
=> Bug 1811183 - Handle non-digit step values passed for time input

focus-android/app/src/main/java/org/mozilla/focus/cookiebannerexception/CookieBannerExceptionDetailsPanel.kt, focus-android/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1812378
=> Bug 1812378 - Fix cookie_banner_exception_panel_description_state_off_for_site string

android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehavior.kt, android-components/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehaviorTest.kt, android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadDialogFragment.kt, android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt, android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ext/DownloadState.kt, android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ui/DownloaderAppAdapter.kt, android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt, android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/ext/DownloadStateKtTest.kt, docs/changelog.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1812518
=> Bug 1812518 - Allow clients to style the download dialogs

android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt
This reverts commit 514baf1cce46fb8ad011f1f69dabd026d11bd5e9.
Post notifications permission should be requested but not required for downloads. Handling this will require more modifications than the initial commit introduced.
Note that the other [commit](https://github.com/mozilla-mobile/firefox-android/pull/604/commits/dc4b74953c12400d105b2f2af55aea27ac075720) included in the [PR](https://github.com/mozilla-mobile/firefox-android/pull/629) landed in fixed an existing bug in the code and does not need reverting.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on …
=> Revert "Bug 1796348 - Add post notification permission requirement for downloads."

docs/changelog.md
Formatted all `[bug #ticket_number]` to `[bug ticket_number]` in the changelog.
https://bugzilla.mozilla.org/show_bug.cgi?id=1811801
=> Bug 1811801 - Use [bug ticket_number] format for previous changelog entries

focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt, focus-android/app/src/main/java/org/mozilla/focus/utils/Settings.kt, focus-android/app/src/main/res/values/preference_keys.xml, focus-android/quality/detekt-baseline.xml
Replace usages with isFirstRun.
https://bugzilla.mozilla.org/show_bug.cgi?id=1802214
=> Bug 1802214 - Remove redundant getAppLaunchCount.

android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksFeature.kt, android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/RedirectDialogFragment.kt, android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/SimpleRedirectDialogFragment.kt, android-components/components/feature/app-links/src/main/res/values/strings.xml, android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksFeatureTest.kt, android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/SimpleRedirectDialogFragmentTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1814130
=> Bug 1814130 - Add prompt to "open in app" in normal tabs

focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt, focus-android/app/src/main/java/org/mozilla/focus/widget/TelemetrySwitchPreference.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1813582
=> Bug 1813582  - Added checks for TelemetryWrapper.startSession() and TelemetryWrapper.stopSession() not to be called multiple times.

.github/workflows/ac-sync-strings.yml, .github/workflows/focus-sync-strings.yml, .github/workflows/import-l10n.yml
CC @gabrielluong 
This pull request restores the original cronjob time for the "import l10n" workflow, and improve the commit message for clarity.
Changes to the sync workflows are mostly for clarity:
* Use of env variables to avoid repetitions, and simplify reuse for other products (e.g. Fenix)
* Use latest versions of ubuntu and actions (most use a deprecated version of node at this point)
There should be no practical changes to the workflow, I've only used `uplift` instead of `sync` in the branch name. Both actions have been tested on my fork.
- **Breaking Changes**: If this is a breaking …
=> Bug 1814338 - Improve l10n GitHub Workflows

focus-android/app/src/main/assets/error_style.css, focus-android/app/src/main/java/org/mozilla/focus/engine/AppContentInterceptor.kt, focus-android/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1812517
=> Bug 1812517 - Update error pages for https and expired certificate. Modified the texts and added a link.

android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/PocketStoriesConfig.kt, android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/PocketStoriesService.kt, android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/spocs/SpocsUseCases.kt, android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/spocs/api/SpocsEndpoint.kt, android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/spocs/api/SpocsEndpointRaw.kt, android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/PocketStoriesConfigTest.kt, android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/PocketStoriesServiceTest.kt, android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/spocs/SpocsUseCasesTest.kt, android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/spocs/api/SpocsEndpointRawTest.kt, android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/spocs/api/SpocsEndpointTest.kt, docs/changelog.md
Added `site` parameter to Pocket sponsored stories request, can be overridden by clients using `PocketStoriesConfig`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1811531
=> Bug 1811531 - Add 'site' query parameter to Pocket sponsored stories request

android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/PocketStoriesConfig.kt, android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/spocs/api/SpocsEndpointRaw.kt, android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/PocketStoriesConfigTest.kt, android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/spocs/SpocsUseCasesTest.kt, android-components/components/service/pocket/src/test/java/mozilla/components/service/pocket/spocs/api/SpocsEndpointRawTest.kt, docs/changelog.md
Added `country` and `city` query parameters to Pocket sponsored stories request. These can be overridden 
https://bugzilla.mozilla.org/show_bug.cgi?id=1811537
=> Bug 1811531 - Add 'country' and 'city' query parameter to Pocket sponsored stories request

focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt, focus-android/app/src/main/java/org/mozilla/focus/utils/Settings.kt, focus-android/app/src/main/res/values/preference_keys.xml, focus-android/quality/detekt-baseline.xml
This reverts commit 76f9abc8b973612c7f6665bf8201e5952d9393f5.
See [bug 1814508#c10](https://bugzilla.mozilla.org/show_bug.cgi?id=1814508#c10).
https://bugzilla.mozilla.org/show_bug.cgi?id=1802214
=> Revert "Bug 1802214 - Remove redundant getAppLaunchCount."

android-components/components/browser/menu2/src/main/java/mozilla/components/browser/menu2/BrowserMenuController.kt, android-components/components/browser/menu2/src/main/java/mozilla/components/browser/menu2/ext/MenuPositioningData.kt, android-components/components/browser/menu2/src/main/java/mozilla/components/browser/menu2/ext/PopupWindow.kt, android-components/components/browser/menu2/src/main/res/values/dimens.xml, android-components/components/browser/menu2/src/test/java/mozilla/components/browser/menu2/ext/PopupWindowTest.kt, android-components/components/concept/menu/src/main/java/mozilla/components/concept/menu/MenuStyle.kt
Adds settings to account for spacing between the menu view and the list (created by `elevation` + `cardUseCompatPadding`) and setting extra offset to shift the item even further. 
I followed the approach that was implemented in the `BrowserMenu.v1` with calculating parameters separately and storing them in `MenuPositioningData` class.
NB: in order it work, we have to pass the [search_selector](https://searchfox.org/mozilla-mobile/source/fenix/app/src/main/res/layout/search_selector.xml#12), not the view with the same icon from the `HomeFragment` as it has a different size (added margins).
- …
=> Bug 27998 – Add settings to BrowserMenu to overlap anchor view completely

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt, focus-android/buildSrc/src/main/java/FocusDependencies.kt
See the bug for changelog links.
https://bugzilla.mozilla.org/show_bug.cgi?id=1815551
=> Bug 1815551 - Update Sentry to version 6.13.1

android-components/components/feature/media/src/main/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeature.kt, android-components/components/feature/media/src/test/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeatureTest.kt, docs/changelog.md
When media session is destroyed, we forget clearing ` FLAG_KEEP_SCREEN_ON`. So we should clear it when active session is nothing or not fullscreen.
https://bugzilla.mozilla.org/show_bug.cgi?id=1813416
=> Bug 1813416 - Clear FLAG_KEEP_SCREEN_ON when playing media is finished.

android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt, android-components/components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
and avoid to have a too long filename.
https://bugzilla.mozilla.org/show_bug.cgi?id=1815195
=> Bug 1815195 - Avoid a redundant file extension when saving a real pdf file

focus-android/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1816058
=> Bug 1816058 - Fix error pages strings for https and expired certificate.

taskcluster/android_taskgraph/transforms/build_apk.py
https://github.com/mozilla-mobile/firefox-android/pull/720#pullrequestreview-1289628557 turned out to be a valid concern. 
Fixes[1]:
```
[task 2023-02-14T10:07:18.792Z] + ../taskcluster/scripts/get-secret.py -s project/mobile/focus-android/nightly -k firebase -f app/src/nightly/res/values/firebase.xml
[task 2023-02-14T10:07:18.996Z] Outputting secret to: /builds/worker/checkouts/vcs/focus-android/app/src/nightly/res/values/firebase.xml
[task 2023-02-14T10:07:18.996Z] Traceback (most recent call last):
[task 2023-02-14T10:07:18.996Z]   File "../taskcluster/scripts/get-secret.py", line 71, in <module>
[task 2023-02-14T10:07:18.996Z]     main()
[task 2023-02-14T10:07:18.996Z]   File "../taskcluster/scripts/get-secret.py", line 67, in main
[task 2023-02-14T10:07:18.996Z] …
```
=> Bug 1808605 - part 28: Do not include non-existing secrets on Focus

taskcluster/android_taskgraph/transforms/signing_apk.py
Fixes[1]:
```
2023-02-14T10:22:19    DEBUG -  404 downloading https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/TY5A-Ed0RrCuIg025WJeKA/artifacts/public%2Fchain-of-trust.json.sig: 404; body={
"code": "ResourceNotFound",
"message": "Artifact not found\n\n---\n\n* method:     getLatestArtifact\n* errorCode:  ResourceNotFound\n* statusCode: 404\n* time:       2023-02-14T10:22:19.921Z",
"requestInfo": {
"method": "getLatestArtifact",
"params": {
"0": "public/chain-of-trust.json.sig",
"taskId": "TY5A-Ed0RrCuIg025WJeKA",
"name": "public/chain-of-trust.json.sig"
},
"payload": {},
"time": "2023-02-14T10:22:19.921Z"
}
}
[...]
2023-02-14T10:22:20 CRITICAL - Chain of Trust verification error!
Traceback (most recent call last):
File …
```
=> Bug 1808606 - part 9: Sign fenix-nightly with the nightly key

taskcluster/ci/lint/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1816629
=> Bug 1816629 - ci: bump max-run-time for lint tasks from 10 to 20 minutes

README.md
POST FENIX MIGRATION:
@gabrielluong and I cleaned up the Monorepo README by providing some first information, and linking to the project-specific README files. This isn't perfect yet, but much better than the placeholder we have now.
https://bugzilla.mozilla.org/show_bug.cgi?id=1803130
https://bugzilla.mozilla.org/show_bug.cgi?id=1803130
https://bugzilla.mozilla.org/show_bug.cgi?id=1803130
=> Bug 1803130 - Update README to reflect Fenix migration

.git-blame-ignore-revs
Bring in and update the commit hashes. Adjusted comments too to map to actual commit messages on this repo.
https://bugzilla.mozilla.org/show_bug.cgi?id=1803130
=> Bug 1803130 - Update .git-blame-ignore-revs to reflect Fenix migration

taskcluster/ci/startup-test/kind.yml
Fixes[1]:
```
[task 2023-02-14T11:35:10.857Z] executing ['bash', '-cx', "../taskcluster/scripts/get-secret.py -s project/mobile/fenix/firebase -k firebaseToken -f .firebase_token.json --json && wget 'https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/LlnFRTvsRfCa7Aoql_kxXw/artifacts/public/build/fenix/arm64-v8a/target.apk' -O app.apk && wget 'https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/fzUBQlSiQi2fkWpfjpdDUg/artifacts/public/build/fenix/noarch/target.apk' -O android-test.apk && automation/taskcluster/androidTest/ui-test.sh arm-start-test app.apk android-test.apk 1"]
[task 2023-02-14T11:35:10.859Z] + ../taskcluster/scripts/get-secret.py -s project/mobile/fenix/firebase -k firebaseToken -f .firebase_token.json --json
[task 2023-02-14T11:35:10.859Z] bash: …
```
=> Bug 1808605 - part 29: Run `startup-test` from the fenix folder

fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/CookieBannersFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialog.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/dialog/CookieBannerReEngagementDialogUtils.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Re-open as https://github.com/mozilla-mobile/fenix/pull/28824 was closed because of the monorepo migration.
https://bugzilla.mozilla.org/show_bug.cgi?id=1816186
=> Bug 1816186 - Use detect-only just when we can show the re-engagement dialog

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1816683
=> Bug 1816683 - Fix AC version not displayed in verifyAboutFirefoxPreview UI test

.cron.yml, taskcluster/ci/ui-test-apk/kind.yml
We would like to run our current test `Task` `legacy-arm` on `github-push` but not be blocking the `complete` `task` as these are not required for PR and Push. We can try setting the `code-review: false` attribute on the `Task`. From then, we can turn off the `Cron` for this `Task`. This is for running a smaller assortment of UI tests on legacy APIs and older Android devices on Firebase Test Lab (for crash and compatibility testing)
This will introduce some time (20min or so) on spinning the task on Github until finish on push (the target [devices](https://github.com/mozilla-mobile/firefox-android/blob/289b44804e7750d0dbc44fe46061e41e344e2768/fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml#L39) are medium/high availability until finish (currently 6 devices in …
=> Bug 1815504 - Convert existing legacy-arm Task to soft dependency

focus-android/app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.kt, focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/TestHelper.kt
Failing on the Beta 111 branch, as the feature is not yet enabled. Will need to uplift this after it is approved.
https://bugzilla.mozilla.org/show_bug.cgi?id=1816778
=> Bug 1816778 - Adds GV channel condition to PDF reader UI test

fenix/app/src/main/res/layout/pbm_shortcut_popup.xml, fenix/app/src/main/res/values/strings.xml
Update the Private Browsing Mode CFR text that currently says, “Launch next private tab in one tap.” to say “Launch your next private tab in one tap" [as per the original issue](https://github.com/mozilla-mobile/fenix/issues/28114)
https://bugzilla.mozilla.org/show_bug.cgi?id=1816892
=> Bug 1816892 - Update the Private Browsing Mode CFR text

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt, android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/activity/GeckoViewActivityContextDelegate.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/activity/GeckoViewActivityContextDelegateTest.kt, android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt, android-components/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehaviorTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineView.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineViewTest.kt, android-components/components/feature/session/src/test/java/mozilla/components/feature/session/SwipeRefreshFeatureTest.kt, android-components/components/support/test-fakes/src/main/java/mozilla/components/support/test/fakes/engine/FakeEngineView.kt, android-components/samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt
This bug implements the GeckoView.ActivityContextDelegate in AC. The purpose of this feature is to give GeckoView access to the containing activity to start a PrintManager (or for potential other uses). Not to be confused with the runtime delegate of GeckoActivityDelegate, which is tightly tied to webauthn.
https://bugzilla.mozilla.org/show_bug.cgi?id=1809919
=> Bug 1809919 - Implement ActivityContextDelegate in AC

fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/NotificationPermissionDialogScreen.kt
– Using `OnboardingPage` added in [fenix#28630](https://github.com/mozilla-mobile/fenix/pull/28630) in NotificationPermissionDialogScreen.
– Reopening this from [Fenix](https://github.com/mozilla-mobile/fenix/pull/28776) because of migration.
https://bugzilla.mozilla.org/show_bug.cgi?id=1808358
=> Bug 1808358 - Use OnboardingPage component in NotificationPermissionDialogScreen

fenix/app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt, fenix/app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorageTest.kt
While debugging a UI test, we found that the messaging feature was being queried during the storage initialization and acting on the cached value alone. This could lead us to no longer receiving new messages during the app lifetime.
For the unit tests, we switched from mocking the entire feature to mocking just the `FeaturesInterface` as the test was providing false-positive results. It's better to create a real feature in any case for the other testing needs.
Co-authored-by: Benjamin Forehand Jr …
=> Bug 1816196 - Do not fetch messaging during storage initialization

taskcluster/ci/build-apk/kind.yml, taskcluster/ci/test-apk/kind.yml, taskcluster/ci/test-components/kind.yml
Regression from the Fenix repo migration. By moving the repo to firefox-android we now have 2 `github-pull-request` events. We need to explicitly call out `github-pull-request-untrusted` if we want jobs to run there. 
There was another bug along the way: these jobs got optimized away for the same reason as https://github.com/mozilla-mobile/firefox-android/pull/793. 
Here's taskgraph-diff run against the `parameters.yml` file in  https://github.com/mozilla-mobile/firefox-android/pull/800: 
```diff
--- optimized_task_graph@494d69711963
+++ optimized_task_graph@bug-1816945
@@ -1,20 +1,21 @@
+build-apk-fenix-debug
build-docker-image-android-build
build-docker-image-base
build-docker-image-ui-tests
complete-pr
complete-pr-1
complete-pr-2
complete-pr-3 …
```
=> Bug 1816945 - Ensure Focus/Fenix builds and unit tests run on (untrusted) PRs

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
The bug blocking the test was fixed. Re-enabled the test now and ran it on Firebase for 50 times to check for flakiness, all green:  https://github.com/mozilla-mobile/firefox-android/pull/841/checks?check_run_id=11385569028
https://bugzilla.mozilla.org/show_bug.cgi?id=1810531
=> Bug 1810531 - Re-enable Fenix UI test: saveAndOpenPdfTest

fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/res/layout/fragment_browser.xml
Talkback now announces the title of the tab switched to using swipe left or right gestures on the navbar.
https://user-images.githubusercontent.com/32488956/218774755-0680500f-657c-4b08-94e1-2ef3bd7ab62c.mp4
https://bugzilla.mozilla.org/show_bug.cgi?id=1813877
=> Bug 1813877 - Announce page title with talkback when swiping on navbar

fenix/app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt, fenix/app/src/main/res/values/strings.xml
Allowed Pocket homepage header `Learn more` link to be mentioned as clickable to a11y services, similar to what we did for the [wallpaper collection `Learn more` button](https://github.com/mozilla-mobile/fenix/pull/27277). Changes from this PR only affect the header when accessed from a11y services, otherwise only the `Learn more` link is clickable.
https://user-images.githubusercontent.com/35462038/219621552-0b9134db-aa26-43eb-90d2-3cfd95ab957c.mp4 …
=> Bug 1807369 - Improve accessibility for 'Learn more' hyperlink from the Pocket homepage header

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolder.kt, fenix/app/src/main/res/values/strings.xml, fenix/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingTrackingProtectionViewHolderTest.kt
Restore showing a different description of the Tracking Protection feature in application's onboarding if the Total Cookie Protection feature is not yet public.
The new description mentioning Total Cookie Protection will only be shown if the Total Cookie Protection CFR is to also be shown.
| If TCP is enabled | If TCP is disabled |
| --- | --- |
| <img src="https://user-images.githubusercontent.com/11428869/219096883-2f1ade67-c512-4973-9e0e-adeb3ef16cba.png" /> | <img src="https://user-images.githubusercontent.com/11428869/219097019-17211d59-b6be-44fa-8c3c-0d7a464e36f6.png" /> |
- **Breaking …
=> Bug 1816724 - Show previous ETP message in onboarding if TCP is not enabled

fenix/app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt, fenix/app/src/test/java/org/mozilla/fenix/IntentReceiverActivityTest.kt
Change IntentReceiverActivity so that if the incoming intent has the private_browsing_mode extra set to true, it overrides the openLinksInAPrivateTab setting. This allows external apps to set this flag for sites they want opened in a private app explicitly.
External apps cannot force the link to open in a non-private tab if openLinksInAPrivateTab is enabled, in that case the extra will be ignored.
This is similar to an old fennec feature ( https://bugzilla.mozilla.org/show_bug.cgi?id=1347583 ), however I used the "private_browsing_mode" extra name since it already appears in the code, instead of the "private_tab" extra that fennec used.
Bugzilla bug is 1807531, GitHub bug is https://github.com/mozilla-mobile/fenix/issues/26158
- **Milestone**: Make sure issues closed by this pull request …
=> Bug 1807531 - Honor private_browsing_mode value from external intents

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Bug 1807289 - Fix collections related UI tests that were affected by timeouts.
Summary:
- Removed excessive scrolling when interacting with the collections
- Used UI automator instead of compose to interact with the collections
- Minor timing syncing adjustments 
Based on the results from #788, I'm confident that the problem is solved.
The most affected collections UI tests successfully passed 200x on Firebase ✅ 
`verifyExpandedCollectionItemsTest`
`renameCollectionTest`
`swipeLeftToRemoveTabFromCollectionTest`
`swipeRightToRemoveTabFromCollectionTest`
`mainMenuSaveToExistingCollection`
- …
=> Bug 1807289 - Fix collections related UI tests

fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Enables [Recents URL sharing](https://developer.android.com/guide/components/activities/recents#url-sharing) so users can share links to recently viewed web content directly from the Recents screen.
https://user-images.githubusercontent.com/38040960/220072399-6fafcdfa-d6c3-4d68-b11d-3c603c249ab6.mp4
https://bugzilla.mozilla.org/show_bug.cgi?id=1817726
=> Bug 1817726 - Add Recents url sharing

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/Chip.kt, fenix/app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
A past refactoring resulted in the functionality still working as intended - no more than 8 topics being selectable at a time but when a topic would be automatically deselected this would not show - that topic would still be displayed as selected.
Moving the implementation to a new `FilterChip` Compose api fixes the UI issue and also allows for more idiomatic code and fixes a previously disabled UI test
https://user-images.githubusercontent.com/11428869/219696716-70b0caca-9204-49fb-80d3-2db079e66266.mp4 …
=> Bug 1816867 - Ensure Pocket topics selections are properly shown

fenix/app/src/main/java/org/mozilla/fenix/compose/list/ExpandableListHeader.kt
The PR fixes the bug `Collection expand/collapse chevron not displayed from a certain length of title`
| Issue  | Fix |
| ------------- | ------------- |
| https://user-images.githubusercontent.com/48829350/204004973-edce88a1-f94d-40d5-bb47-716f0c983110.mp4 | https://www.loom.com/share/0599cfadc63348c29caf06257760e498 |
https://bugzilla.mozilla.org/show_bug.cgi?id=1815634
=> Bug 1815634 - Set weight and fill to text to display collection expand / collapse chevron for any length of title

fenix/app/src/main/java/org/mozilla/fenix/home/recentsyncedtabs/view/RecentSyncedTab.kt
This content originally had a fixed height of 180, but it does not actually need this to be set as a `Modifier` property, since the card's contents will naturally make this larger than 180.
The text cut-off manifested after [replacing the fixed height of 36 from the top-level `Button` Composable](https://bugzilla.mozilla.org/show_bug.cgi?id=1813905) with the up-to-date padding values. The padding increase (in order to match the figma) caused the button to be bigger than what was allowed by the card's fixed height, causing the text to be vertically truncated. The [figma](https://www.figma.com/file/hJfV1KGZuOK7OYr29pooL5/Synced-tabs?node-id=334%3A14730&t=aKEEiisG4lp6r04a-0) for this homescreen component does not have the accurate padding represented, making the value of 180 misleading and …
=> Bug 1815185 - Remove fixed height from `RecentSyncedTab`

android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt, android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
Add "maps" as part of the domain that we strip when deciding if two domains are the same.  (example: maps.google.com is the same as www.google.com)
The reason here is that we do not want to trigger the prompt to the user twice when the redirect from maps.google.com to www.google.com/maps happened.
https://bugzilla.mozilla.org/show_bug.cgi?id=1816932
=> Bug 1816932 - Add Maps to app links common sub domains

fenix/app/src/main/java/org/mozilla/fenix/settings/logins/LoginsFragmentStore.kt
The PR allows users to search their logins using their username 
https://www.loom.com/share/c9cc5340166d4e15964f36dd17a9594f
[fnx-39-fix.webm](https://user-images.githubusercontent.com/93866435/220068930-b00087b1-11f3-4846-b117-5e9af97fdac6.webm)
https://bugzilla.mozilla.org/show_bug.cgi?id=1812447
=> Bug 1812447 - Search Logins by Username

docs/shared/versioning.md
Bug 1818572 - Adds new versioning doc
Create new shared doc that describes versioning best practices for Fenix and Focus in the new monorepo
https://bugzilla.mozilla.org/show_bug.cgi?id=1818572
https://bugzilla.mozilla.org/show_bug.cgi?id=1818572
=> Bug 1818572 - Document versioning for Fenix and Focus

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt, fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Use custom tab to display the privacy notice when interacting with the "Read our privacy notice" button from the onboarding screen.
https://user-images.githubusercontent.com/35462038/220962553-d16daf1b-d53c-419c-9d55-980c8caaf853.mp4
https://bugzilla.mozilla.org/show_bug.cgi?id=1818015
=> Bug 1818015 - Use custom tab to show privacy notice during onboarding

fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml, fenix/automation/taskcluster/androidTest/robo-test.sh, taskcluster/ci/ui-test-apk/kind.yml
[Bug 1817250 - Add/Enable Robo Test on Firebase Test Lab](https://github.com/mozilla-mobile/firefox-android/commit/60fd1ecb68f42412de603faf5f0c198c4b51f9d0)
To assist with finding client-side crashes in Firefox for Android, we can run Robo test on Firebase Test Lab to target a device pool and API target and run the testing tool crawler. Robo test analyzes the structure of an app's user interface and then explores it methodically, automatically simulating user activities. This can be helpful in finding crashes.
PR adds:
* New `ui-test-apk` `task` for Robo Test for `fenix` (`code-review` off, push only)
* New script (clone of `ui-test.sh`) with adjustments in calls for Robo test
* New Flank config for targeting Robo test specifics
Of note: Robo test does not require a test app APK …
=> Bug 1817250 - Add/Enable Robo Test on Firebase Test Lab

fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/res/layout/fragment_browser.xml
A previous PR (https://github.com/mozilla-mobile/firefox-android/pull/790) introduced accessibilityLiveRegion for EngineView in order for talkback to dictate when swiping to another tab on navbar. This change lead to talkback dictating the title/url of the current page even when tapping empty spaces or when certain elements lose focus (see videos below). Changing the implementation from using live regions to the announceForAccessibility method seems to fix this issue.
| Previous implementation with live region  | Current implementation with announceForAccessibility |
| ------------- | ------------- |
|  <video src="https://user-images.githubusercontent.com/32488956/221524352-ce66a20a-85ea-445a-a734-24d7d454366e.mp4"> |  <video src="https://user-images.githubusercontent.com/32488956/2215244 …
=> Bug 1817611 - Revert using live region for talkback on navbar swipe

fenix/app/src/main/java/org/mozilla/fenix/settings/logins/view/SavedLoginsListView.kt
The PR increases the clickable area of the `Learn more about Sync` in the Logins and passwords- Saved logins page
| Issue | Fix |
| ----- | --- |
| ![FNXOSS-58](https://user-images.githubusercontent.com/2725300/216322497-9281abd3-c1c6-46d7-afd9-1c11cd51adbe.gif) | [FNXOSS-56 FIX.webm](https://user-images.githubusercontent.com/2725300/216570647-86dac6d5-d6f0-4c04-9af3-f61e832b9252.webm) | …
=> Bug 1812196 - Sets height of `Learn more about Sync` in Logins and passwords- Saved logins

taskcluster/ci/build-apk/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1819094
=> Bug 1819094 - Set track-apk-size for fenix-debug/nightly/beta/release builds

fenix/buildSrc/src/main/java/org/mozilla/fenix/gradle/tasks/ApkSizeTask.kt
Our `ApkSizeTask` regressed by https://github.com/mozilla-mobile/firefox-android/commit/07ee3642ad1b959ac55c946228cf5dd97e147af0, which changed the variant names to include `fenix` as a prefix. The task basically just looked at the wrong output folder, based on this change.
Before: `../debug/app-fenix-x86-debug.apk`
After: `../fenix/fenixDebug/app-fenix-x86-debug.apk`
https://bugzilla.mozilla.org/show_bug.cgi?id=1819094
https://bugzilla.mozilla.org/show_bug.cgi?id=1819094
=> Bug 1819094 - Fix ApkSizeTask to work for new variant names

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt, fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
Discovered another scenario in which the Home Page is displayed instead of the browsing fragment that was supposed to be displayed.
[Bugzilla](https://bugzilla.mozilla.org/show_bug.cgi?id=1817524)
##Steps to reproduce
1. Open normal browsing tab and navigate to a site (ex wikipedia)
2. Open a new private browsing tab and navigate to a site
3. Switch to the previously opened normal browsing tab.
4. Open tabs tray and close the private browsing tab.
##Expected behavior
After the tabs tray is closed, the normal browsing tab is still open.
##Actual behavior
Home page is displayed.
- **Breaking …
=> Bug 1817524 - Do not show homepage if last tab of section is closed while not in view

fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt, fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
When interacting with the homescreen private browsing button we should also navigate to `SearchDialogFragment`, allowing the user to start a new private search. This was unintentionally removed in https://github.com/mozilla-mobile/fenix/pull/27262.
5. The APK links should be on the right side of the screen, named for …
=> Bug 1818774 - Navigate to search dialog when interacting with homescreen private browsing button

fenix/app/src/main/res/layout/delete_history_time_range_dialog.xml
The PR fixes accessibility issue on the History deletion screen. The fixes include:
- ~Increased contrast ratio on `Delete` and `Cancel` buttons (achieved by making the card background darker)~
- Dynamic height of radio buttons (achieved with `wrap_content` property)
PS: This is a minor UI change only, and thus does not require writing tests under PR checklist
Updated card background color to achieve the desired contrast ratio.
- **Breaking Changes**: If this is a breaking change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the …
=> Bug 1813451 - Fix accessibility issues on History deletion screen

fenix/app/src/main/res/layout/studies_section_item.xml, fenix/app/src/main/res/values/integers.xml, fenix/app/src/main/res/values/styles.xml
The PR fixes the `Active` text truncate issue on Studies screen.
1. Open the app and restart it once.
2. Enable the Debug menu by tapping the Firefox icon from Settings > About Firefox 5 times.
3. Enroll in an experiment by tapping a branch from Settings > Nimbus Experiments > experiment name.
4. Go to Settings > Data collection > Studies.
5. Observe the “Active” section.
https://www.loom.com/share/ddda083d88a0449198eac73868969a76
https://www.loom.com/share/6875b27b4349474aae8d34ce22ee998c
**QA**
1. Click on Checks at the top of the PR page.
2. Click on the firefoxci-taskcluster group on the left to expand all tasks.
3. Click on the build-debug task.
4. Click on View task in Taskcluster in the new DETAILS section. …
=> Bug 1815631 - changed height and reduced padding for `Active` text from the Studies menu

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
This affected a lot of the logins tests, but after fixing it, there's still one bug remaining that is causing failures in these tests: https://bugzilla.mozilla.org/show_bug.cgi?id=1812426
If the tests become blocking, we'll start disabling them until the bug is fixed.
https://bugzilla.mozilla.org/show_bug.cgi?id=1807273
https://bugzilla.mozilla.org/show_bug.cgi?id=1807283 …
=> Bug 1807273 - Prevent keyboard blocking the login saving prompt in UI tests

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabSheetBehaviorManager.kt
For some reason, the CI did not catch this when landing https://github.com/mozilla-mobile/firefox-android/pull/1013. 
This test was throwing an error about a typing mismatch. Simply allowing it to match the function signature of `BottomSheetBehavior` (allowing `View` and any of its subtypes) fixes the issue.
5. The …
=> Bug 1819733 - Fix broken tests in `TabSheetBehaviorManagerTest`

android-components/components/support/rusthttp/build.gradle, android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt, android-components/plugins/dependencies/src/main/java/Gecko.kt
A ~test~ patch to see if removing the failing dependencies from the support-rusthttp has any effect. 
Forcing the build as well for added safety, but this shouldn't change with the cherry-picked GV and Glean bumps.
https://bugzilla.mozilla.org/show_bug.cgi?id=1819776
=> Bug 1819776 - Remove unused test dependencies from support-rusthttp

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Bug 1807283 - re-enable `verifyJumpBackInSectionTest` UI test 
Summary:
- Switched to compose when verifying the "Jump back in" item details on the home screen
- Also refactored the test a bit to match the manual test from TestRail
✅ Successfully passed 100x **without the retry rule**.
5. The APK links should be on …
=> Bug 1807283 - re-enable verifyJumpBackInSectionTest UI test

fenix/app/src/main/java/org/mozilla/fenix/onboarding/MarketingNotificationHelper.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1819927
=> Bug 1819927 - Remove DEFAULT_BROWSER_NOTIFICATION_ID from MarketingNotificationHelper 

android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/helper/DisplayOrientationListener.kt, android-components/components/compose/cfr/src/test/java/mozilla/components/compose/cfr/helper/DisplayOrientationListenerTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1819746
=> Bug 1819746 - Fix for possible NullPointerException on a potential nullable object reference in DisplayOrientationListener

android-components/components/support/rusthttp/build.gradle, android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
These dependencies are not needed and for some reason this fixes the build failure we are seeing on CI that is expecting the artifact `androidx.test:monitor:1.4.0`.
=> Bug 1819776 - Remove unused test dependencies from support-rusthttp (partial backport #1061)

fenix/build.gradle
Follow up to https://github.com/mozilla-mobile/firefox-android/pull/1098 to fix the link to the Fenix unit test report. Focus is already correct.
https://bugzilla.mozilla.org/show_bug.cgi?id=1820129
=> Bug 1820129 - Fix Fenix test result report URL

taskcluster/scripts/toolchain/external-gradle-dependencies.sh
Addresses the first part of the problem described in [bug 1820129](https://bugzilla.mozilla.org/show_bug.cgi?id=1820129#c0).
https://bugzilla.mozilla.org/show_bug.cgi?id=1820129
https://bugzilla.mozilla.org/show_bug.cgi?id=1820129
=> Bug 1820129 - part 1: Do not let Gradle tests silently fail anymore

android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/ext/PromptRequest.kt, android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt, android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/ext/PromptRequestTest.kt, docs/changelog.md
Showing the YouTube issue fixed:
https://user-images.githubusercontent.com/11428869/223170127-e7a11f1b-1729-4697-ae04-8d67f5b2fb52.mp4
https://bugzilla.mozilla.org/show_bug.cgi?id=1819254
=> Bug 1819254 - Don't exit fullscreen for user input prompts

fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt, fenix/app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt, fenix/app/src/main/res/values/strings.xml, fenix/app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
Verdi [reviewed](https://docs.google.com/document/d/1Byj50kRrg8fVRqEDQ06DuYnBeN0eH1tKZiU95i9CSD0/edit) unified search feature, and one of follow up [requirements](https://www.figma.com/file/epu0Sj6mCPk7K282sNpHgI/Site?node-id=3754%3A51165&t=O5Yn6gDdSKHYkGwO-4) was to search for an url instead of loading it for non default search engines. We had a call after that, and agreed on the final requirements. From the ticket:
_Not just topic specific, but non default general search engines also should search for an url instead of loading it. Also should change the prompt for those as well: in case the general search engine is selected, the text should be changed from Search or enter address to "Enter search terms"._
https://user-images.githubusercontent.com/92760693/221651584-41956842-a351-4ed4-b27 …
=> Bug 1817519 – force search for not default engines

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt
Summary:
Removed running conditions for UI tests related to the "PDF reader" feature and for youControlYourDataCardTest UI test, both are now available on all current releases. …
=> Bug 1820746 - Remove running conditions for UI tests related to the "PDF reader" feature and for youControlYourDataCardTest UI test

fenix/app/src/main/res/layout/fragment_add_login.xml
For having the minimum of target size for the delete button,
following the other examples in code, i modified it's height to 48dp.
https://bugzilla.mozilla.org/show_bug.cgi?id=1820552
=> Bug 1820552 - Increase Site's field x button in Add new login

taskcluster/ci/browsertime/kind.yml
This patch fixes an issue with the speedometer3 task that currently has a symbol of `None` but it should be `sp3`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1820553
https://bugzilla.mozilla.org/show_bug.cgi?id=1820553
https://bugzilla.mozilla.org/show_bug.cgi?id=1820553
https://bugzilla.mozilla.org/show_bug.cgi?id=1820553
=> Bug 1820553 - Fix speedometer3 task naming for Fenix.

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt, android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt, docs/changelog.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1806741
=> Bug 1806741 - Expose hasRuleForBrowsingContext API

taskcluster/ci/test-apk/kind.yml
Forgot to update the `notify` route in `test-apk` CI task for the mono-repo. Just need to update some headers and links.
https://bugzilla.mozilla.org/show_bug.cgi?id=1821088
https://bugzilla.mozilla.org/show_bug.cgi?id=1821088
=> Bug 1821088 - Update notify block in test-apk CI task

fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1817070
=> Bug 1817070 - Add strings used for experimentation with Re-engagement notifications

taskcluster/android_taskgraph/util/scriptworker.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1821128
=> Bug 1821128 - Use correct beetmover folder prefix for fenix nightly

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt, fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt
Added telemetry for the homescreen no collections placeholder close (`X`) button.
https://bugzilla.mozilla.org/show_bug.cgi?id=1821032
=> Bug 1821032 - Add telemetry for the homescreen no collections placeholder close button

taskcluster/android_taskgraph/transforms/release_started.py, taskcluster/ci/release-notify-started/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1817058
=> Bug 1817058 - add github log link to release promotion notification email

fenix/app/build.gradle, fenix/buildSrc/src/main/java/FenixDependencies.kt
Was probably mistakenly added back in a different rebased PR. Removing for good.
https://bugzilla.mozilla.org/show_bug.cgi?id=1820130
=> Bug 1820130 - Remove unused accompanist insets dependency

android-components/.buildconfig.yml, fenix/.buildconfig.yml, focus-android/.buildconfig.yml, taskcluster/scripts/lint/update_buildconfig_from_gradle.py
Bug found in https://github.com/mozilla-mobile/firefox-android/pull/948
The parser in `taskcluster/scripts/lint/update_buildconfig_from_gradle.py` originally comes from https://github.com/mozilla-mobile/android-components/pull/7617 and https://github.com/mozilla-mobile/android-components/pull/8594. 
@csadilek could you take a look at the generated `.buildconfig.yml` and let me know if you see anything suspicious? 
https://bugzilla.mozilla.org/show_bug.cgi?id=1820125
https://bugzilla.mozilla.org/show_bug.cgi?id=1820125
https://bugzilla.mozilla.org/show_bug.cgi?id=1820125
https://bugzilla.mozilla.org/show_bug.cgi?id=1820125
https://bugzilla.mozilla.org/show_bug.cgi?id=1820125
https://bugzilla.mozilla.org/show_bug.cgi?id=1820125
https://bugzilla.mozilla.org/show_bug.cgi?id=1820125 …
=> Bug 1820125 - Let `.buildconfig.yml` contain transitive dependencies

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
Bug 1821285 - New credit card deletion UI tests and other refactoring work
Summary:
- Created new UI tests based on the toDoAutomation [notes](https://testrail.stage.mozaws.net/index.php?/cases/view/1512798) from TestRail
- All tests successfully passed 100x on Firebase ✅ 
5. The APK links should be on the right side …
=> Bug 1821285 - New credit card deletion UI smoke tests and other refactoring work

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddToHomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Bug 1821266 - Refactor privateModeScreenItemsTest UI test
Summary:
- Removed unnecessary steps to match the manual test we have in TestRail
- Simplified the way we check the Private Browsing home screen elements
- The test successfully ran 100x on Firebase ✅ 
5. The APK links should be on the right side of the screen, …
=> Bug 1821266 - Refactor privateModeScreenItemsTest UI test

fenix/app/nimbus.fml.yaml, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/static_strings.xml, fenix/app/src/main/res/xml/secret_settings_preferences.xml
created a different branch with a different approach suggested by @gabrielluong [here](https://github.com/mozilla-mobile/firefox-android/pull/1180#issuecomment-1463025531).
I kept using the preference settings (it actually made fixing UI tests much easier, thanks again, gl, for the tip). I changed the pref name to enable unified search for had it disabled manually, to address Roger's concern as well. …
=> Bug 1821261 – Enables unified search on nightly

android-components/plugins/dependencies/src/main/java/Gecko.kt
This patch manually updates GV Beta to 112.0.20230313153916.
=> Update to GeckoView Beta 112.0.20230313153916 on releases_v112

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsGeneralTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuTabsRobot.kt
Bug 1821973 - New tabs option summary updates UI tests
Summary:
- Renamed SettingsBasicTest to SettingsGeneralTest class
- Created a new UI test `verifyTabsOptionSummaryUpdatesTest` ✅ successfully passed 100x on Firebase. …
=> Bug 1821973 - New tabs option summary updates UI tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsGeneralTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHomepageTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SponsoredShortcutsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
Bug 1821986 - new opening screen option summary updates UI smoke test
`verifyHomepageOptionSummaryUpdatesTest` ✅ successfully passed 100x on Firebase.
https://bugzilla.mozilla.org/show_bug.cgi?id=1821986
=> Bug 1821986 - new opening screen option summary updates UI smoke test

fenix/.git-blame-ignore-revs
This file is a leftover post migration. https://github.com/mozilla-mobile/firefox-android/blob/2d0ce92593ecb04e24397c3947d1c8862c76041f/.git-blame-ignore-revs was already updated and contain the up-to-date hashes.
https://bugzilla.mozilla.org/show_bug.cgi?id=1803130
=> Bug 1803130 - Remove leftover .git-blame-ignore-revs file

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt
Note: the disabling of the Private theme will be examined at-large in [Bug 1820897](https://bugzilla.mozilla.org/show_bug.cgi?id=1820897)https://bugzilla.mozilla.org/show_bug.cgi?id=1820897 
https://user-images.githubusercontent.com/87384386/224806154-a60466ef-54f1-4b47-b6fc-b5fb4bf38b63.mov
5. The APK links should be …
=> Bug 1814994 - Create Tabs Tray list and grid layouts

fenix/buildSrc/src/main/java/AndroidComponents.kt
AndroidComponents.kt in Fenix is no longer used in the Monorepo and contains an outdated version. Let's remove it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1822375
=> Bug 1822375 - Remove unneeded and now incorrect AndroidComponents.kt

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ThreeDotMenuMainTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Bug 1822267 - Improve coverage for "Edit bookmarks" related UI tests.
Summary:
- Updated `editBookmarkTest` based on the toDoAutomation note from TestRail
- Created a new UI test cancelEditBookmarkTest based on the toDoAutomation note from TestRail
- Other refactoring work
Both bookmark editing UI tests successfully passed 100x on Firebase ✅ 
4. Click on `View task in Taskcluster` in …
=> Bug 1822267 - Improve coverage for "Edit bookmarks" related UI tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SponsoredShortcutsTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1821016
=> Bug 1821016 - Disable openPocketStoryItemTest and verifySponsoredShortcutsSettingsOptionTest UI tests

fenix/app/messaging.fml.yaml, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1821466
=> Bug 1821466 - Add nimbus message for fullscreen research surface

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1814032
=> Bug 1814032 - Retry attempts for address autofill in UI tests

fenix/app/src/main/java/org/mozilla/fenix/compose/ext/Modifier.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/wallpaper/WallpaperSettings.kt
Added debouncing to the button click event for `WallpaperThumbnailItem` so that a rapid second click doesn't trigger the snackbar again before the new `currentWallpaper` is set from the initial click. …
=> Bug 1809809 - debounce click events on wallpaper settings

fenix/app/.experimenter.yaml, fenix/app/nimbus.fml.yaml, fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1821718
=> Bug 1821718 - Add feature and nimbus flag for juno onboarding

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1820897
=> Bug 1820897 - Disable the private theme from being used in the Composified Tabs Tray

fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt
This fix is the Compose analog of a patch from a few weeks ago. https://github.com/mozilla-mobile/fenix/pull/28792
https://bugzilla.mozilla.org/show_bug.cgi?id=1815620
=> Bug 1815620 - Truncate long tab titles before they are composed

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationPing.kt
There is a race condition when generated hashed Ad IDs because we were using a single metric rather than separate metrics for each.
https://bugzilla.mozilla.org/show_bug.cgi?id=1822283
=> Bug 1822283 - Fix race condition for Ad IDs

fenix/app/src/test/java/org/mozilla/fenix/gleanplumb/state/MessagingMiddlewareTest.kt
Store.dispatch launches a coroutine. If we return to the test before we launch there's a chance the store is (still) idle and the tests proceed without the action being applied.
The test fails intermittently, but pretty consistently in for https://github.com/mozilla-mobile/firefox-android/pull/1190. Let's fix it.
https://bugzilla.mozilla.org/show_bug.cgi?id=1822394
=> Bug 1822394 - Fix intermittent failures in MessagingMiddlewareTest

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt, fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1822606
=> Bug 1822606 - Refactor HomeFragment.navigateToSearch() to the ToolbarController

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingNotificationTest.kt, fenix/app/src/main/java/org/mozilla/fenix/gleanplumb/MessageNotificationWorker.kt
Fixes [EXP-3184](https://mozilla-hub.atlassian.net/browse/EXP-3184).
Fixes [Bug 1821464](https://bugzilla.mozilla.org/show_bug.cgi?id=1821464).
https://bugzilla.mozilla.org/show_bug.cgi?id=1821464
=> Bug 1821464 Add UI test to NotificationWorker

fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, focus-android/app/src/main/java/org/mozilla/focus/browser/integration/FullScreenIntegration.kt, focus-android/app/src/test/java/org/mozilla/focus/browser/integration/FullScreenIntegrationTest.kt
| Result on Fenix | Result on Focus |
| --- | --- |
| <video src="https://user-images.githubusercontent.com/11428869/225364322-5c853785-17cc-45c7-b4a8-6ff78a055653.mp4" /> | <video src="https://user-images.githubusercontent.com/11428869/225364404-f46652cf-89eb-4184-be68-360e7cfad6e1.mp4" /> |
5. The APK links should …
=> Bug 1816059 - Show the notification for entering fullscreen as a Toast

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/home/TabCounterView.kt, fenix/app/src/test/java/org/mozilla/fenix/home/TabCounterViewTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1822634
=> Bug 1822634 - Refactor tab counter code from HomeFragment into TabCounterView

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
https://user-images.githubusercontent.com/87384386/225459214-e7a61dee-77e5-44ac-8014-72419650ccfd.mov
https://bugzilla.mozilla.org/show_bug.cgi?id=1814995
=> Bug 1814995 - Add private tabs to `TabsTray`

fenix/app/src/main/java/org/mozilla/fenix/compose/home/HomeSectionHeader.kt
Talkback does not mention "Show all" as a button in the Recently visited section
https://www.loom.com/share/78849456150c422cb6958b1f69ae0582
https://www.loom.com/share/7470a8dd1f8c48dc89d44c9dff19819d
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
https://bugzilla.mozilla.org/show_bug.cgi?id=1809815
=> Bug 1809815 - Talkback does not mention `Show all` as a button in the Recently visited section

fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
The PR fixes accessibility issue for autocomplete edit text (URL)
- Increased tap area to 48dp for auto complete edit text (URL)
For other accessibility issues that haven't been fixed:
- Touch target for clear button hasn't been fixed ~ as it requires changing xml resource (will need UI confirmation)
- For clickable item on the dropdown, requires updating string values (and thus translation as well)
- For Search engine, the tap area is already increased to 48dp, thus scanner result is a false positive
PS: This is a minor UI change only, and thus does not require writing tests under PR checklist
Fix applied by increasing tap area to 48dp
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) …
=> Bug 1813450 - Increase tap area for autocomplete edit text in address bar

fenix/app/src/main/res/layout/fragment_tracking_protection_blocking.xml
TalkBack mentions activate actions for read only items in ETP settings info panels
https://user-images.githubusercontent.com/39338964/222073399-c77e19d0-cdf9-451a-b811-24609c408dae.mp4
https://user-images.githubusercontent.com/39338964/222073590-931bde99-d23d-4788-951b-c4cc43ab8099.mp4
https://bugzilla.mozilla.org/show_bug.cgi?id=1807558
=> Bug 1807558 - TalkBack mentions activate actions for read only items in ETP settings info panels

android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/helper/DisplayOrientationListener.kt, android-components/components/compose/cfr/src/test/java/mozilla/components/compose/cfr/helper/DisplayOrientationListenerTest.kt, docs/changelog.md
Seems like on Android 33 the current orientation detection calls do not report valid results.
As such on newer Android versions we'll use another way to infer the current rotation based on the configuration read from Resources.
Tested the changes on:
- Samsung J3 with Android api level 22
- Emulator of Android api level 29 
- Emulator of Android api level 30
- Samsung A51 with Android api level 31
- Emulator of Android api level 29 
- Pixel 7 (and a tablet emulator) with Android api level 33
Result on a Pixel 7 with Android 13 on which previously the CFR would not get automatically dismissed:
https://user-images.githubusercontent.com/11428869/225631503-d7e777c4-c7d4-41d7-9083-57d73b458357.mp4
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR …
=> Bug 1819950 - Ensure a change of orientation on new Androids will dismiss CFRs

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt, fenix/app/src/main/java/org/mozilla/fenix/home/toolbar/ToolbarController.kt, fenix/app/src/main/java/org/mozilla/fenix/home/toolbar/ToolbarInteractor.kt, fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/recentvisits/interactor/RecentVisitsInteractorTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/toolbar/DefaultToolbarControllerTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1822744
=> Bug 1822744 - Refactor ToolbarController and ToolbarInteractor into their own files

fenix/app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt, fenix/app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorageTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1822899
=> Bug 1822899 - Limit Nimbus message display count to max display count

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
The PR will display a snackbar when a new tab is added to a collection
| Issue video | Fix Video |
| ----------- | --------- |
| https://www.loom.com/share/2d199e00f9f94c4fb3c7b0e9adafbab3 | https://www.loom.com/share/c4bb32ffac174b8388d739fae0b1f966 |
---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time.
https://bugzilla.mozilla.org/show_bug.cgi?id=1812736
=> Bug 1812736 - Display snackbar when a new tab is added to a collection

android-components/components/feature/search/src/main/res/layout/mozac_search_widget_small.xml
This PR fixes issue where microphone icon is not placed correctly in 2x1 widget for Firefox Focus app.
> Bugzilla issue [#1802627](https://bugzilla.mozilla.org/show_bug.cgi?id=1802627))
> GitHub issue [#7547](https://github.com/mozilla-mobile/focus-android/issues/7547) 
**Reproduction step**
https://user-images.githubusercontent.com/13991373/223920673-b6a6d18d-f5d1-4d72-b7c8-1210c7cd471a.mov 
<br> **Fix Description**
Changed parent container to `RelativeLayout` to distribute two child views in start & end of the parent container.
> No additional tests added
- Screenshot
- Recording
https://user-images.githubusercontent.com/13991373/223920980-d14e3f1a-cf63-4436-a5e4-d7f13ede9a70.mov
- **Milestone**: Make sure issues closed by this pull request are added to the …
=> Bug 1802627 - Microphone icon is incorrectly placed on the 2x1 size widget

fenix/app/src/main/java/org/mozilla/fenix/compose/button/FloatingActionButton.kt
Added Composable FAB, which supports animations similar to the existing new tab/sync FAB.
https://user-images.githubusercontent.com/35462038/222423705-a5e6b1b0-17ac-4ac8-94ff-c65146a42666.mp4 …
=> Bug 1815011 - Create a top-level FAB Composable

focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt, focus-android/app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt, focus-android/app/src/main/java/org/mozilla/focus/utils/FocusSnackbar.kt, focus-android/quality/detekt-baseline.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1646242
=> Bug 1646242 - Avoid crashes when requireContext is called and fragment is no longer attached.

focus-android/.editorconfig
https://bugzilla.mozilla.org/show_bug.cgi?id=1823059
=> Bug 1823059 - Replace deprecated ktlint_disabled_rules.

taskcluster/ci/startup-test/kind.yml
Bug 1819153 is still problematic on Firebase Test Lab.
`build-type: nightly` -> `build-type: nightly-firebase` let's try this
https://bugzilla.mozilla.org/show_bug.cgi?id=1819153
https://bugzilla.mozilla.org/show_bug.cgi?id=1819153
=> Bug 1819153 - Adjust startup task to resolve NoSuchMethodError on Firebase Test Lab

fenix/app/src/androidTest/assets/pages/externalLinks.html, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/WebControlsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuOpenLinksInAppsRobot.kt
Bug 1822611 - New open links in apps related UI smoke tests
Summary:
- Refactored existing UI smoke test to match the new functionality
- Created new UI smoke tests based on TestRail toDoAutomation notes
- Added running conditions (the upgraded feature is not available yet on the RC, 111 branch)
- Added a Youtube link to the `externalLinks.html` asset because it didn't work properly with the Playstore link from `generic3.html`
✅ All 10 UI tests successfully passed 100x on Firebase. 
2. Click on the `firefoxci-taskcluster` group on the left …
=> Bug 1822611 - New open links in apps related UI smoke tests

taskcluster/ci/config.yml, taskcluster/ci/external-gradle-dependencies/kind.yml
Let
https://bugzilla.mozilla.org/show_bug.cgi?id=1820122
https://bugzilla.mozilla.org/show_bug.cgi?id=1820122
https://bugzilla.mozilla.org/show_bug.cgi?id=1820122
https://bugzilla.mozilla.org/show_bug.cgi?id=1820122
https://bugzilla.mozilla.org/show_bug.cgi?id=1820122
https://bugzilla.mozilla.org/show_bug.cgi?id=1820122
=> Bug 1820122 - Use b-android-xlarge to speed up external-gradle-dependencies jobs

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsGeneralTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Bug 1822823 - Refactor `settingsGeneralItemsTests` UI test ✅ successfully passed 100x on Firebase.
https://bugzilla.mozilla.org/show_bug.cgi?id=1822823
=> Bug 1822823 - Refactor settingsGeneralItemsTests UI test

focus-android/app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteCustomDomainsPreference.kt, focus-android/app/src/main/java/org/mozilla/focus/autocomplete/AutocompleteDefaultDomainsPreference.kt, focus-android/app/src/main/java/org/mozilla/focus/biometrics/BiometricAuthenticationFragment.kt, focus-android/app/src/main/java/org/mozilla/focus/browser/integration/BrowserMenuController.kt, focus-android/app/src/main/java/org/mozilla/focus/cookiebanner/CookieBannerRejectAllPreference.kt, focus-android/app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsPreference.kt, focus-android/app/src/main/java/org/mozilla/focus/settings/ManualAddSearchEngineSettingsFragment.kt, focus-android/app/src/main/java/org/mozilla/focus/settings/SettingsFragment.kt, focus-android/app/src/main/java/org/mozilla/focus/utils/SupportUtils.kt, focus-android/app/src/main/java/org/mozilla/focus/widget/TelemetrySwitchPreference.kt, focus-android/app/src/test/java/org/mozilla/focus/TestFocusApplication.kt, focus-android/app/src/test/java/org/mozilla/focus/animation/TransitionDrawableGroupTest.java, focus-android/app/src/test/java/org/mozilla/focus/biometrics/BiometricAuthenticationFragmentTest.kt, focus-android/app/src/test/java/org/mozilla/focus/cfr/CfrMiddlewareTest.kt, focus-android/app/src/test/java/org/mozilla/focus/contextmenu/ContextMenuCandidatesTest.kt, focus-android/app/src/test/java/org/mozilla/focus/locale/LocalesTest.java, focus-android/app/src/test/java/org/mozilla/focus/menu/BrowserMenuControllerTest.kt, focus-android/app/src/test/java/org/mozilla/focus/searchwidget/ExternalIntentNavigationTest.kt, focus-android/app/src/test/java/org/mozilla/focus/sitepermissions/SitePermissionOptionsStoreTest.kt, focus-android/app/src/test/java/org/mozilla/focus/telemetry/HistogramTest.kt, focus-android/app/src/test/java/org/mozilla/focus/telemetry/ProfilerMarkerFactProcessorTest.kt, focus-android/app/src/test/java/org/mozilla/focus/topsites/DefaultTopSitesStorageTest.kt, focus-android/app/src/test/java/org/mozilla/focus/utils/IntentUtilsTest.kt, focus-android/app/src/test/java/org/mozilla/focus/utils/SupportUtilsTest.kt, focus-android/app/src/test/java/org/mozilla/focus/whatsnew/WhatsNewVersionTest.kt, focus-android/app/src/test/resources/robolectric.properties, focus-android/quality/detekt-baseline.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1819123
=> Bug 1819123 - Re-evaluate usage of robolectric in Focus unit tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerReductionTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/EnhancedTrackingProtectionTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeveloperToolsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsGeneralTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHTTPSOnlyModeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Bug 1823707 - Refactor settingsAdvancedItemsTest UI tests
`settingsAdvancedItemsTest` successfully passed 100x on Firebase. ✅ 
https://bugzilla.mozilla.org/show_bug.cgi?id=1823707
=> Bug 1823707 - Refactor settingsAdvancedItemsTest UI tests

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt, fenix/app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
The UNDO Snackbar is outside of the scope of this ticket, and will be completed in Bug 1823999.
https://bugzilla.mozilla.org/show_bug.cgi?id=1821206
=> Bug 1821206 - Implement composified tab list click listeners

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt
Fixes [Bug 1823492](https://bugzilla.mozilla.org/show_bug.cgi?id=1823492).
https://bugzilla.mozilla.org/show_bug.cgi?id=1823492
=> Bug 1823492 Add timing metric for Adjust Attribution Listener

fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/UpgradeOnboarding.kt
Removing the speculative fix from the Onboarding.
Forcing LTR on Android 5.1 devices did not lower crash rates and should be removed.
https://bugzilla.mozilla.org/show_bug.cgi?id=1824027
=> Bug 1824027 - Revert speculative fix for Onboarding RTL crash

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/home/toolbar/SearchSelectorBinding.kt, fenix/app/src/main/java/org/mozilla/fenix/home/toolbar/SearchSelectorMenuBinding.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1823848
=> Bug 1823848 - Add binding classes to handle the home search selector toolbar

fenix/app/src/androidTest/assets/pages/cross-site-cookies.html, fenix/app/src/androidTest/assets/pages/trackingPage.html, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/EnhancedTrackingProtectionTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/EnhancedTrackingProtectionRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionExceptionsRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionRobot.kt
Adds some new tests for all ETP options, trackers blocked, adding and removing exceptions.
Also improved the coverage of existing tests.
Worked on improving the stability of tests.
Ran on Firebase multiple times, all green.
Before merging, we should wait for https://github.com/mozilla-mobile/firefox-android/pull/1340 as they might have a conflict.
4. Click on `View task in Taskcluster` …
=> Bug 1823929 - New ETP UI tests

fenix/app/src/main/java/org/mozilla/fenix/settings/logins/controller/SavedLoginsStorageController.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt, fenix/app/src/main/res/navigation/nav_graph.xml
The PR fixes the issue where `saved Login Page` is shown after a new `login` is added
https://www.loom.com/share/3b5cc33e7a7a4ae79282531292666c52
[fnx-15-fix.webm](https://user-images.githubusercontent.com/93866435/214651093-fc6a787e-5456-4aa5-878c-1354a6820782.webm)
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
**GitHub Automation**
Fixes …
=> Bug 1815628 - Refactored Navigation Graph to show `Saved Login Page` after new Credentials added. 

fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsFragment.kt
The PR fixes saved Logins not updating immediately a login is deleted
Navigate back to the saved login screen, rather than just popping back stack 
[fnx-58-issue.webm](https://user-images.githubusercontent.com/93866435/216845977-f84bf078-76b6-4fc9-a02b-10649605c509.webm)
[fnx-58-fix.webm](https://user-images.githubusercontent.com/93866435/216846010-0f993584-f300-40cc-a9ff-acc418ce14b7.webm)
---
This code was written and …
=> Bug 1799622 - A password deleted in the password manager, is still visible in the list afterwards

android-components/components/browser/icons/src/main/assets/extensions/browser-icons/manifest.template.json, android-components/components/feature/accounts/src/main/assets/extensions/fxawebchannel/manifest.template.json, android-components/components/feature/readerview/src/main/assets/extensions/readerview/manifest.template.json, android-components/components/feature/search/src/main/assets/extensions/ads/manifest.template.json, android-components/components/feature/search/src/main/assets/extensions/search/manifest.template.json, android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json, android-components/samples/browser/src/main/assets/extensions/borderify/manifest.template.json, android-components/samples/browser/src/main/assets/extensions/test/manifest.template.json
This change has no impact, visible or not. It does not require a changelog entry.
It's not a breaking change.
https://bugzilla.mozilla.org/show_bug.cgi?id=1824341
=> Bug 1824341 - Use `browser_specific_settings` instead of `applications` in built-in manifests

fenix/nimbus.fml.yaml
=> Bug 1823794 - Disable re-engagement notification by default

android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/creditcard/CreditCardPicker.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/login/LoginPicker.kt, android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/creditcard/CreditCardPickerTest.kt, android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/login/LoginPickerTest.kt
Consume login and credit card select prompts when calling dismissCurrentLoginSelect and dismissSelectCreditCardRequest with the active prompt request as parameter.
More context can be found here https://github.com/mozilla-mobile/android-components/pull/12142#discussion_r873096373
https://bugzilla.mozilla.org/show_bug.cgi?id=1796340
=> Bug 1796340 - Consume login and credit card select prompts on dismiss

android-components/components/tooling/lint/build.gradle
https://bugzilla.mozilla.org/show_bug.cgi?id=1824052
=> Bug 1824052 - Fix compatibility warning by setting jvmTarget to 11 for KotlinCompile task

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFab.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt, fenix/app/src/main/res/layout/component_tabstray3_fab.xml
Added FAB to composed tabs tray, business logic remains to be added in [1819196](https://bugzilla.mozilla.org/show_bug.cgi?id=1819196).
https://bugzilla.mozilla.org/show_bug.cgi?id=1815013
=> Bug 1815013 - Port over the Tabs Tray FAB 

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/home/privatebrowsing/controller/PrivateBrowsingController.kt, fenix/app/src/main/java/org/mozilla/fenix/home/privatebrowsing/interactor/PrivateBrowsingInteractor.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/PrivateBrowsingDescriptionViewHolder.kt, fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/privatebrowsing/DefaultPrivateBrowsingControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/recentvisits/interactor/RecentVisitsInteractorTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1824869
=> Bug 1824869 - Add PrivateBrowsing[Interactor|Controller] for handling private browsing mode

fenix/app/src/main/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreference.kt
The search engines list does not contain any element matching the predicate
https://bugzilla.mozilla.org/show_bug.cgi?id=1823085
=> Bug 1823085 - NoSuchElementException fix

fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
https://bugzil.la/1825015
https://bugzilla.mozilla.org/show_bug.cgi?id=1825015
=> Bug 1825015 - Remove dreamlte in legacy test configuration

fenix/app/build.gradle, fenix/app/src/androidTest/java/org/mozilla/fenix/perf/StartupExcessiveResourceUseTest.kt, fenix/app/src/main/AndroidManifest.xml, fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt, fenix/app/src/main/java/org/mozilla/fenix/MozillaOnlineHomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/home/mozonline/PrivacyContentDisplayActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/home/mozonline/PrivacyContentDisplayHelper.kt, fenix/app/src/main/java/org/mozilla/fenix/perf/StrictModeManager.kt, fenix/app/src/main/res/layout/activity_privacy_content_display.xml
See ticket for motivation.
We're essentially introducing a new activity for the `MozillaOnline` build so we can show our privacy notice prompt before initializing `FenixApplication` and `HomeActivity`, which in turn would otherwise initialize all our submodules e.g., Nimbus, Glean, Gecko. This change prevents unnecessary initialization.
Verify before landing:
https://bugzilla.mozilla.org/show_bug.cgi?id=1825028
=> Bug 1825028 - Delay init of MozillaOnline build until privacy notice is accepted

android-components/gradle.properties
https://bugzilla.mozilla.org/show_bug.cgi?id=1825453
https://bugzilla.mozilla.org/show_bug.cgi?id=1825453
https://bugzilla.mozilla.org/show_bug.cgi?id=1825453
=> Bug 1825453 - Use the same Gradle jvmargs for AC as Fenix

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingHomescreenTest.kt
When #1097 landed, it upstreamed the Nimbus messaging code to components and changed the namespace for those generated classes.
Surprisingly, CI didn't rebase the original patch for bug 1819727 before landing it, leading to the main branch being busted.
This patch fixes that breakage.
cc: @jrbenny35 
5. The APK links …
=> Bug 1819727 - Fix imports for FxNimbusMessaging in UI tests

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt, fenix/app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorController.kt, fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/recentvisits/interactor/RecentVisitsInteractorTest.kt, fenix/app/src/test/java/org/mozilla/fenix/search/toolbar/DefaultSearchSelectorControllerTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1825576
=> Bug 1825576 - Refactor search selector menu handling out of SessionControlController into its own controller

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/home/HomeMenuView.kt, fenix/app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/HomeMenuViewTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1823430
=>  Bug 1823430 - Refactor home menu button dismissal into HomeMenuView

android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt, android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt
Fixes [Bug 1825549](https://bugzilla.mozilla.org/show_bug.cgi?id=1825549).
https://bugzilla.mozilla.org/show_bug.cgi?id=1825549
=> Bug 1825549 Disallow messages with blank text fields

android-components/build.gradle, android-components/settings.gradle, fenix/build.gradle, fenix/settings.gradle, focus-android/build.gradle, focus-android/settings.gradle, shared-settings.gradle
This allows code re-use in our Gradle files, which currently have quite a bit of code duplication. For now, I just unified our settings.gradle files, but as a next step we can define shared functions in this new `shared-setting.gradle` e.g., for the `getManifestVersionString` function introduced in https://github.com/mozilla-mobile/firefox-android/pull/1429/.
https://bugzilla.mozilla.org/show_bug.cgi?id=1825649
=> Bug 1825649 - Introduce shared-settings.gradle to allow reusing build logic.

android-components/settings.gradle, shared-settings.gradle
I've made a mistake when unifying our settings.gradle logic. The A-C settings.gradle had leftover logic to set the nightly version, which needs to be moved to the share-settings.gradle file.
https://bugzilla.mozilla.org/show_bug.cgi?id=1825649
=> Bug 1825649 - Fix A-C nightly builds after adding shared settings.gradle

taskcluster/android_taskgraph/target_tasks.py, taskcluster/ci/startup-test/kind.yml, taskcluster/ci/ui-test-apk/kind.yml
Hopefully the last fix needed for https://bugzil.la/1819153.
Can confirm `startup-test-nightly-arm` is scheduled with the additional build-type (testing as part of `main-repo-cron-nightly.yml` using newer parameters offered by @jcristau [1]
`% taskgraph target-graph -p taskcluster/test/params/main-repo-cron-nightly.yml` 
[1] https://firefox-ci-tc.services.mozilla.com/api/queue/v1/task/Twes5msbQ3-AnHAaElEX4Q/runs/0/artifacts/public/parameters.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1819153
Previous change in https://github.com/mozilla-mobile/firefox-android/commit/4893d00c4adb2b725c8e71f4f1ef09b06deadbe4 where the `build-type` was adjusted to a build with no optimizations suitable for Firebase Test Lab
https://bugzilla.mozilla.org/show_bug.cgi?id=1819153 …
=> Bug 1819153 - Add nightly-firebase build type in nightly tasks + cleanup

fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
Device seems to still (Apr. 4) be hitting frequent inconclusive result (infrastructure error) on Firebase Test Lab on recent commits on `firefox-android` likely due to another Play Services update on the device. I'll reach out to Firebase Test Lab Community Slack again.
https://bugzilla.mozilla.org/show_bug.cgi?id=1825279
=> Bug 1825279 - Remove dreamlte device in legacy test configuration

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt, fenix/app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
Enabled existing logic to dismiss tabs tray when tapping outside of the bottom sheet.
https://bugzilla.mozilla.org/show_bug.cgi?id=1819439
=> Bug 1819439 - Add logic to dismiss tabs tray when user taps outside

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Bug 1826568 - Minor changes related to system notification UI smoke tests
Summary:
- Added the `@ Smoketest` annotation to `videoPlaybackSystemNotificationTest`
- Moved `audioPlaybackSystemNotificationTest` to MediaNotificationTest class …
=> Bug 1826568 - Minor changes related to system notification UI smoke tests

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Bug 1824928 - Fix and re-enable open links in apps UI tests.
Summary:
- Changed the way we check that the Youtube app is opened
- Had to refactor the UI tests to mach the current manual tests (all sort of changes were made in the meantime)
All tests successfully passed 100x on Firebase. ✅ 
5. The APK links should be …
=> Bug 1824928 - Fix and re-enable open links in apps UI tests

android-components/components/service/nimbus/src/main/res/layout/mozac_service_nimbus_branch_item.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1814138
=> Bug 1814138 - Fix nimbus branch item check mark visibility

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
- ~~**Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.~~ …
=> Bug 1825130 - Mark extension as disabled/enabled when it gets disabled/enabled by Gecko(View)

fenix/app/nimbus.fml.yaml
Now that we can test with experiment on beta, disabling on nightly. More context in the bug.
https://bugzilla.mozilla.org/show_bug.cgi?id=1826874
=> Bug 1826874 - Disable juno onboarding on nightly and developer

fenix/app/nimbus.fml.yaml
https://bugzilla.mozilla.org/show_bug.cgi?id=1827119
=> Bug 1827119 - Disable notification pre permission prompt by default

focus-android/app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.kt
Remove running condition for UI tests related to the "PDF reader" feature as It's now available on all current releases.
https://bugzilla.mozilla.org/show_bug.cgi?id=1827381
=> Bug 1827381 - Remove running condition for UI tests related to the PDF reader feature

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
- ~~**Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues.~~ …
=> Bug 1828094 - Mark extension as uninstalled when it gets uninstalled by Gecko(View)

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt, fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
I discovered that Private tabs do not support multi selection, so rather than adding this part of business logic into the Compose code, I opted for adding it to the Controller with some unit test coverage. 
Note that the close tab UI does not properly hide itself with the grid items (list items function correctly). This will be addressed [here](https://bugzilla.mozilla.org/show_bug.cgi?id=1826670).
https://user-images.githubusercontent.com/87384386/230489340-2fa25c13-bc16-49be-9ccf-5d6e40665e39.mov
2. Click on the `firefoxci-taskcluster` …
=> Bug 1821425 - Add the logic to show the selected tab UI and the multiselection tab UI

fenix/app/src/androidTest/assets/pages/mutedVideoPage.html, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestAssetHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSitePermissionsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TextSelectionTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSitePermissionsCommonRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSitePermissionsExceptionsRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSitePermissionsRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SitePermissionsRobot.kt
Had to recreate PR https://github.com/mozilla-mobile/firefox-android/pull/1426.
https://bugzilla.mozilla.org/show_bug.cgi?id=1824136
https://bugzilla.mozilla.org/show_bug.cgi?id=1828663
=> Bug 1824136 - New tests coverage for site permissions settings

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/ext/SearchEngine.kt, fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/search/RadioSearchEngineListPreference.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1827686
=> Bug 1827686 - Add telemetry for user updating Default Search Engine

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Note: the business logic for the FAB has yet to land via https://github.com/mozilla-mobile/firefox-android/pull/1562, so any syncs during testing will need to be manual syncs via Settings. …
=> Bug 1814992 - Add `SyncedTabsList` to `TabsTray`

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Bug 1807270 - Re-enable open tabs thumbnail check in UI tests.
Summary:
The`verifyOpenedTabThumbnail()` step remained disabled after I've re-enabled the two UI tests back in Dec. due to the compose refactoring work.
Both tests successfully passed 100x on Firebase ✅ …
=> Bug 1807270 - Re-enable open tabs thumbnail check in UI tests

android-components/components/browser/errorpages/build.gradle, android-components/components/feature/addons/build.gradle, android-components/components/ui/icons/build.gradle
As now Fenix and AC are in the same repo, `lint` can see the resources been used.
https://bugzilla.mozilla.org/show_bug.cgi?id=1796305
=> Bug 1796305 - Address lint unused resources

fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1825429
=> Bug 1825429 - Tapping on empty search result should cancel search mode.

taskcluster/android_taskgraph/__init__.py, taskcluster/android_taskgraph/morph.py, taskcluster/ci/config.yml, taskcluster/requirements.in, taskcluster/requirements.txt
Reverts mozilla-mobile/firefox-android#1703 until we fix the regression in taskgraph.
https://bugzilla.mozilla.org/show_bug.cgi?id=1829864
https://bugzilla.mozilla.org/show_bug.cgi?id=1805651
https://bugzilla.mozilla.org/show_bug.cgi?id=1805651
https://bugzilla.mozilla.org/show_bug.cgi?id=1805651
=> Bug 1829864 - Revert "Bug 1805651 - Update taskgraph to 5.1.0 and use index-path-regexes"

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BrowsingErrorPagesTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Bug 1829600 - Create new "No internet connection" and "Address not found" UI tests
✅ Both tests successfully passed 100x on Firebase.
https://bugzilla.mozilla.org/show_bug.cgi?id=1829600
=> Bug 1829600 - Create new "No internet connection" and "Address not found" UI tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1830030
=> Bug 1830030 - disable failing deleteCollectionTest UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuOpenLinksInAppsRobot.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/OpenLinksInAppsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
Right now even if the user set "Open links in apps" as "Always" we still prompt the user in private browsing in order to protect user's policy.  To reflect this behaviour in settings, removing "Always" as an option in private browsing.
If the user set the option to "Always", in private browsing mode the "Open links in apps" setting will still say "Ask before opening".
4. Click on `View …
=> Bug 1829937 - Remove "Always" as an option for app links in private browsing

android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt, android-components/components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
The previous fix, addressed the specific issue but introduce an unwanted code path no addressing the general issue, lets revert for now until we have general solution.
https://bugzilla.mozilla.org/show_bug.cgi?id=1810197
=> Bug 1810197 - Revert "Fix condition of changeExtension".

focus-android/app/src/androidTest/java/org/mozilla/focus/activity/SitePermissionsTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1830312
=> Bug 1830312 - Disable failing allowAudioVideoAutoplayPermissionTest UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1814032
=> Bug 1814032 - disable failing verifyAddressAutofillSelectionTest UI test

fenix/app/src/main/java/org/mozilla/fenix/downloads/StartDownloadDialog.kt, fenix/app/src/test/java/org/mozilla/fenix/downloads/StartDownloadDialogTest.kt
This should also fix the bug https://bugzilla.mozilla.org/show_bug.cgi?id=1825827 .
https://bugzilla.mozilla.org/show_bug.cgi?id=1829531
=> Bug 1829531 - Fix the status bar color when the download prompt appears.

taskcluster/android_taskgraph/transforms/external_gradle_dependencies.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1820122
=> Bug 1820122 - Do not run gradle 'test' in external-gradle-dependencies-fenix

fenix/app/src/main/java/org/mozilla/fenix/messaging/FenixNimbusMessagingController.kt
Add a licence to FenixNimbusMessagingController
https://bugzilla.mozilla.org/show_bug.cgi?id=1830902
=> Bug 1830902 - Add a licence to FenixNimbusMessagingController

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFab.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt, fenix/app/src/main/res/layout/component_tabstray3_fab.xml
https://user-images.githubusercontent.com/87384386/234960614-1a8a5123-58a6-4846-99f5-111ab0d635d2.mov
droid/blob/main/docs/changelog.md) or does not need one
https://bugzilla.mozilla.org/show_bug.cgi?id=1823999
=> Bug 1823999 - Fix UNDO Snackbar for composified Tabs Tray

fenix/app/onboarding.fml.yaml, fenix/app/src/androidTest/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapperTest.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapper.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1830849
=> Bug 1830849 - Add image resource field to Nimbus onboarding feature

fenix/app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt, fenix/app/src/test/java/org/mozilla/fenix/nimbus/NimbusSystemTest.kt
Fixes [Bug 1830080](https://bugzilla.mozilla.org/show_bug.cgi?id=1830080).
Fixes [Bug 1830079](https://bugzilla.mozilla.org/show_bug.cgi?id=1830079).
https://bugzilla.mozilla.org/show_bug.cgi?id=1830080
=> Bug 1830080 Add more careful handling of preview-collection in maybeFetchExperiments

fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt, fenix/app/src/main/java/org/mozilla/fenix/FenixLogSink.kt, fenix/app/src/test/java/org/mozilla/fenix/FenixLogSinkTest.kt, fenix/app/src/test/java/org/mozilla/fenix/HomeActivityTest.kt, fenix/app/src/test/java/org/mozilla/fenix/ServiceWorkerSupportTest.kt, fenix/app/src/test/java/org/mozilla/fenix/browser/BaseBrowserFragmentTest.kt, fenix/app/src/test/java/org/mozilla/fenix/ext/ImageButtonTest.kt, fenix/app/src/test/java/org/mozilla/fenix/ext/TopSiteTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/intent/CrashReporterIntentProcessorTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/SessionControlViewTest.kt, fenix/app/src/test/java/org/mozilla/fenix/nimbus/NimbusBranchesControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/settings/quicksettings/ConnectionDetailsInteractorTest.kt, fenix/app/src/test/java/org/mozilla/fenix/settings/quicksettings/protections/cookiebanners/DefaultCookieBannerDetailsInteractorTest.kt, fenix/app/src/test/java/org/mozilla/fenix/trackingprotection/TrackingProtectionPanelInteractorTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1825071
=> Bug 1825071 - Re-evaluate usage of robolectric in Fenix unit tests

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt, android-components/components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/content/DownloadState.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt, docs/changelog.md, fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/DownloadUtils.kt
Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1829159
https://bugzilla.mozilla.org/show_bug.cgi?id=1829371
https://bugzilla.mozilla.org/show_bug.cgi?id=1829372
=> Bug 1829372 - Allow PDF files to be opened in third party apps.

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/Matchers.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataOnQuitTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataOnQuitRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1830011
=> Bug 1830011 - New Delete browsing data on quit tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Bug 1807276 - Fix `firstRunScreenTest` and `youControlYourDataCardTest` UI tests
Summary:
Failed to scroll to the "Privacy notice" onboarding card, hence I've changed the element to be scrolled to.
✅ Both tests successfully passed 50x on Firebase.
5. The APK links should be on the right side of the screen, named for …
=> Bug 1807276 - Fix firstRunScreenTest and youControlYourDataCardTest UI tests

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Added functionality for the tabs tray banner three-dot button.
| Normal mode | Multi select mode |
| --- | --- |
| <video src="https://user-images.githubusercontent.com/35462038/236197977-c3f483da-9987-4ac2-8f06-90c607e61823.mp4" /> | <video src="https://user-images.githubusercontent.com/35462038/236198002-2c1d7e9b-27a4-4c44-9b1a-137914c113c4.mp4" /> |
4. Click on `View task in …
=> Bug 1816517 - Add functionality for the three-dot button in the tabs tray page indicator

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Created new search bookmarks related UI tests based on our [manual tests](https://testrail.stage.mozaws.net/index.php?/suites/view/3192&group_by=cases:section_id&group_id=274060&group_order=asc).
All tests successfully passed 100x on Firebase. …
=> Bug 1830045 - New search bookmarks UI tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
Bug 1815402 - Fix flaky `verifyReaderViewAppearanceUI` UI test
Summary:
Added a waitForPageToLoad() after pressing the reader view button (it actually re-loads the page)
Due to the fact that the page wasn't fully loaded, the "Appearance" button was missing from the main menu causing failures.
✅ Successfully passed 100x on Firebase.
4. Click on `View task in Taskcluster` in the new …
=> Bug 1815402 - Fix flaky verifyReaderViewAppearanceUI UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt
=> Bug 1807268 - disable failing dismissOnboardingUsingHelpTest UI test

fenix/app/src/main/res/drawable/ripple_button.xml, fenix/app/src/main/res/drawable/ripple_button_dark.xml, fenix/app/src/main/res/layout/fenix_snackbar.xml, fenix/app/src/main/res/values/styles.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1807131
=> Bug 1807131: Fix ripples for snackbar and alert dialogs

taskcluster/android_taskgraph/transforms/external_gradle_dependencies.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1833199
https://bugzilla.mozilla.org/show_bug.cgi?id=1833199
=> Bug 1833199 - Ensure that changes to Fenix & Focus dependencies rebuild the gradle cache

fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml, fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1833382
https://bugzilla.mozilla.org/show_bug.cgi?id=1833382
https://bugzilla.mozilla.org/show_bug.cgi?id=1833382
=> Bug 1833382 - Temporarily remove walleye for long queuing on Test Lab

fenix/app/src/main/java/org/mozilla/fenix/compose/button/Button.kt
When using the compose button and the size of the font is set to largest for accessibility purposes, the font should not cut if it doesn't fit. Instead, the button accommodates the entirety of the text. …
=> Bug 1830112 - Display full text in compose button when large font

fenix/app/build.gradle, fenix/settings.gradle, focus-android/app/build.gradle, focus-android/settings.gradle
Moved the code into `settings.gradle` and put it inside an `allprojects` block.  I'm not 100% sure what's going on but I think this applies the changes to android-components projects as well.  In any case, `./gradlew assembleDebug` now seems to pick up the local app-services code. …
=> Bug 1833452 - Fix app services autopublish when building Fenix/Focus

focus-android/app/src/main/java/org/mozilla/focus/cfr/CfrMiddleware.kt, focus-android/app/src/main/java/org/mozilla/focus/navigation/MainActivityNavigation.kt, focus-android/app/src/main/java/org/mozilla/focus/utils/Settings.kt, focus-android/app/src/test/java/org/mozilla/focus/cfr/CfrMiddlewareTest.kt
Fixes [Bug 1833851](https://bugzilla.mozilla.org/show_bug.cgi?id=1833851).
https://bugzilla.mozilla.org/show_bug.cgi?id=1833851
=> Bug 1833851 — Remove context param from FeatureHolder in Focus

fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1826670
=> Bug 1826670 - Hide the close button on grid items when in multiselection

.github/workflows/pull-request-labeler.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1833655
=> Bug 1833655 - Bump pull-request-labeler action to 1.0.4

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/button/FloatingActionButton.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFab.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTabLayouts.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTestTag.kt
Rather than rewrite the existing logic inside of [`TabDrawerRobot`](https://searchfox.org/mozilla-mobile/source/firefox-android/fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt) and [`TabbedBrowsingTest`](https://searchfox.org/mozilla-mobile/source/firefox-android/fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt), I created an intermediary `ComposeTabbedBrowsingTest` and `ComposeTabDrawerRobot` to perform the conversion, so that there aren’t breaking changes in 15+ files AND the two suites of tests can live in tandem until the switch-over happens.
In `ComposeTabDrawerRobot`, I opted for extension functions to obtain the Composables, as that would allow the logic of test tags, etc., to live in one unified place and could be used by both …
=> Bug 1831602 - Convert two UI tests to support composified Tabs Tray

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1830870
=> Bug 1830870 - Disable failing closeTabTest UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerReductionTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Summary:
Decided to search and try using a different website from the [rule list](https://github.com/mozilla/cookie-banner-rules-list/blob/main/cookie-banner-rules-list.json). (Sometimes the cookie banner from`voetbal24.be` remained displayed)
While searching for another suitable website, I've noticed there were [problems with other websites as well](https://bugzilla.mozilla.org/show_bug.cgi?id=1807440#c6).
I've found `startsiden.no` in the list, tested it manually on both a physical device as well as on an emulator, the cookie banner can be identified easily (for the UI tests), the dismissal works properly, and also noticed better page loading performance compared to `voetbal24.be`
Used it in our UI tests and both tests successfully passed 150x on Firebase. ✅ 
- **Breaking Changes**: If …
=> Bug 1814030 - Fix cookie banner reduction UI tests

.github/workflows/pull-request-labeler.yml
This adjusts how the action was fetching the pull request number which doesn't expose a `number` property for the [pull_request_review](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request_review) event compare to the [pull_request](https://docs.github.com/en/webhooks-and-events/webhooks/webhook-events-and-payloads#pull_request) event. This will ensure that we will mark the PR as approved or changes needed when a pull request review is submitted.
2. Click on the `firefoxci-taskcluster` group on the …
=> Bug 1833655 - Bump pull-request-labeler action to 1.0.5

.github/workflows/pull-request-labeler.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1833655
=> Bug 1833655 - Bump pull-request-labeler action to 1.0.6

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1807283
=> Bug 1807283 - Disable failing verifyJumpBackInSectionTest UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Fixes [1830870](https://bugzilla.mozilla.org/show_bug.cgi?id=1830870) and [1829838](https://bugzilla.mozilla.org/show_bug.cgi?id=1829838)
Summary:
The problems were caused when trying to close a tab using the swipe gesture, UI Automator sometimes fails to perform the swipe action, so I've switched to Espresso.
Both tests successfully ran 100x **without** the retryRule on Firebase ✅ 
4. …
=> Bug 1830870 - Fix disabled tab closing UI tests

fenix/app/src/main/res/layout/component_cookie_banner_details_panel.xml, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1834516
=> Bug 1834516 - Change the string for the cookie banner reduction report site button.

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabLayoutMediator.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt, fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/tabstray/TabLayoutObserverTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1826453
=> Bug 1826453 - Refactor tab page button click metrics

android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt, android-components/components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1835453
=> Bug 1835453 - Handling content-type with extra information correctly

android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt, android-components/components/support/utils/src/test/java/mozilla/components/support/utils/DownloadUtilsTest.kt
Moved from: https://github.com/mozilla-mobile/android-components/pull/12952
This is just a small simplification I made while I was in the area.
https://bugzilla.mozilla.org/show_bug.cgi?id=1836338
=> Bug 1836338 - Improve DownloadUtils.uniqueFileName readability.

fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/static_strings.xml, fenix/app/src/main/res/xml/secret_settings_preferences.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1836339
=> Bug 1836339 - Add a secret setting for the Compose Top Sites

fenix/app/src/main/java/org/mozilla/fenix/compose/PagerIndicator.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1836347
=> Bug 1836347 - Add default active and inactive colors for the PagerIndicator

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1807273
=> Bug 1807273 - Disable saveLoginsInPWATest UI tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
Bug 1807275 - Fix and re-enable emailLinkPWATest UI test 
Summary:
Had to add an extra step after clicking the email link, namely, to click the "Open" button from the "Open links in another app" prompt.
The test successfully passed 100x on Firebase ✅ 
5. The APK links should be on the right side of the screen, named …
=> Bug 1807275 - Fix and re-enable emailLinkPWATest UI test

docs/changelog.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1836794
=> Bug 1836794 - Start the Nightly 116 development cycle

focus-android/app/src/main/java/org/mozilla/focus/browser/integration/BrowserMenuController.kt, focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt, focus-android/app/src/main/res/values/strings.xml, focus-android/app/src/test/java/org/mozilla/focus/menu/BrowserMenuControllerTest.kt
Show a snack bar when a website is added to shortcut
[fnx-62-issue.webm](https://user-images.githubusercontent.com/35276272/224277226-f77b37ad-81da-4663-a1d6-26f5f4a86f0c.webm)
[fnx-62-fix.webm](https://user-images.githubusercontent.com/35276272/224272629-29ae582d-9b3e-4cc2-9e0c-5bab7d1f3538.webm)
---
This code was written and reviewed by GitStart Community. Growing future engineers, one PR at a time. …
=> Bug 1802010 - After adding a shortcut, show a confirmation message

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/DataChoicesFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1836887
=> Bug 1836887 - Remove telemetry probes expired in v116

fenix/app/src/main/java/org/mozilla/fenix/onboarding/ReEngagementNotificationWorker.kt, fenix/app/src/test/java/org/mozilla/fenix/onboarding/ReEngagementNotificationWorkerTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1820545
=> Bug 1820545 - Refactor isActiveUser method to remove test intermittency.

fenix/app/src/main/java/org/mozilla/fenix/browser/readermode/ReaderModeController.kt
This was likely automatically imported by mistake
https://bugzilla.mozilla.org/show_bug.cgi?id=1837059
=> Bug 1837059 - Remove stray GMS reference for annotation

fenix/app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1837208
=> Bug 1837208 - Add support for Adjust preinstall attribution tracking

fenix/app/src/main/java/org/mozilla/fenix/compose/ListItemTabLarge.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/ListItemTabLargePlaceholder.kt, fenix/app/src/main/java/org/mozilla/fenix/home/pocket/PocketStoriesComposables.kt
Reverts mozilla-mobile/firefox-android#2312
https://bugzilla.mozilla.org/show_bug.cgi?id=1821724
=> Revert "Bug 1821724 - For Portrait mode, align the Pocket column with the column title  "

fenix/app/src/androidTest/assets/pages/password.html, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1816066
=> Bug 1837568 - Revert commits causing keyboard visibility problems in UI tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsPrivacyTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SystemSettingsRobot.kt
Bug 1837378 - New system notification settings UI tests
Both tests successfully passed 100x on Firebase ✅ 
https://bugzilla.mozilla.org/show_bug.cgi?id=1837378
=> Bug 1837378 - New system notification settings UI tests

fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt, fenix/app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt, fenix/app/src/main/res/layout/fragment_share.xml
Rebased of https://github.com/mozilla-mobile/firefox-android/pull/1799
https://bugzilla.mozilla.org/show_bug.cgi?id=1816004
=> Bug 1816004 - Remove unused saveToPDF feature flags

fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1816004
=> Bug 1816004 - Remove unused unifiedSearchFeature and notificationPrePermissionPromptEnabled feature flags

fenix/build.gradle, fenix/plugins/fenixdependencies/build.gradle, fenix/plugins/fenixdependencies/settings.gradle, fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt, fenix/settings.gradle, focus-android/build.gradle, focus-android/plugins/focusdependencies/build.gradle, focus-android/plugins/focusdependencies/settings.gradle, focus-android/plugins/focusdependencies/src/main/java/FocusDependenciesPlugin.kt, focus-android/settings.gradle, taskcluster/android_taskgraph/transforms/external_gradle_dependencies.py, taskcluster/ci/external-gradle-dependencies/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1837451
https://bugzilla.mozilla.org/show_bug.cgi?id=1837478
=> Bug 1837478 - Refactor FenixDependencies into a plugin using composite build

android-components/components/browser/icons/src/main/java/mozilla/components/browser/icons/BrowserIcons.kt, fenix/app/src/test/java/org/mozilla/fenix/ext/BrowserIconsTest.kt
Also add some additional checks.
https://bugzilla.mozilla.org/show_bug.cgi?id=1825071
=> Bug 1825071 - Refactor BrowserIconsTest to remove Robolectric.

.mergify.yml
Because the github-actions bot is untrusted its PR graphs don't include ui tests, so green complete-pr is not enough to avoid breakage.
https://bugzilla.mozilla.org/show_bug.cgi?id=1838216
=> Bug 1838216 - mergify: require successful complete-push task for geckoview updates

fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1837525
=> Bug 1837525 - Load favicons directly from drawables for certain urls in the Compose Top Sites

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt
Just some small tweaks to wait before checking the titles in the tabs tray.
https://bugzilla.mozilla.org/show_bug.cgi?id=1836454
=> Bug 1836454 - Fix ComposeTabbedBrowsingTest flaky tests

fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1838391
=> Bug 1838391 - Address crash UninitializedPropertyAccessException in AddonsManagementFragment.

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt, android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/EngineDelegateMiddleware.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/EngineStateReducer.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt, android-components/components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt, android-components/samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt, docs/changelog.md
This bug adds an option to print the current page's content using the Android Print Spooler via GeckoView with status on the Engine in AC.
GeckoView bug [1837426](https://bugzilla.mozilla.org/show_bug.cgi?id=1837426) adds in the new `didPrintPageContent` to the GeckoView API first. …
=> Bug 1836778 - Add Support for Printing in GeckoEngineSession

taskcluster/android_taskgraph/transforms/push_apk.py
https://github.com/mozilla-mobile/firefox-android/blob/348dc4badab80135f016076eb7c071d478afc96d/taskcluster/android_taskgraph/transforms/push_apk.py#L45 is not needed as it is replaced in https://github.com/mozilla-mobile/firefox-android/blob/348dc4badab80135f016076eb7c071d478afc96d/taskcluster/android_taskgraph/transforms/push_apk.py#L48 as the `startup-test` config has a Fenix and Focus task in it now and those tasks are new/renamed.
https://bugzilla.mozilla.org/show_bug.cgi?id=1838662
=> Bug 1838662 - cleanup push-apk.py in firefox-android

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt, android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/EngineStateReducer.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt, docs/changelog.md, fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/share/SaveToPDFMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/share/ShareController.kt, fenix/app/src/test/java/org/mozilla/fenix/share/SaveToPDFMiddlewareTest.kt, fenix/app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt
* Adds `checkForPdfJs` to determine if page is a PDF.js page or not
* Adjusts save_to_pdf_failure to have extras of pdf, non-pdf, or unknown
* Adjusts save_to_pdf_failure to have extras of failure reason
* Adjusts save_to_pdf_tapped to have extras of pdf, non-pdf, or unknown
* Adds save_to_pdf_completed with extras of pdf, non-pdf, or unknown
4. Click on `View task in Taskcluster` in …
=> Bug 1829213 - Update Save To PDF Telemetry and checkForPdfViewer Option

fenix/app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1837864
=> Bug 1837864 – fix search settings opening visual glitch

android-components/components/support/utils/src/main/java/mozilla/components/support/utils/BrowsersCache.kt, fenix/detekt-baseline.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1838512
=> Bug 1838512 - Fix detekt issue from moving Browsers Cache utility into Android Components

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt, android-components/components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateReader.kt, android-components/components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/BrowserStateWriter.kt, android-components/components/browser/session-storage/src/main/java/mozilla/components/browser/session/storage/serialize/Keys.kt, android-components/components/browser/session-storage/src/test/java/mozilla/components/browser/session/storage/serialize/BrowserStateWriterReaderTest.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ReaderStateReducer.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/ReaderState.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/ReaderActionTest.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt, android-components/components/feature/readerview/src/main/assets/extensions/readerview/readerview.js, android-components/components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt, android-components/components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt
1.  Keep Readerview's position between active and inactive
2.  Persiste Readerview's position between restart fenix
Note:  Value of position (scrollY) is accurate, however after fenix restart , the Readerview may not remain in same place ( a bit above). This may be caused by re-generating DOM. There's no such problem when toggling between active and inactive.
4. Click on the `firefoxci-taskcluster` group on the left to expand all tasks.
5. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested in.
6. Click on `View task in …
=> Bug 1794077/1780350/1820404 Persist Readerview position

fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Updating the variable `shouldUseBottomToolbar` to use `lazyFeatureFlagPreference` instead of `booleanPreference` as if we use `booleanPreference` Nimbus isn't even initialized when `shouldUseBottomToolbar` is called hence `shouldDefaultToBottomToolbar() `does not return the expected value.
5. The APK links should be …
=> Bug 1830768 - Add nimbus flag for toolbar position

android-components/build.gradle
https://bugzilla.mozilla.org/show_bug.cgi?id=1839578
=> Bug 1839578 - Allow ktlintFormat task to modify access java.lang class fields.

android-components/build.gradle
See https://docs.gradle.org/7.6/dsl/org.gradle.api.tasks.JavaExec.html#org.gradle.api.tasks.JavaExec:main.
This is a followup to https://github.com/mozilla-mobile/firefox-android/pull/732 …
=> Bug 1802817 - Replace deprecated main with mainClass.

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/RecentlyClosedTabsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/RecentlyClosedTabsRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1839443
https://bugzilla.mozilla.org/show_bug.cgi?id=1807275
=> Bug 1839443 - Adds Recently closed tabs UI tests coverage

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/identitycredential/Account.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/identitycredential/BasicAccountsAdapter.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/identitycredential/SelectAccountDialogFragment.kt, android-components/components/feature/prompts/src/main/res/layout/mozac_feature_prompts_choose_identity_account_dialog.xml, android-components/components/feature/prompts/src/main/res/layout/mozac_feature_prompts_identity_crendential_account_item.xml, android-components/components/feature/prompts/src/main/res/values/strings.xml, android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt, android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/StringTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1836364
=> Bug 1836364 - Add a dialog for handling FedCM showAccountListPrompt

android-components/components/concept/sync/src/main/java/mozilla/components/concept/sync/OAuthAccount.kt, android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt, android-components/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/strings.xml, fenix/app/src/main/res/xml/account_settings_preferences.xml
This seems to work well - for reasons I don't fully understand, the `FxaWebChannelFeature` automagically kicks in when opening the view, so we get the correct exchange of the FxA account information between the server and the browser "for free".
I put the menu item at the top of the menu and made the English version of the string "Manage account" to match desktop.
4. Click on `View …
=> Bug 1810630 - add 'manage account' to the sync menu.

android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1836364
=> Bug 1836364 - Correctly handle the confirm action on SelectAccount prompt

focus-android/app/metrics.yaml, focus-android/app/src/main/java/org/mozilla/focus/experiments/NimbusSetup.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1840151
=> Bug 1840151 - Remove telemetry probes expiring in v118

fenix/app/build.gradle, fenix/app/src/main/AndroidManifest.xml, fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/drawable-v23/splash_screen.xml, fenix/app/src/main/res/drawable-v24/splash_screen.xml, fenix/app/src/main/res/values-night/styles.xml, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/styles.xml, fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1839522
=> Bug 1839522 – added splash screen compat implementation, tied extra duration to the experiment

fenix/app/src/main/java/org/mozilla/fenix/settings/account/AccountSettingsFragment.kt
We need the UX of this to improve before we should unleash this as a new feature on our users. Flagging @jonalmeida as he approved the bug which first landed the new option.
https://bugzilla.mozilla.org/show_bug.cgi?id=1840483
https://bugzilla.mozilla.org/show_bug.cgi?id=1840483
=> Bug 1840483 - 'manage account' is only available on Nightly/Debug builds

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TextSelectionTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Bug 1840316 - New text selection and quick actions url bar UI tests
The UI tests successfully passed 100x on Firebase. ✅ 
https://bugzilla.mozilla.org/show_bug.cgi?id=1840316
=> Bug 1840316 - New text selection and quick actions url bar UI tests

fenix/app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1840634
=> Bug 1840634 - Refactor test to remove usage of mockkStatic.

fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt, fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesViewHolder.kt
To test this with actual wallpapers in a debug build, you'll need to create a file `.wallpaper_url` file in the top-level of Fenix, and it should include the URL of the server as contents:
https://assets.mozilla.net/mobile-wallpapers/android …
=> Bug 1837509 - Compose Top Sites should work with wallpapers

android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt, android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt, android-components/components/support/utils/src/main/java/mozilla/components/support/utils/Browsers.kt, android-components/components/support/utils/src/test/java/mozilla/components/support/utils/BrowsersTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1833960
=> Bug 1833960 - Use Browsers Cache utility in App Links

fenix/app/src/main/java/org/mozilla/fenix/compose/TabThumbnail.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/ThumbnailImage.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/list/ListItem.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabListItem.kt, fenix/app/src/main/java/org/mozilla/fenix/home/recenttabs/view/RecentTabs.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/inactivetabs/InactiveTabs.kt
Thumbnail bitmaps were seemingly fetched, retained, and re-fetched. They were garbage collected when the Tabs Tray was dismissed, but violently scrolling up and down would explode the in-app memory.
- My solution for this was to add a bitmap recycle call to `ThumbnailImage` in a `DisposableEffect` block.
Relying on the `Favicon` Composable when the icon was available via `TabsessionState.content.icon` was causing unnecessary icon fetches inside `TabGridItem` AND `ThumbnailCard`. 
- I ended up needing to differentiate use cases for the original `ThumbnailCard`; one via Recent Synced Tabs (where `TabSessionState` isn't available) and one where `TabSessionState` is the driving data object. `TabThumbnail` is driven via `TabSessionState` so that the passed-in bitmap of `tab.content.icon` can …
=> Bug 1815579 - Improve performance of image loading in tab items

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1807289
=> Bug 1807289 - Disable failing customTabDownloadTest UI test

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt
Performance seems to be similar with composed tabs tray disabled, tested on 2 devices with 40+ private, normal and synced tabs. This makes sense, considering we did the same in the XML version.
https://github.com/mozilla-mobile/firefox-android/assets/35462038/1881ce71-b597-403e-828f-a010b891fa82
5. The APK links …
=> Bug 1837417 - Remember synced tabs collapsed/expanded state in composed tabs tray

docs/changelog.md, fenix/app/metrics.yaml, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt, fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt, fenix/app/src/main/java/org/mozilla/fenix/share/PrintItem.kt, fenix/app/src/main/java/org/mozilla/fenix/share/SaveToPDFInteractor.kt, fenix/app/src/main/java/org/mozilla/fenix/share/SaveToPDFMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/share/ShareController.kt, fenix/app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/share/ShareInteractor.kt, fenix/app/src/main/res/drawable/ic_print.xml, fenix/app/src/main/res/layout/fragment_share.xml, fenix/app/src/main/res/values/strings.xml, fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/share/ShareControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/share/ShareInteractorTest.kt
This bug adds a print button on the main Fenix toolbar menu and a print button on the share menu.
This bug adds a main toolbar extra telemetry of
print_content. Additional telemetry and Nimbus instrumentation will be added in bug 1837517. …
=> Bug 1836780 - Add UI For Printing Page Content

android-components/.buildconfig.yml, android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt, android-components/components/feature/prompts/build.gradle, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptContainer.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/dialog/PromptDialogFragment.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/identitycredential/PrivacyPolicyDialogFragment.kt, android-components/components/feature/prompts/src/main/res/values/strings.xml, android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptContainerTest.kt, android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt, android-components/samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonPopupBaseFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1836360
=> Bug 1836360 - Add a dialog for handling FedCM showPolicyPrompt.

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PDFViewerTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1840061
=> Bug 1840061 - Adds PDF viewer - Open in app button UI tests

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt, fenix/app/src/test/java/org/mozilla/fenix/home/DefaultSessionControlControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/HomeFragmentTest.kt
This patch aims to reimplement the previous behavior upon removing a pinned top site when a snackbar was shown giving the option to undo the removal.
https://github.com/mozilla-mobile/firefox-android/assets/32488956/fab2d4b5-15e2-4b68-acb3-012a32fef67c
5. The APK links should be on the right side of the screen, named …
=> Bug 1837504 - Display undo snackbar when compose top site is removed

fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1815421
=> Bug 1815421 - Clear button should be active only when username input is not empty.

fenix/app/src/main/java/org/mozilla/fenix/compose/ThumbnailImage.kt
Using `rememberSaveable` with a bitmap is causing crashes on certain combinations of Android devices and OS versions, since bitmaps are not serializable. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1840896
=> Bug 1840896 - Remove `rememberSaveable` since bitmaps are not serializable

fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/BottomSheetHandle.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeature.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckViewModel.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContent.kt, fenix/app/src/main/res/navigation/nav_graph.xml, fenix/app/src/main/res/values/static_strings.xml
– Add bottom sheet fragment 
– Add compose content with a basic header
– Create `BottomSheetHandle` common UI component
– Add `ViewModel` so parent fragment can observe the bottom sheet visibility state and update the `ToggleButton` selection. …
=> Bug 1840099 - Add bottom sheet container for shopping experience

android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt, android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt, android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1836971
=> Bug 1836971 - Respect never setting in open links in apps

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
Follow up to [2615](https://github.com/mozilla-mobile/firefox-android/pull/2615).
https://bugzilla.mozilla.org/show_bug.cgi?id=1840315
=> Bug 1840315 – added telemetry to the splash screen data fetching

android-components/components/feature/prompts/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1836360
=> Bug 1836360 - Remove trailing space from mozac_feature_prompts_identity_credentials_privacy_policy_description.

fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
"Add to shortcuts" menu entry should be hidden if Shortcuts are disabled on the HomepageScreens need refactor.
- ShortScreen
- HomeScreen
[fnx-54-issue.webm](https://user-images.githubusercontent.com/20729878/216297805-d9dd8d94-c534-4c8e-a5bd-aa13189e9652.webm)
[fnx-54-fixed.webm](https://user-images.githubusercontent.com/20729878/216386701-74f89fb2-517a-442e-ba3a-8637cbc4a2a6.webm)
Pull Request checklist
**QA**
---
This code was written and reviewed by GitStart Community. Growing great engineers, one PR at a time.
**GitHub Automation**
Fixes https://bugzilla.mozilla.org/show_bug.cgi?id=1813787
https://bugzilla.mozilla.org/show_bug.cgi?id=1813787
https://bugzilla.mozilla.org/show_bug.cgi?id=1813787
https://bugzilla.mozilla.org/show_bug.cgi?id=1813787 …
=> Bug 1813787 - Hide `Add to shortcuts` menu entry if Shortcuts are disabled on the Homepage

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
This PR re-enables `verifyLoginWithoutPasswordCanNotBeSavedTest` and refactors `verifyLoginWithNoUserNameCanNotBeSavedTest`
The changes recently introduces in #906 changed the save login button's behaviour, as it follows:
- The save button is inactive when no changes are made to the login credentials while in edit mode
- The save button is inactive when the user name field is empty in edit mode (we could previously save a login without a user name, and no error message was displayed)
- The save button is inactive when the password field is empty in edit mode
✅ Both tests successfully passed 100x on Firebase.
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address …
=> Bug 1840561 - Fix and refactor verifyLoginWithoutPasswordCanNotBeSavedTest UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeContextMenusTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Added new conditions based on the link types and missing options when verifying link related context menu options.
https://bugzilla.mozilla.org/show_bug.cgi?id=1841073
=> Bug 1841073 - Add missing conditions when verifying link related context menu options in UI tests

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1841153
=> Bug 1841153 - new event telemetry for private tab open

focus-android/app/src/androidTest/java/org/mozilla/focus/activity/ThreeDotMainMenuTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1842719
=> Bug 1842719 - Disables "Report site issue" button check in Focus UI test

android-components/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/ContextMenuFeature.kt, android-components/components/feature/contextmenu/src/main/java/mozilla/components/feature/contextmenu/facts/ContextMenuFacts.kt, android-components/components/feature/downloads/README.md, android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt, android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/facts/DownloadsFacts.kt, android-components/components/feature/prompts/README.md, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/facts/PromptFacts.kt, android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt, fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt, fenix/app/src/main/java/org/mozilla/fenix/android/FenixDialogFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/components/Analytics.kt, fenix/app/src/main/java/org/mozilla/fenix/crashes/CrashFactCollector.kt, fenix/app/src/main/java/org/mozilla/fenix/downloads/StartDownloadDialog.kt, fenix/app/src/main/java/org/mozilla/fenix/share/ShareFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt, fenix/app/src/test/java/org/mozilla/fenix/downloads/StartDownloadDialogTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/recentvisits/view/RecentBookmarksViewHolderTest.kt, fenix/app/src/test/java/org/mozilla/fenix/tabstray/TabsTrayFragmentTest.kt
This patch will add [bread crumbs](https://docs.sentry.io/product/issues/issue-details/breadcrumbs/) that will help us detect the source of the [bug #1839239](https://bugzilla.mozilla.org/show_bug.cgi?id=1839239). …
=> Bug 1839239 - Add crash bread crumbs for dialogs.

taskcluster/ci/startup-test/kind.yml
commit 1b4e16327a05fc75c20be678a96f4210826d6c86 changed build artifact names, and adjusted the fenix startup-test, but missed focus.
https://bugzilla.mozilla.org/show_bug.cgi?id=1843062
=> Bug 1843062 - fix focus startup-test artifact-reference

android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt, android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
Originally we used to try to launch the intent if engine doesn't support the scheme even though no external app is found.  This is not a good behaviour since Android OS already told us nothing on the device support the intent.
Stop trying to redirect to an external app that doesn't exist on the device.
5. The APK …
=> Bug 1835816 - Do not try to redirect intent even if unsupported by engine

taskcluster/android_taskgraph/util/scriptworker.py
I missed this in bug 1831168.
https://bugzilla.mozilla.org/show_bug.cgi?id=1843121
=> Bug 1843121 - fix destination path for focus nightly apks on archive.mozilla.org

android-components/components/feature/webcompat-reporter/src/main/assets/extensions/webcompat-reporter/manifest.json
We accidentally updated the addon but gave it a lower version number. Since we're not sure if that's going to cause any issues, let's bump the version higher.
https://bugzilla.mozilla.org/show_bug.cgi?id=1842886
=> Bug 1842886 - bump the version of the webcompat-reporter addon up

fenix/app/src/main/res/values/strings.xml
This aims to fix the `l10n` PR failing due to lint checks for these strings in particular, by marking them as UnusedResource. As a result, these will be marked as UnusedResource in strings.xml of other locales as well.
We will follow this up with marking strings as deleted that were added for 113 onboarding. [Bug.](https://bugzilla.mozilla.org/show_bug.cgi?id=1843245)
4. Click on `View …
=> Bug 1843243 - Mark nimbus onboarding strings as unused

fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1843245
=> Bug 1843245 - Mark unused onboarding strings for removal

focus-android/app/src/androidTest/java/org/mozilla/focus/activity/ThreeDotMainMenuTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1842719
=> Bug 1842719 - Enable "Report site issue" button check in Focus UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/OnboardingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SponsoredShortcutsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TextSelectionTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
https://github.com/mozilla-mobile/firefox-android/pull/2755 needs to land first so the UI test run here can be green.
https://bugzilla.mozilla.org/show_bug.cgi?id=1842179
=> Bug 1842179 - Enable Unified Search in all UI tests

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1842082
=> Bug 1842082 - Normal home screen view count telemetry

fenix/app/metrics.yaml, fenix/app/src/main/AndroidManifest.xml, fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/home/intent/HomeDeepLinkIntentProcessor.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1843610
=> Bug 1843610 - Add telemetry for deferred deep link test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Bug 1807268 - Disable failing `verifyContextCopyLinkNotDisplayedAfterApplied` UI test
Bug 1840994 - Disable failing systemNotificationCantBeDismissedWhileDownloadingTest UI test …
=> Bug 1807268 - Disable failing verifyContextCopyLinkNotDisplayedAfterApplied UI test

android-components/components/service/nimbus/messaging.fml.yaml, android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt, android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt, fenix/app/.experimenter.yaml
Fixes [Bug 1843546](https://bugzilla.mozilla.org/show_bug.cgi?id=1843546)
Fixes [EXP-3682](https://mozilla-hub.atlassian.net/browse/EXP-3682)
https://bugzilla.mozilla.org/show_bug.cgi?id=1843546
=> Bug 1843546 — Fixup malformed control messages

android-components/components/feature/recentlyclosed/src/main/java/mozilla/components/feature/recentlyclosed/RecentlyClosedTabsStorage.kt, android-components/components/feature/recentlyclosed/src/test/java/mozilla/components/feature/recentlyclosed/RecentlyClosedTabsStorageTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1839250
=> Bug 1839250 - Avoid crash caused by OOM while saving a just-closed tab into storage

android-components/components/support/base/src/main/java/mozilla/components/support/base/android/NotificationsDelegate.kt, android-components/components/support/base/src/test/java/mozilla/components/support/base/android/NotificationsDelegateTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1826933
=> Bug 1826933 - Avoid memory leaks in NotificationsDelegate

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1844580
=> Bug 1844580 - Disable pocket related UI tests

fenix/app/src/main/res/drawable-v23/splash_screen.xml, fenix/app/src/main/res/values-v24/styles.xml, fenix/app/src/main/res/values/styles.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1844386
=> Bug 1844386 - Only use splash screen animation for SDK 31+

fenix/app/metrics.yaml, fenix/app/src/main/AndroidManifest.xml, fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/home/intent/HomeDeepLinkIntentProcessor.kt
=> Bug 1843610 - Add telemetry for deferred deep link test (backport #2851)

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
Bug 1844312 - Remove `verifyOpenLinkInAppViewInPrivateBrowsingTest` UI test
Summary:
While reviewing the toDoAutomation notes from TestRail, I've noticed that the steps from this steps are actually repeated in both `privateBrowsingNeverOpenLinkInAppTest` and `privateBrowsingAskBeforeOpeningLinkInAppTest`.
5. The APK …
=> Bug 1844312 - Remove verifyOpenLinkInAppViewInPrivateBrowsingTest UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHomepageTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Bug 1844330 - Add missing steps to `verifyShortcutOptionTest` UI test
Summary:
Based on the toDoAutomation notes from TestRail, the  "Add to shortcuts" option shouldn't be displayed in the main menu if "Shortcuts" homepage setting is disabled. …
=> Bug 1844330 - Add missing steps to verifyShortcutOptionTest UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeCollectionTest.kt
Bug 1844305 - Add snackbar verification in UI tests when removing tabs from a collection
Summary:
Based on the toDoAutomation notes from TestRail I've added tab removal snackbar verification steps where needed and also created a new one .
The tests successfully passed 100x on Firebase ✅ 
5. The APK links should be on …
=> Bug 1844305 - Add snackbar verification in UI tests when removing tabs from a collection

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Bug 1840994 - Fix `systemNotificationCantBeDismissedWhileDownloadingTest` UI test
Summary:
In some cases the download of the file was completed before performing the swipe right action on the download notification causing inconsistencies.
To overcome this problem, I've removed the swipe right action, relying only on the swipe left action to check that the notification isn't dismissed while the download is in progress.
The test successfully passed 100x on Firebase ✅ 
2. Click on the `firefoxci-taskcluster` group on the left to expand all …
=> Bug 1840994 - Fix systemNotificationCantBeDismissedWhileDownloadingTest UI test

android-components/components/ui/icons/src/main/res/drawable/mozac_ic_chevron_down_20.xml, android-components/components/ui/icons/src/main/res/drawable/mozac_ic_chevron_up_20.xml, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckCards.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContent.kt, fenix/app/src/main/res/values/static_strings.xml
– Create common `ReviewQualityCheckCard` and `ReviewQualityCheckExpandableCard` components that will be used to display various cards.
– Create `ReviewGradeCard` and display in the content with static data. …
=> Bug 1840332 - Add ReviewGradeCard

fenix/app/src/main/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckAction.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckPreferences.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckPreferencesMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckStore.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/test/java/org/mozilla/fenix/shopping/state/ReviewQualityCheckStoreTest.kt
– Add preferences in `Settings.kt`
– Create `ReviewQualityCheckPreferences` as an abstraction to get/update preferences.
– Define store actions based on their property, whether they are handled by a middleware or cause an update to the state.
– Create `PreferencesMiddleware` that uses `ReviewQualityCheckPreferences` …
=> Bug 1843029 - Add preferences for shopping experience

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/FirstSessionPing.kt
There was some questions related to Adjust attribution time.  This is to use a timespan telemetry to confirm the data that we have from the time distribution telemetry.
https://bugzilla.mozilla.org/show_bug.cgi?id=1823492
=> Bug 1823492 - Add timespan metric for Adjust attribution

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SyncSignInRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt
Bug 1845307 - New `verifySyncedTabsWhenUserIsNotSignedInTest` UI test
1. Created 2 new UI test ✅ successfully passed 100x on Firebase
2. While trying to create the UI test that uses the refactored tabs tray, noticed that the [verifySyncedTabsList](https://github.com/mozilla-mobile/firefox-android/pull/2984/files#diff-d35ffbcbe6efc7f36d175346b6dc94963663e0c3b3c36764a12795e273658b95R85) function didn't work
After taking a closer look how the tests tags are actually used, noticed that the synced tabs list composable didn't have 
any testTag (compared it against the other tab lists)
Asked @Alexandru2909 if that could cause the problems, added the missing `testTag` and afterwards the 
synced tabs list verification worked properly.
@MozillaNoah I would kindly ask you to review that change ☺️ 
- …
=> Bug 1845307 - New verifySyncedTabsWhenUserIsNotSignedInTest UI test

fenix/app/build.gradle, fenix/plugins/apksize/build.gradle, fenix/plugins/apksize/settings.gradle, fenix/plugins/apksize/src/main/java/ApkSizePlugin.kt, fenix/settings.gradle
https://bugzilla.mozilla.org/show_bug.cgi?id=1845354
=> Bug 1845354 - Refactor ApkSizeTask into a plugin using composite build

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt
Based on the recent changes made in TestRail, some PWA related tests were removed from our smoke and sanity tests suite (as there will be no more development done on this feature).
We'll need to remove the `@ SmokeTest` annotation from the corresponding automated UI tests.
5. The APK links should be on the right side …
=> Bug 1845520 - Remove smoke test annotation from pwa related UI tests

android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt, android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1845104
=> Bug 1845104 - Open links in the current app from a CustomTab even when OpenInApp settings is set to 'never'

fenix/app/src/test/java/org/mozilla/fenix/shortcut/PwaOnboardingObserverTest.kt
This allows mocking navigateToPwaOnboarding method and avoids ClassCastException when this method is called.
https://bugzilla.mozilla.org/show_bug.cgi?id=1845677
=> Bug 1845677 - Correctly mock pwaOnboardingObserver in PwaOnboardingObserverTest

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1845644
https://bugzilla.mozilla.org/show_bug.cgi?id=1845644
=> Bug 1845644 - Update Sentry to version 6.27.0

fenix/gradle.properties
According to https://github.com/gradle/gradle/issues/19750 setting the org.gradle.jvmargs property can lead to "Daemon disappeared" failures by removing the default values.
Also use -XX:+UseParallelGC to improve build performance. …
=> Bug 1845098 - Improve Fenix Gradle builds.

taskcluster/ci/ui-test-apk/kind.yml
Reverts mozilla-mobile/firefox-android#3046
https://bugzilla.mozilla.org/show_bug.cgi?id=1807307
https://bugzilla.mozilla.org/show_bug.cgi?id=1807307
=> Revert "Bug 1807307 - Re-land disabling LeakCanary in CI fuzzy testing builds"

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
=> Bug 1807268 - Disable failing verifyBasicNavigationToolbarFunctionality UI tests

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt, fenix/app/build.gradle, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductReviewLoading.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
Same as #3068 along with the compose animation dependency
https://bugzilla.mozilla.org/show_bug.cgi?id=1845255
=> Bug 1845255 - Add loading UI for review quality check

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionException.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoWebExtensionExceptionTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt
This is going to fail a bit until the patch for https://bugzilla.mozilla.org/show_bug.cgi?id=1845745 lands... …
=> Bug 1845820 - Add the `WebExtensionInstallException.Blocklisted` class

android-components/components/feature/addons/src/main/res/values/strings.xml, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt, fenix/app/src/test/java/org/mozilla/fenix/addons/AddonsManagementFragmentTest.kt
~~:warning: Depends on https://github.com/mozilla-mobile/firefox-android/pull/3015~~
---
As anticipated on Slack, I am stuck on the testing part... …
=> Bug 1845823 - Display a better error message when a user installs a blocklisted add-on

fenix/app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1846773
=> Bug 1846773 - Set adjust preinstall file path in system properties

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1840994
https://bugzilla.mozilla.org/show_bug.cgi?id=1840994
=> Bug 1840994 - Disable systemNotificationCantBeDismissedWhileDownloadingTest

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
Bug 1846529 - New UI tests that verify the PB state after closing the app
All 4 UI tests successfully pass 100x on Firebase ✅ 
https://bugzilla.mozilla.org/show_bug.cgi?id=1846529
=> Bug 1846529 - New UI tests that verify the PB state after closing the app

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/EnhancedTrackingProtectionRobot.kt
Bug 1845944 - New custom tabs ETP settings UI test
✅ Successfully passed 100x on Firebase.
https://bugzilla.mozilla.org/show_bug.cgi?id=1845944
=> Bug 1845944 - New custom tabs ETP settings UI test

android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt, android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt, android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
This reverts commit 3fe4af368dab87c685140a56632a2b9b837141da.
=> Revert "Bug 1836971 - Respect never setting in open links in apps"

fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt, fenix/app/src/main/res/values/static_strings.xml, fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStateTest.kt
– Add composable UI
~– Add `highlightsForCompactMode` property that contains the first two highlights of the first highlight type to display in the highlights card in compact state.~
– Add `highlights.forCompactMode()` extension function that returns the first two highlights of the first highlight type to display in the highlights card in compact state.
4. Click on `View task in …
=> Bug 1840339 - Add review highlights card for shopping experience

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
…llection is deleted
https://bugzilla.mozilla.org/show_bug.cgi?id=1845900
=> Bug 1845900 -  deleting the last element of a collection, the entire collection is deleted

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Bug 1847211 - New unified search tab UI tests
All 6 UI tests successfully passed 100x on Firebase ✅ 
https://bugzilla.mozilla.org/show_bug.cgi?id=1847211
=> Bug 1847211 - New unified search tab UI tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeBookmarksTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHistoryTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
Made verifyFirefoxSuggestResults  and verifySearchEngineSuggestionResults only one method as they were practically the same.
Added new tests based on TestRail manual tests.
Fixed defaultSearchCodeGoogleUS failing on the PR, for un-related reasons.
Ran 100x on Firebase, and all passed.
Discussed with Aaron how to handle code duplication in old and new Composed test classes, we've made a decision to freeze the old UI classes (to be deprecated in the future) and only add to the new Compose test classes.
2. Click on the `firefoxci-taskcluster` …
=> Bug 1847583 - Fenix: Add search by bookmarks tests

fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt, fenix/app/src/test/java/org/mozilla/fenix/extension/WebExtensionPromptFeatureTest.kt
=> Bug 1847179 - Fix wrong error message displayed when trying to install an unsupported add-on

fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
:warning: Depends on https://bugzilla.mozilla.org/show_bug.cgi?id=1847173
- ~~[ ] **Tests**: This PR includes thorough tests or an explanation of why it does not~~
1. Click on `Checks` at the top …
=> Bug 1847186 - Enable the `mozAddonManager` web API on Fenix Nightly builds

docs/shared/uplift_guide.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1833666
=> Bug 1833666 - Remove extra bracket from uplift video link

fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
This test has failed a few times ([example tc task](https://firefox-ci-tc.services.mozilla.com/tasks/PyYeYU1GSLazqIcQyAFP1w#artifacts)) on the CI ([for an unrelated PR](https://github.com/mozilla-mobile/firefox-android/pull/3140)) and I've been unable to reporoduce the failure locally. Removing this so we don't block the CI. 
If anyone has some ideas on how to better test this, please let me know. …
=> Bug 1846229 - Ignore flaky test in ReviewQualityCheckStoreTest

android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt, android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt, android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt, android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1843895
=> Bug 1843895 - Update AppLinksUseCases launchInApp when updating the interceptor

fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt, fenix/app/src/test/java/org/mozilla/fenix/extension/WebExtensionPromptFeatureTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1847956
=> Bug 1847956 - Show snackBars on top of the toolbar.

android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonsProvider.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AMOAddonsProvider.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragment.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt, docs/changelog.md
~~:warning: Depends on https://github.com/mozilla-mobile/firefox-android/pull/3154~~
- ~~[ ] **Tests**: This PR includes thorough tests or an explanation of why it does not~~
3. Click on the `build-apk-{fenix,focus,klar}-debug` …
=> Bug 1847906 - Add `getAddonIconBitmap()` to the `AddonsProvider` interface

fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt, fenix/app/src/main/res/drawable/mozac_ic_extensions_black.xml, fenix/app/src/main/res/layout/fragment_add_ons_management.xml, fenix/app/src/main/res/layout/overlay_add_on_progress.xml, fenix/app/src/test/java/org/mozilla/fenix/addons/AddonsManagementFragmentTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1845323
=> Bug 1845323 - Bring back the downloading add-on dialog.

fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStateTest.kt
This is a minor state update to more accurately reflect the nullability and present of some of the properties. More details in the bug.
https://bugzilla.mozilla.org/show_bug.cgi?id=1847922
=> Bug 1847922 - Update ReviewQualityCheckState for analysis present and not

fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/Pipfile, fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/Pipfile.lock, fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/SurveyExperimentIntegrationTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/conftest.py, fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/gradlewbuild.py, fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/launchSimScript.sh, fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/pytest.ini, fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/test_integration.py, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAboutRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuExperimentsRobot.kt, fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml, fenix/automation/taskcluster/androidTest/flank-arm64-v8a.yml, fenix/automation/taskcluster/androidTest/flank-x86.yml
Works on https://mozilla-hub.atlassian.net/browse/EXP-3252
This config is very similar to the Sync Integration Tests that already exist in this repo.
- [✅] **Quality**: This PR builds and passes detekt/ktlint checks (A pre-push hook is recommended)
- [✅] **Tests**: This PR includes thorough tests or an explanation of why it does not
- [✅] **Accessibility**: The code in this PR follows [accessibility best practices](https://github.com/mozilla-mobile/firefox-android/blob/main/docs/shared/android/accessibility_guide.md) or does not include any user facing features
1. Click on `Checks` at the …
=> Bug 1848191 - Add experimenter UI integration testing framework 

fenix/app/src/main/java/org/mozilla/fenix/share/PrintItem.kt, fenix/app/src/main/java/org/mozilla/fenix/share/SaveToPDFItem.kt
The content description was incorrectly set on the print and save to PDF icon as "close". The content description should be null because the elements are decorative and are a part of a compose button. …
=> Bug 1847746 - Content Description on Print and Save to PDF

fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
Changing the default for the feature while we work on fixing some of the known glaring bugs that users are facing.
This does not change the option for users that have toggled this value at any point, this is only for users that are currently using the default. …
=> Bug 1847282 - Change the default for pull-to-refresh to disabled

fenix/app/src/test/java/org/mozilla/fenix/library/history/state/HistoryStorageMiddlewareTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1848436
=> Bug 1848436 - Temporarily disable failing test in HistoryStorageMiddlewareTest

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextualHintsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
For more information please see this [document](https://docs.google.com/document/d/1k4xjEtbWThvBNflIq6_0MtLIWaMK9Rjy7s-R2g2xMcM/edit) …
=> Bug 1848142 - Homescreen TestRail matching

fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckServiceImplTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
More details in the bug. 
– Add `ReviewQualityCheckNetworkMiddleware` that handles network related actions. It delegates to `ReviewQualityCheckService` to fetch the product analysis and then maps to UI State, then dispatches an update action on the store.
– Remove fake data in `ReviewQualityCheckState` as the data is now coming from the network.
4. Click on `View task in Taskcluster` …
=> Bug 1847923 - Part 2: Add network middleware for review quality check

fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeature.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ShoppingExperienceFeature.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/static_strings.xml, fenix/app/src/main/res/xml/secret_settings_preferences.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1848377
=> Bug 1848377 - Add secret setting to control the visibility of the Shopping feature

fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/ext/NavController.kt, fenix/app/src/main/java/org/mozilla/fenix/nimbus/controller/NimbusBranchesController.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/controller/OnboardingController.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/HomeSettingsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/account/TurnOnSyncFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/SavedLoginsAuthFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/sitepermissions/SitePermissionsFragment.kt, fenix/app/src/test/java/org/mozilla/fenix/onboarding/DefaultOnboardingControllerTest.kt
Tried to add as many scenarios from [crash-stats](https://crash-stats.mozilla.org/signature/?signature=java.lang.IllegalArgumentException%3A%20at%20androidx.navigation.NavController.navigate%28NavController.kt%3A23%29&date=%3E%3D2023-08-05T01%3A03%3A00.000Z&date=%3C2023-08-12T01%3A03%3A00.000Z&_columns=date&_columns=product&_columns=version&_columns=build_id&_columns=platform&_columns=reason&_columns=address&_columns=install_time&_columns=startup_crash&_sort=-date&page=1#reports) (Until page 2). 
2. Click on the `firefoxci-taskcluster` group …
=> Bug 1842039 - Add bread crumbs for IllegalArgumentException when navigating

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt
=> Bug 1807268 - Disable openAllInTabsTest UI test

taskcluster/ci/external-gradle-dependencies/kind.yml
The typical run time is under 25 minutes nowadays (unless it's hanging), so even with some wiggle room there's no need to go anywhere near 4h anymore.
https://bugzilla.mozilla.org/show_bug.cgi?id=1845098
=> Bug 1845098 - reduce external-gradle-dependencies max-run-time from 4h to 40min

taskcluster/scripts/toolchain/external-gradle-dependencies.sh
https://bugzilla.mozilla.org/show_bug.cgi?id=1845098
=> Bug 1845098 - give java more heap space for external-gradle-dependencies job

android-components/components/lib/dataprotect/src/main/java/mozilla/components/lib/dataprotect/Keystore.kt
This is not catching the failure at a low enough call.  The next call fails with the same error.  Reverting this fix for a better one.
Reverts mozilla-mobile/firefox-android#3294
https://bugzilla.mozilla.org/show_bug.cgi?id=1842596
https://bugzilla.mozilla.org/show_bug.cgi?id=1842596
=> Revert "Bug 1842596 - Recover from UnrecoverableKeyException when retrieving sync key"

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
This started permafailing tonight due to what appears to be a change on the YouTube end. Ignore the test for now.
https://bugzilla.mozilla.org/show_bug.cgi?id=1849278
=> Bug 1849278 - Ignore mainMenuOpenInAppTest failures

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
Bug 1849146 - Add tab and history search smoke tests
Summary:
Adding 2 UI test to our smoke test suite.
Because the composable tabs tray is only enabled on Nightly and Debug:
- I've moved the `verifySearchHistoryWithBrowsingDataTest` from `ComposeSearchTest` class to `SearchTest` class because it doesn't interact in any way with the tabs tray
- Added `verifySearchTabsWithOpenTabsTest` to the `SearchTest` class and will run only on Beta and RC builds. (We ignore the Compose* test classes when running the smoke test suite) …
=> Bug 1849146 - Add tab and history search smoke tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSearchRobot.kt, fenix/app/src/main/res/values/strings.xml, fenix/app/src/main/res/xml/search_settings_preferences.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1849085
=> Bug 1849085 - Add localization for the "Search engines" setting preference header

fenix/app/src/androidTest/java/org/mozilla/fenix/syncintegration/SyncIntegrationTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeContextMenusTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeNavigationToolbarTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextualHintsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PwaTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsGeneralTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHomepageTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt
There are a few too many Smoke tests in TestRail to be done in one day by manual testing, in case a quick check is required. 
I reviewed them and kept what is still relevant, and also removed some that have dropped in severity or priority over time.
It can ride the train on 118, then it will need to be uplifted to the release branch too.
4. Click on `View task in Taskcluster` in the …
=> Bug 1849599 - Reorganize the Smoke tests suite

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/WebControlsTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1845098
https://bugzilla.mozilla.org/show_bug.cgi?id=1846773
https://bugzilla.mozilla.org/show_bug.cgi?id=1830348
https://bugzilla.mozilla.org/show_bug.cgi?id=1836971 …
=> Bug 1849278 - Fix external links breaking tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt
Just a small leftover from #3360
Will need to remove the remaining `@ SmokeTest` annotations from `verifyContextOpenLinkPrivateTab` and `verifyContextOpenLinkNewTab`
https://bugzilla.mozilla.org/show_bug.cgi?id=1849978
=> Bug 1849978 - Remove smoke test annotation from context menu related UI tests

fenix/app/src/main/res/values/strings.xml
Strings for the extension process crash dialog which will be added in another PR. These strings will be shown to a user to notify them that their extensions are no longer working. …
=> Bug 1846979 - Add extensions process crash dialog strings

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
Recently started failing in https://github.com/mozilla-mobile/firefox-android/runs/16242371194 and in https://github.com/mozilla-mobile/firefox-android/runs/16249951484
https://bugzilla.mozilla.org/show_bug.cgi?id=1813521
https://bugzilla.mozilla.org/show_bug.cgi?id=1813521
https://bugzilla.mozilla.org/show_bug.cgi?id=1813521
=> Bug 1813521 - Disable DownloadTest.pauseResumeCancelDownloadTest

fenix/app/src/main/java/org/mozilla/fenix/collections/CollectionCreationView.kt, fenix/app/src/main/java/org/mozilla/fenix/collections/CollectionsDialog.kt
The PR will disable the dialog `OK` button and keyboard `DONE` button if the collection name is `blank`
1. Open a tab with a web page open
2. Click on `three dot menu`
3. Select `Save to collection`
4. Delete the default name
5. Try saving by clicking on the keyboard `Done` button
6. Repeat steps `1 - 3`  
7. Enter a name with spaces at the beginning and end 
1. Make sure you have more than 1 tab open with a web page open
2. Click on the tab tray
3. Click on `three dot menu`
4. Click on `Select tabs`
5. Select one or more tabs
6. Click on `Collection button`
7. Click on ~Add new collection`
8. Delete the name and try saving or
9. Append and prepend spaces on the name 
| Issue video | Fix Video |
| ----------- | --------- |
| https://www.loom.com/share/6880e832f260420ab3a26a5a88045420 | …
=> Bug 1812730 - Prevent collections with empty name from being created

fenix/docs/substituting-local-gv.md
We do not need to patch the build system to read the GeckoView version anymore.
https://bugzilla.mozilla.org/show_bug.cgi?id=1849329
=> Bug 1849329 - Update local GV docs

fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
- ~~[ ] **Tests**: This PR includes thorough tests or an explanation of why it does not~~
2. Click on the `firefoxci-taskcluster` group on the left …
=> Bug 1850673 - Enable the `mozAddonManager` web API on Fenix Beta builds

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1850623
=> Bug 1850623 - Register tab/action handlers when an extension has been installed.

android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/PermissionsDialogFragment.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/PermissionsDialogFragmentTest.kt
In order to try this patch, I manually edited the `Addon` class as follows:
```diff
diff --git a/android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt b/android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
index 3ead293ba2..ffa6793c93 100644
--- a/android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
+++ b/android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt
@@ -239,13 +239,13 @@ data class Addon(
fun newFromWebExtension(extension: WebExtension, installedState: InstalledState? = null): Addon {
val name = extension.getMetadata()?.name ?: extension.id
val description = …
```
=> Bug 1847756 - Adjust permissions dialog when there is no permission

android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchEngineSuggestionProvider.kt, android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SearchEngineSuggestionProviderTest.kt, docs/changelog.md
Old | New
--- | --- 
https://bugzilla.mozilla.org/show_bug.cgi?id=1851012
=> Bug 1851012 – aligned Search Engine Suggestion Provider behaviour with Desktop

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataTest.kt
=> Bug 1807268 - Disable failing deleteCachedFilesTest UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSitePermissionsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt
Disable the tests if a real cause cannot be found in the [latest GV](https://github.com/mozilla-mobile/firefox-android/pull/3505) update.
https://bugzilla.mozilla.org/show_bug.cgi?id=1815395
=> Bug 1815395 - Disable failing audio-video permissions UI tests

android-components/components/feature/downloads/src/main/AndroidManifest.xml, android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt, docs/changelog.md, fenix/app/src/main/AndroidManifest.xml, focus-android/app/src/main/AndroidManifest.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1847141
=> Bug 1847141 - Remove hardcoding of RECEIVE_DOWNLOAD_BROADCAST_PERMISSION

fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt, fenix/app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1851006
=> Bug 1851006 - SearchEngineSuggestionProvider should always be added to the provider list.

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1851419
=> Bug 1851419 - Disable searchHistoryNotRememberedInPrivateBrowsingTest UI test

docs/changelog.md, taskcluster/android_taskgraph/loader/build_config.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1825116
=> Bug 1825116 - fix a couple of typos

fenix/app/src/beta/res/drawable/animated_splash_screen.xml, fenix/app/src/debug/res/drawable/animated_splash_screen.xml, fenix/app/src/main/res/drawable/animated_splash_screen.xml, fenix/app/src/nightly/res/drawable/animated_splash_screen.xml, fenix/app/src/release/res/drawable/animated_splash_screen.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1825116
=> Bug 1825116 - add license info to animated_splash_screen.xml

android-components/components/service/sync-logins/src/main/java/mozilla/components/service/sync/logins/SyncableLoginsStorage.kt, docs/changelog.md
Removes the calls to SQLCipher migration. We should do this first before actually removing it from a-s to prevent any breaking changes needed.
a-s tracking issue: https://github.com/mozilla/application-services/issues/5777
a-s tracking epic: https://mozilla-hub.atlassian.net/browse/SYNC-3838
5. The APK links should be …
=> Bug 1849031 - Remove SQLCipher migration calls

fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1845020
=> Bug 1845020 - The hint for search suggestions in private mode should be disabled if search suggestions in normal browsing are disabled.

fenix/app/src/main/java/org/mozilla/fenix/addons/ExtensionProcessDisabledController.kt, fenix/app/src/test/java/org/mozilla/fenix/addons/ExtensionProcessDisabledControllerTest.kt
The root cause of the issue is the `import androidx.appcompat.app.AlertDialog` vs `import android.app.AlertDialog`, where `androidx` version is picking the right them while the `android.app`is not, we will follow up by adding a lint check to avoid possible future issues, we will follow up on [bug #1852992](https://bugzilla.mozilla.org/show_bug.cgi?id=1852992).
4. Click on `View task in …
=> Bug 1852984 - Show the right theme for the extensions process crash dialog

fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckSettingsCard.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityInfoCard.kt
TLDR: The changes in this PR
- Made a `ProductAnalysisError` Composable to serve as the container for the error state UI to mirror `ProductAnalysis`.
- Refactored the review grade info UI to its own file.
- Added the review grade info to `ProductAnalysisError` …
=> Bug 1852305 - Add review grade info to all error states

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTopSitesTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTopSitesRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt, fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt, fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt, fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesTestTag.kt
Since the old UI tests don't work for the new Compose Top Sites elements, new tests have been created.
https://bugzilla.mozilla.org/show_bug.cgi?id=1845039
=> Bug 1845039 - Create new UI Tests for Compose Top Sites

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1853270
=> Bug 1853270 - Add LoadUrlFlag flag to allow additional headers

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt
For more information please see this [document](https://docs.google.com/document/d/1i9kftL_BiL3Lw-wrkCEi78T9ikp0H0B0vrKO2Zr4IyY/edit?usp=sharing) …
=> Bug 1853654 - Advanced settings TestRail matching

android-components/components/lib/crash-sentry/src/main/java/mozilla/components/lib/crash/sentry/SentryService.kt, docs/changelog.md, fenix/app/src/main/java/org/mozilla/fenix/components/Analytics.kt, fenix/app/src/main/java/org/mozilla/fenix/components/Components.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1851676
=> Bug 1851676 - Adds ability to initialize Sentry on startup

android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterDelegate.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/CustomViewHolder.kt, android-components/components/feature/addons/src/main/res/layout/mozac_feature_addons_footer_section_item.xml, android-components/components/feature/addons/src/main/res/values/strings.xml, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementView.kt, fenix/app/src/test/java/org/mozilla/fenix/addons/AddonsManagementViewTest.kt
=> Bug 1850783 - Add button to open AMO from the fenix add-on manager

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt, fenix/app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1853967
=> Bug 1853967 - Capture telemetry for the amount of RAM a device has.

fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt, fenix/app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1852802
=> Bug 1852802 - Prevents search suggestion prompt in private mode when felt privacy is enabled

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTopSitesTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTopSitesRobot.kt
Bug 1853626 - Fix flaky `verifyRenameTopSite` UI test
Summary:
- The `IllegalStateException` was caused by the fact the rules were not ordered. (Compose and RetryTestRule)
- Ordered the rules but afterwards noticed that the RetryTestRule wasn't actually helping that much, there are 9 UI tests in both test classes, and in 7 of them we add the website as a home screen shortcut using the "Add to shortcuts" button.
On retry, we already have that website added as a shortcut, meaning that "Add to shortcuts" button will be replaced with the "Remove from shortcuts" button causing failures.
- Finally, had to make some changes to `renameTopSite` (setting the new shortcut name and click the "OK" button)
The UI test successfully passed 100x on Firebase ✅ 
- **Breaking Changes**: If this is a breaking …
=> Bug 1853626 - Fix flaky verifyRenameTopSite UI test

fenix/app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt, fenix/app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1848562
=> Bug 1848562 - Autocomplete for bookmarked website should appear when 'search browsing history' is disabled.

fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt, fenix/app/src/main/res/values/strings.xml, fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStateTest.kt
– Use the error types to display error [cards](https://www.figma.com/file/VE5xayz3yOSB5qOATUU9Im/Mobile-Shopping-Experience-MVP?type=design&node-id=2678-62307&mode=design&t=qIXMuZllp8FQINlt-0 :
1. "No network connection" when error is `NetworkError`
2. "We can't check these reviews" when error is `UnsupportedProductTypeError`
3. "No info available at this time"  when error is `GenericError`
– Display "Not enough reviews" when `productAnalysis.notEnoughReviewsCardVisible` is true.
~– Display analysis completed card when when `analysisStatus` is `AnalysisStatus.COMPLETED`~
~– Add `AnalysisCompleteConfirmation` action, when triggered, updates the `analysisState` from `COMPLETED` to `UP_TO_DATE`, dismissing the card when user clicks the confirmation button.~
[Figma for all the …
=> Bug 1840113 - Display review checker info cards

fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml, fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
Currently the `blueline` is either backed up or moved to low capacity on Test Lab and is timing out Tasks exceeding the `7200` second timeout.
Opened a thread on Firebase Community. In the mean-time, temporarily remove.
https://bugzilla.mozilla.org/show_bug.cgi?id=1854429
=> Bug 1854429 - Temporarily remove Pixel3 for low capacity

android-components/components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt
=> Bug 1853065 - Fix TabsUseCasesTest merge conflict

fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSites.kt, fenix/app/src/main/java/org/mozilla/fenix/home/topsites/TopSitesViewHolder.kt, fenix/app/src/main/java/org/mozilla/fenix/perf/StartupReportFullyDrawn.kt, fenix/app/src/main/java/org/mozilla/fenix/perf/StartupTimeline.kt
Because we are migrating Top Sites to Compose, we want to ensure we are still recording when top sites are loaded, therefore the call for StartupTimeline is now called after creating the top sites compose elements. Calling it here will ensure it will be called even after we replace the home page recycler with a Compose view.
4. Click on `View task in Taskcluster` in the new `DETAILS` …
=> Bug 1837526 - Call StartupTimeline in the Compose Top Sites

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeBookmarksTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
For more information please see this [document](https://docs.google.com/document/d/1lRN75vjmqFHqT4aG21JPSriQbUSahCxJplWSi2ec-lw/edit?usp=sharing)
Deleted the following UI tests that don't have any coresponding manual test in TestRail:
- `verifyBookmarkButtonTest` 
- `addBookmarkTest`
- `multipleBookmarkDeletionsTest`
- `verifyCloseMenuTest`  …
=> Bug 1854354 - Bookmarks TestRail matching

fenix/app/.experimenter.yaml, fenix/app/onboarding.fml.yaml, fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1848188
=> Bug 1848188 - Remove Nimbus flag for Juno Onboarding

fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/test/java/org/mozilla/fenix/FenixApplicationTest.kt, fenix/app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
It looks like on https://github.com/mozilla-mobile/firefox-android/commit/f2134f7b79ab12e7c49686c3922fd95d5acf5355 we changed the type of `pref_key_search_widget_installed` without changing the pref key, that caused a mismatch between types which resulted in to `ClassCastException`. 
I was able to replicate the issue locally by installing Fenix with a commit before https://github.com/mozilla-mobile/firefox-android/commit/f2134f7b79ab12e7c49686c3922fd95d5acf5355 (maybe this one https://github.com/mozilla-mobile/firefox-android/commit/b44fb318d54b998672aaecff3fff01e54e6a9066) , and adding the **"Search the web"** Fenix's widget.
Then switching to https://github.com/mozilla-mobile/firefox-android/commit/f2134f7b79ab12e7c49686c3922fd95d5acf5355 which it's the commit which introduced the …
=> Bug 1854739 - Migrate pref_key_search_widget_installed

fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/test/java/org/mozilla/fenix/utils/SettingsTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1854739
=> Bug 1854739 - Catch crash when migrating pref_key_search_widget_installed

fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/Retry.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeNetworkChecker.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckPreferences.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/RetryKtTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
– Integrate `reanalyzeProduct` and `requestAnalysisStatus` APIs in `ReviewQualityCheckService` and middleware.
– Add polling logic for analysis status.
– Create a generic retry function.
– Add an edge case in mapper and test. …
=> Bug 1853311 - Add review checker reanalysis logic

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHistoryTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt, fenix/automation/taskcluster/androidTest/flank-arm-beta.yml, fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml, fenix/automation/taskcluster/androidTest/flank-arm-start-test.yml
For more information please see this [document](https://docs.google.com/document/d/1eRtulddxAlMC5qzjQU77TDhjs7k2f8a6Vbfs7j_UcAg/edit?usp=sharing) …
=> Bug 1854606 - History TestRail matching

fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/NoAnalysis.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckFooter.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityInfoCard.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddlewareTest.kt
Also refactored `LinkType` class to support instances for each external link accessible from the review quality check feature
https://bugzilla.mozilla.org/show_bug.cgi?id=1853301
=> Bug 1853301 - Refactor ReviewQualityCheckNavigationMiddleware to use TabsUseCases and SessionUseCases

android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/webextension/WebExtensionTest.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt, android-components/components/feature/addons/src/test/java/AddonManagerTest.kt, android-components/components/feature/addons/src/test/java/AddonTest.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt, fenix/app/src/test/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragmentTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1844557
=> Bug 1844557 - Disable the switch control when the add-on is blockedlisted.

android-components/components/ui/icons/src/main/res/drawable/mozac_ic_information_fill_24.xml, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckInfoCard.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1854712
=> Bug 1854712 - Update `information_fill` icon

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionRuntime.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/ExtensionProcessDisabledController.kt, fenix/app/src/test/java/org/mozilla/fenix/addons/ExtensionProcessDisabledControllerTest.kt
Depends on https://phabricator.services.mozilla.com/D189350 in GV.
https://bugzilla.mozilla.org/show_bug.cgi?id=1855516
=> Bug 1855516 - Call `disableExtensionProcessSpawning()` when the user clicks the "continue without add-ons" button

android-components/components/service/glean/src/main/java/mozilla/components/service/glean/config/Configuration.kt, fenix/app/.experimenter.yaml, fenix/app/nimbus.fml.yaml, fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1855421
=> Bug 1855421 - Glean: Pass through enableEventTimestamps and add nimbus variable for it

fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt, fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt, fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeature.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt, fenix/app/src/main/res/drawable/ic_shopping_selected.xml, fenix/app/src/test/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeatureTest.kt
Since the toolbar is in XML and depends upon the state of the shopping bottom sheet, using an `Action` became the only reasonable way to get the shopping icon to reset to its default, unselected state. If the toolbar is later converted to Compose, we'll be able to do more direct observations on this new state variable, rather than having to do it indirectly via `ReviewQualityCheckFeature`.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested …
=> Bug 1853304 - Color the shopping icon while the bottom sheet is open

fenix/app/src/main/java/org/mozilla/fenix/shopping/ext/ProductVendor.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckPreferencesMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckVendorsService.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/NoAnalysis.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityInfoCard.kt, fenix/app/src/main/res/values/strings.xml, fenix/app/src/test/java/org/mozilla/fenix/shopping/ReviewQualityCheckBottomSheetStateFeatureTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckVendorsService.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Changes in this PR:
- Added `ProductVendor` to the `OptedIn` state, so it's now a pseudo top-level property for that entire flow. This required adding the necessary logic to `ReviewQualityCheckPreferencesMiddleware` and `ReviewQualityCheckVendorsService` 
- Added the missing text for two sections of the review quality info card. One was dependent on the first bullet point in order to include the product vendor text.
- Added the string ID to the `ProductVendor` enum.
- Added new strings for the AB and DF rating blocks.
- Removed the deprecated use of `ClickableText` for `LinkText`
1. Click …
=> Bug 1855553 - Add missing copy & update existing review quality info copy

android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterDelegate.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/CustomViewHolder.kt, android-components/components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml, android-components/components/feature/addons/src/main/res/values/strings.xml, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt, fenix/app/src/main/java/org/mozilla/fenix/BrowserDirection.kt, fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementView.kt, fenix/app/src/test/java/org/mozilla/fenix/addons/AddonsManagementViewTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1847266
=> Bug 1847266 - Implement status message for blocklisted add-ons in the manager

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NavigationToolbarTest.kt
Summary:
The page security sub menu displayed an incorect connection state because the page wasn't fully loaded before opening the submenu.
Added `waitForPageToLoad()` to be sure the page is fully loaded before verifying the security sub menu.
Successfully passed 100x on Firebase ✅  …
=> Bug 1817930 - Fix verifySecurePageSecuritySubMenuTest UI test

fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1856059
=> Bug 1856059 - Turn off Compose Top Sites

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
Summary:
There were 2 problems that were causing this UI test to be intermittent:
1. `RootViewWithoutFocusException` caused by some deficient syncing after opening the downloaded file.
- To resolve this problem I've used `clickAndWaitForNewWindow` in `clickNotification` which will wait for 3 seconds for the new window (Google photos app) and properly verify that the app opens.
2. Problems trying to dismiss the "Download completed" notification
- As part of the test matching task, this UI test was refactored (the downloaded file is now opened from the notification, the Google photos app is verified that is properly opened and afterwards the notification tray is opened again to dismiss the notification)
- To be sure that the "Download completed" notification is identified and expanded …
=> Bug 1807274 - Fix verifyDownloadCompleteNotificationTest UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
For more information please see this [document](https://docs.google.com/document/d/1UN5DtSWADJg7vD-fd45uXXuzfrE1Zh-Mj9JVxHLaRkI/edit?usp=sharing) …
=> Bug 1856381 - PB search engine results, search groups and search codes TestRail matching

android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/webextension/WebExtensionTest.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterDelegate.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/CustomViewHolder.kt, android-components/components/feature/addons/src/main/res/layout/mozac_feature_addons_item.xml, android-components/components/feature/addons/src/main/res/values/colors.xml, android-components/components/feature/addons/src/main/res/values/strings.xml, android-components/components/feature/addons/src/test/java/AddonManagerTest.kt, android-components/components/feature/addons/src/test/java/AddonTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/SupportUtils.kt, fenix/app/src/main/res/values-night/colors.xml, fenix/app/src/main/res/values/colors.xml, fenix/app/src/test/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragmentTest.kt
~~:warning: Depends on https://github.com/mozilla-mobile/firefox-android/pull/3805 and https://phabricator.services.mozilla.com/D189423~~
To verify this PR, we can (1) install an add-on, (2) set the `xpinstall.signatures.dev-root` (boolean) pref to `true` and (3) use remote debugging to run the following code snippet:
```js
{
const { XPIDatabase } = ChromeUtils.import("resource://gre/modules/addons/XPIDatabase.jsm");
XPIDatabase.verifySignatures();
}
```
3. Click …
=> Bug 1847266 - Implement status message for add-ons not signed correctly in the manager

android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/webextension/WebExtensionTest.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt, android-components/components/feature/addons/src/main/res/values/strings.xml, android-components/components/feature/addons/src/test/java/AddonManagerTest.kt, android-components/components/feature/addons/src/test/java/AddonTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt, fenix/app/src/test/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragmentTest.kt
~~:warning: Depends on https://phabricator.services.mozilla.com/D189763 and https://github.com/mozilla-mobile/firefox-android/pull/3840~~
---
In order to verify this PR, one has to follow the instructions at https://addons-frontend.readthedocs.io/en/latest/fenix/ in order to allow extensions from AMO stage to be installed. Then:
1. open `about:config` and create a boolean pref named `extensions.checkCompatibility.nightly` set to `false`. This will disabled compatibility checks
2. open the fenix add-ons manager and install a test extension named "extension to verify status bar"
3. go back to `about:config` and set the `extensions.checkCompatibility.nightly` pref to `true`
4. re-open the fenix add-ons manager: you should see the "incompatible" message. Note that this won't work without …
=> Bug 1847266 - Implement status message for incompatible add-ons in the manager

fenix/app/metrics.yaml
https://bugzilla.mozilla.org/show_bug.cgi?id=1856950
=> Bug 1856950 - Fix wrong data review link for `device_total_ram`

android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/extension/WebExtensionPromptRequest.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/WebExtensionActionTest.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragment.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/PermissionsDialogFragment.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/PermissionsDialogFragmentTest.kt, android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt, android-components/components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt, fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt, fenix/app/src/test/java/org/mozilla/fenix/extension/WebExtensionPromptFeatureTest.kt
Sorry this is something I should have done in https://github.com/mozilla-mobile/firefox-android/pull/3917. Not sure what I was thinking when I landed the PR as is.
https://bugzilla.mozilla.org/show_bug.cgi?id=1810047
=> Bug 1810047 - Fixup WebExtensionPromptFeature

android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AMOAddonsProvider.kt, android-components/components/feature/addons/src/main/res/values/strings.xml, android-components/components/feature/addons/src/test/java/AddonTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/amo/AMOAddonsProviderTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/ExtensionsTest.kt, android-components/samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonDetailsActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonDetailsBindingDelegate.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonDetailsFragment.kt, fenix/app/src/main/res/layout/fragment_add_on_details.xml, fenix/app/src/test/java/org/mozilla/fenix/addons/AddonDetailsBindingDelegateTest.kt
~~Depends on #3950~~
https://bugzilla.mozilla.org/show_bug.cgi?id=1857232
=> Bug 1857232 - Linkify author of an add-on in the details view

fenix/app/src/main/java/org/mozilla/fenix/collections/CollectionsDialog.kt, fenix/app/src/main/res/values/dimens.xml
This is the same as https://github.com/mozilla-mobile/firefox-android/pull/1393 which already has r+ from @boek. Just starting a fresh PR because Mergify was getting confused on the rebase.
https://bugzilla.mozilla.org/show_bug.cgi?id=1817955
=> Bug 1817955 - Increase Tap Area of the Add new collection prompt edittext field.

android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineMiddleware.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/ExtensionsProcessMiddleware.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ExtensionsProcessStateReducer.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/ExtensionsProcessMiddlewareTest.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/reducer/ExtensionsProcessStateReducerTest.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/CustomViewHolder.kt, android-components/components/feature/addons/src/main/res/layout/mozac_feature_addons_header_section_item.xml, android-components/components/feature/addons/src/main/res/values/strings.xml, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt, android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/ExtensionsProcessDisabledPromptObserver.kt, android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt, android-components/components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt, android-components/samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/ExtensionsProcessDisabledController.kt, fenix/app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt, fenix/app/src/test/java/org/mozilla/fenix/addons/ExtensionsProcessDisabledControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/telemetry/TelemetryMiddlewareTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1847088
=> Bug 1847088 - Show a notification in the Fenix add-on manager when the extensions process spawning is disabled

android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt
Reverts mozilla-mobile/firefox-android#3739
https://bugzilla.mozilla.org/show_bug.cgi?id=1849368
https://bugzilla.mozilla.org/show_bug.cgi?id=1849368
https://bugzilla.mozilla.org/show_bug.cgi?id=1849368
=> Revert "Bug 1849368 - Remove data path and data authorities requirement for open links in apps"

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeCollectionTest.kt
For more information please see this [document](https://docs.google.com/document/d/1_Am_8fF-nXStNcjd9Gltp2KSbZzq1tpFp5lbBRgYNC0/edit?usp=sharing) …
=> Bug 1858081 - Collections TestRail matching

fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1858057
=> Bug 1858057 - Make WebExtensionPrompt available to the whole app.

android-components/components/concept/sync/src/main/java/mozilla/components/concept/sync/OAuthAccount.kt, android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt, android-components/components/service/firefox-accounts/src/test/java/mozilla/components/service/fxa/FxaAccountManagerTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1855291
=> Bug 1855291 - Handle FxA exceptions in getManageAccountURL

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeMediaNotificationTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MediaNotificationTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt
Tabs tray tests data alignment. See doc for reference: https://docs.google.com/document/d/1_VTY18OWluKes4pmENisJqqugaOpwBGGHOwEWiNJJD4/edit
https://bugzilla.mozilla.org/show_bug.cgi?id=1858438
=> Bug 1858438 - Tabs Tray TestRail matching

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTopSitesTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PDFViewerTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TopSitesTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTopSitesRobot.kt, fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
For more information please see this [document](https://docs.google.com/document/d/1lfcr8MCYBYTYbI55MNiP1LT9un3jzyYvhNUlZJi9IQU/edit?usp=sharing) …
=> Bug 1858607 - Top sites TestRail matching

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
Summary:
Sometimes the click on the credit card number text box wasn't properly performed.
Based on the logs the click was performed but in reality it looked like nothing happened. (even after performing the page refresh from the catch block)
I've created `clickCreditCardNumberTextBox()` in which we'll use BySelectors instead of UISelectors, change that seems to be properly working without using any retry loops. (compared to `clickPageObject`)
Both `verifyCreditCardsAutofillToggleTest` and `verifyEditedCardIsSavedTest` successfully passed 100x on Firebase. ✅ 
1. Click on `Checks` at the …
=> Bug 1826318 - Fix verifyCreditCardsAutofillToggleTest UI test

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/home/HomeMenuView.kt, fenix/app/src/test/java/org/mozilla/fenix/home/HomeMenuViewTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1858771
=> Bug 1858771 - New Help button telemetry in home menu

fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt, fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt, fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt, fenix/app/src/main/java/org/mozilla/fenix/components/appstate/shopping/ShoppingState.kt, fenix/app/src/main/java/org/mozilla/fenix/components/appstate/shopping/ShoppingStateReducer.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeature.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt, fenix/app/src/test/java/org/mozilla/fenix/components/appstate/ShoppingActionTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeatureTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/DefaultReviewQualityCheckServiceTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Restore reanalysis state if the product was in the process of reanalyzing when the sheet was closed, i.e. hold state of `productsAnalysed` for a session (no need for persistence).
– Create `ShoppingState` to be held in `AppState`. Migrate existing shopping related state inside so it's all in one place.
– Create `ShoppingReducer` that actions on `ShoppingAction`s, this is a similar pattern to `BrowserStateReducer`.
– Add tests for the above, note that the tests don't just test the reducer but the logic from action dispatch, again similar to `BrowserAction`s, making refactoring of reducer state easier without updating tests.
– Use `AppStore` in `ReviewQualityCheckNetworkMiddleware` to dispatch `AddToProductAnalysed` when reanalysis has started and `RemoveFromProductAnalysed` once reanalysis …
=> Bug 1858018 - Persist review checker reanalysis state

android-components/components/feature/readerview/src/main/assets/extensions/readerview/readerview-background.js, android-components/components/feature/readerview/src/main/assets/extensions/readerview/readerview-content.js, android-components/components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt, android-components/components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt, docs/changelog.md
Also fixes Bug 1856708 - Fixes ReaderView to use new storage.session APIs
https://bugzilla.mozilla.org/show_bug.cgi?id=1856731
https://bugzilla.mozilla.org/show_bug.cgi?id=1856708
=> Bug 1856731 - Moves showing reader mode from the content / background script to the Feature.

android-components/components/compose/awesomebar/build.gradle, android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/AwesomeBar.kt, android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestions.kt, android-components/components/compose/awesomebar/src/test/java/mozilla/components/compose/browser/awesomebar/internal/SuggestionsTest.kt, android-components/components/concept/awesomebar/src/main/java/mozilla/components/concept/awesomebar/AwesomeBar.kt
This commit adds an `onVisibilityStateUpdated` callback to the `AwesomeBar` composable. The new callback is invoked with the current `AwesomeBar.VisibilityState` whenever the list of visible suggestions changes.
I split this out of #4050 to make it a little easier to review, and so that we could land the instrumentation earlier, in case we need to uplift telemetry, or if there are any performance pitfalls.
3. Click on the `build-apk-{fenix,focus,klar}-debug` task …
=> Bug 1859408 - Instrument the awesomebar to report visible suggestions.

android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProvider.kt, android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProviderTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1859644
=> Bug 1859644 - Don't show full keyword in FxSuggest Suggesions

fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt
Uses the newly exposed property from AC/GV to set the state to `UnsupportedProductTypeError` based on the api response.
https://bugzilla.mozilla.org/show_bug.cgi?id=1856959
=> Bug 1856959 - Fix review checker unsupported product error case

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TextSelectionTest.kt
For more information please see this [document](https://docs.google.com/document/d/17zd189M_uzClDtmxZIOuANeEuvkscDXj2TJe3as_8uk/edit?usp=sharing) …
=> Bug 1859318 - Text selection TestRail matching

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
For more information please see this [document](https://docs.google.com/document/d/1NMr5xo-vnle5zp95X5rVUSS-TzBKabdjNLt-6SiutJw/edit?usp=sharing) …
=> Bug 1860052 - Custom tabs TestRail matching

focus-android/app/src/main/java/org/mozilla/focus/fragment/UrlInputFragment.kt, focus-android/app/src/main/java/org/mozilla/focus/searchsuggestions/ui/SearchSuggestionsFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1860263
=> Bug 1860263 - Remove onActivityCreated from Focus fragments.

fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/GenericExperimentIntegrationTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/tests/test_generic_scenarios.py, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
[JIRA TICKET](https://mozilla-hub.atlassian.net/browse/EXP-3955
)
https://bugzilla.mozilla.org/show_bug.cgi?id=1860632
=> Bug 1860632 - Add unenrollment telemetry verification tests to integration test suite

android-components/.buildconfig.yml, android-components/components/browser/state/build.gradle, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/AwesomeBarAction.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/AwesomeBarStateReducer.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/AwesomeBarState.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/BrowserState.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/AwesomeBarActionTest.kt, android-components/components/concept/awesomebar/src/main/java/mozilla/components/concept/awesomebar/AwesomeBar.kt, android-components/components/feature/fxsuggest/README.md, android-components/components/feature/fxsuggest/build.gradle, android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProvider.kt, android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/facts/FxSuggestFacts.kt, android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/facts/FxSuggestFactsMiddleware.kt, android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestFactsMiddlewareTest.kt, android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestFactsTest.kt, android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProviderTest.kt, fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt, fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt, fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarWrapper.kt, fenix/app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
This is a three-part change that builds on bug 1857092 to record impressions for sponsored Firefox Suggest suggestions.
It's probably easiest to review commit-by-commit—the messages for each commit have a bit more context about how the changes fit together! But here's a quick overview:
* The first part adds new actions (`AwesomeBarAction`) and state (`AwesomeBarState`) to `browser-state` that remembers the currently visible suggestions and the last clicked suggestion.
* The second part adds middleware to `feature-fxsuggest` that emits facts for impressions and clicks based on the `AwesomeBarState`.
* The third part is the Fenix integration: dispatching the new `AwesomeBarAction`s, mounting the new middleware, and collecting the emitted facts in Glean.
/cc @ncloudioj
- **Breaking …
=> Bug 1858542 - Add Glean metrics for sponsored Firefox Suggest impressions.

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeature.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/ReviewQualityCheckFeatureTest.kt
Added a new probe `product_page_visits` which counts the number of visits to a supported retailer product page.
Tested ping can be found [here](https://debug-ping-preview.firebaseapp.com/pings/drevla/c5fc61dd-72de-481f-a1c8-8986cd90cbdd) and looks like this:
```
"counter": {
"shopping.product_page_visits": 9,
},
``` …
=> Bug 1854501 - Add telemetry to count Fakespot exposures

taskcluster/ci/build-bundle/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1567912
=> Bug 1567912 - Add shippable secrets in focus/fenix nightly/beta/release AAB

taskcluster/ci/complete/kind.yml
Drive-by fix for an issue I noticed today.
https://bugzilla.mozilla.org/show_bug.cgi?id=1567912
=> Bug 1567912 - Add build-bundle as a dependency for the complete task

fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductRecommendationMapper.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt, fenix/app/src/test/java/org/mozilla/fenix/helpers/LocaleTestRule.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/ProductAnalysisTestData.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/ProductRecommendationTestData.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductRecommendationMapperTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
– Uses `ReviewQualityCheckService` in middleware to fetch product recommendations and update the state
– Add `ProductRecommendationsMapper`
– Update RecommendedProductState.Product to include `aid`.
– Add LocaleTestRule to make Locale based testing easier
Note: Since this is a [bug](https://mozilla-hub.atlassian.net/jira/software/c/projects/FAK/boards/669?selectedIssue=FAK-665) on backend, make `price` nullable in `mozilla.components.concept.engine.shopping.ProductRecommendation` to use this to display the UI. …
=> Bug 1857215 - Part 2:Integrate review checker recommendations

android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonsProvider.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AMOAddonsProvider.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonDialogFragment.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragment.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/Extensions.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/PermissionsDialogFragment.kt, android-components/components/feature/addons/src/main/res/layout/mozac_feature_addons_fragment_dialog_addon_permissions.xml, android-components/components/feature/addons/src/test/java/AddonManagerTest.kt, android-components/components/feature/addons/src/test/java/AddonTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/amo/AMOAddonsProviderTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonDialogFragmentTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonInstallationDialogFragmentTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/ExtensionsTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/PermissionsDialogFragmentTest.kt, android-components/samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt, fenix/app/src/test/java/org/mozilla/fenix/extension/WebExtensionPromptFeatureTest.kt
https://github.com/mozilla-mobile/firefox-android/assets/773158/080e4642-61de-4410-a6bd-2d3a063b4773
https://bugzilla.mozilla.org/show_bug.cgi?id=1858439
=> Bug 1858439 - Refactor how addons icons are loaded

android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AMOAddonsProvider.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/amo/AMOAddonsProviderTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1859755
=> Bug 1859755 - Read text count from AMO API response to get the number of reviews

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt, android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicy.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicyKtTest.kt, fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1861084
=> Bug 1861084 - Add cookie banner global-rules/ sub-frames to default settings and toContentBlockingSetting

android-components/components/feature/readerview/src/main/assets/extensions/readerview/readerview-background.js, android-components/components/feature/readerview/src/main/java/mozilla/components/feature/readerview/ReaderViewFeature.kt, android-components/components/feature/readerview/src/test/java/mozilla/components/feature/readerview/ReaderViewFeatureTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1860130
=> Bug 1860130 - Fix getSerializedDoc message reply in readerview-background.js

docs/contribute/release_checklist.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1862038
=> Bug 1862038 - Update release_checklist.md to swap two steps

android-components/components/feature/fxsuggest/README.md, android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProvider.kt, android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/facts/FxSuggestFacts.kt, android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestFactsMiddlewareTest.kt, android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestFactsTest.kt, android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProviderTest.kt, fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt
This PR:
* Adds new facts, `wikipedia_suggestion_clicked` and `wikipedia_suggestion_impressed`, to the `feature-fxsuggest` component.
* Emits `fx-suggest` Glean pings for those facts in Fenix's `MetricController`.
This PR doesn't add any new probes, but expands the existing `fx_suggest` metrics added for AMP suggestions in https://bugzilla.mozilla.org/show_bug.cgi?id=1857092 and https://bugzilla.mozilla.org/show_bug.cgi?id=1858542 to also be emitted for Wikipedia suggestions. Would you still like a data review form, @HarrisonOg?
@ncloudioj I can't tag you for review—I think you might need to [join the `mozilla-mobile` GitHub organization first](https://bugzilla.mozilla.org/show_bug.cgi?id=1851706), and then I can add you to the `ast` team—but could you take a look also, please?
- …
=> Bug 1860919 - Send Glean pings for Wikipedia Firefox Suggestion impressions and clicks.

fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt, fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
The current onboarding CFR is set to show the first time someone lands on a product detail page. If the user dismisses the CFR and does not opt-in, we show it on the next product detail page after at least 24 hours have elapsed.
This patch changes this to showing the CFR up to 3X (instead of 2) with at least 12 hrs in-between (instead of 24).
https://github.com/mozilla-mobile/firefox-android/assets/32488956/7ac6e185-849c-41df-bc7e-5e84105d942a …
=> Bug 1861173 - Change timing of the Review Checker onboarding CFR

fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt, fenix/app/src/main/res/values/strings.xml
| Before | After | 
| -- | -- |
| ![image](https://github.com/mozilla-mobile/firefox-android/assets/87384386/e971dbc4-e2ec-4be2-b536-988adef35c56) | ![image](https://github.com/mozilla-mobile/firefox-android/assets/87384386/1e072405-e2a0-4050-a4fb-2a7146542889) | …
=> Bug 1861732 - Split-out "terms of use" and "privacy policy" text links

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt, android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt, docs/changelog.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1845835
=> Bug 1845835 - Expose shopping ad attribution events in AC

android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProvider.kt, android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/CombinedHistorySuggestionProvider.kt, android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProvider.kt, android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt, android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/BookmarksStorageSuggestionProviderTest.kt, android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/CombinedHistorySuggestionProviderTest.kt, android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/HistoryStorageSuggestionProviderTest.kt, android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProviderTest.kt, android-components/components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/SyncedTabsStorageSuggestionProvider.kt, android-components/components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/SyncedTabsStorageSuggestionProviderTest.kt, android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/kotlin/String.kt, android-components/components/support/ktx/src/test/java/mozilla/components/support/ktx/kotlin/StringTest.kt, fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt, fenix/app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt
Hi @jonalmeida and @MatthewTighe! 👋🏼 This turned into a bit of a refactor, so I wanted to put this up as a draft for your initial thoughts, in case you'd like to approach it differently!
The big idea is that, if the "show sponsored suggestions" setting is switched on, we want to hide suggestions whose URLs have `mfadid=adm` in their query params.
I saw we already do that for Top Sites via `frecencyFilterQuery`, and set about extending that to suggestions. I also noticed that we already have logic for filtering suggestions to only show URLs for the current search engine when a shortcut engine is selected, which got me thinking about ways to combine these filters.
So I did an exploratory refactor that:
1. Changed the providers to take a predicate function, instead of a URL or a host, for …
=> Bug 1861415 - Filter sponsored suggestion URLs from other providers when the "show sponsored suggestions" setting is enabled

fenix/app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt, focus-android/app/src/main/java/org/mozilla/focus/experiments/NimbusSetup.kt
Fixes [EXP-2822](https://mozilla-hub.atlassian.net/browse/EXP-2822).
This PR tells the `NimbusBuilder` in both Focus and Firefox about SharedPrefernece. The first place this is [exposed to is the Nimbus FML file](https://experimenter.info/fml/using-prefs/).
5. The APK links should be on the right side of the screen, …
=> Bug 1861234 — Add SharedPreferences to NimbusBuilder

fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt, fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt
Using `.inc()` was wrong due to it returning the incremented value and not incrementing the already existing one. This patch aims to fix that, therefore showing the CFR correctly for max 3 times. …
=> Bug 1861173 - Correctly increment shopping CFR counter

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataOnQuitTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadFileTypesTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PDFViewerTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataOnQuitTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
Summary:
- Created `clearDownloadsFolder` which verifies if there are downloaded files on the device and added it to our `@ After `annotations
Tried adding it to `@ Before` as @jjSDET suggested but it didn't seem to properly work.
- Created `openPageAndDownloadFile` which contains the most used navigations and interactions from our download related UI tests and switched to using it where applicable.
✅ All 23 affected download tests successfully passed 75x on Firebase.
2. Click on the `firefoxci-taskcluster` group on the left to expand all …
=> Bug 1863278 - Refactor navigation and storage deletion in downloads UI tests

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddlewareTest.kt
Added `surface_powered_by_fakespot_link_clicked` telemetry probe that is sent when the user taps the "Powered by Fakespot by Mozilla" footer link in Review Checker Sheet.
Ping: 
```
{
"timestamp": 24228,
"category": "shopping",
"name": "surface_powered_by_fakespot_link_clicked"
},
``` …
=> Bug 1862775 - Send telemetry on "Powered by Fakespot by Mozilla" tap

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt, android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicy.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicyKtTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/SettingsTest.kt, fenix/app/nimbus.fml.yaml, fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
This requires a new GV version containing https://phabricator.services.mozilla.com/D192496
https://bugzilla.mozilla.org/show_bug.cgi?id=1862425
=> Bug 1862425 - Allow to control QPS prefs using nimbus.

fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductRecommendationMapper.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductRecommendationMapperTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Removed unneeded states from RecommendedProductState: Loading and Error, because the UI only uses the other 2 states.
https://bugzilla.mozilla.org/show_bug.cgi?id=1862403
=> Bug 1862403 - Remove unneeded states from RecommendedProductState

android-components/components/feature/tabs/src/main/java/mozilla/components/feature/tabs/TabsUseCases.kt, android-components/components/feature/tabs/src/test/java/mozilla/components/feature/tabs/TabsUseCasesTest.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt, fenix/app/src/main/res/drawable/ic_open_in_regular_tab.xml, fenix/app/src/main/res/values/strings.xml
This feature allows a private tab to be reopened as a regular tab. The feature is only enabled for users with the "Open links in a private tab" option enabled - such users who follow links from external applications will always have these tabs opened as private, so may wish to "opt-out" of individual tabs being private.
Users without this option set will not have private tabs opened by default, so have already opted-in to each private tab - thus, those users are unlikely to benefit from this feature.
The feature is added to the main menu - however, as above, it will only be visible when a private tab is open *and* "Open links in a private tab" is enabled, so will only be seen by a minority of users.
The feature is also enabled only for Nightly while it is polished, but the intention is …
=> Bug 1807545 - Add new "Open in regular tab" feature.

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/ext/WaitNotNull.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/TabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
Split the large tests into smaller ones. 
Matched them with new manual tests in TestRail.
Added more logging for easier debugging.
Removed keyboard visibility verification.
All of which improved the crash rates, from ~10-15/100 runs to 2-3/100 runs.
5. The APK links should be on the right side of the screen, named for …
=> Bug 1863319 - Fenix: fix flaky tests in TabbedBrowsingTest

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionDelegate.kt, android-components/components/support/webextensions/src/main/java/mozilla/components/support/webextensions/WebExtensionSupport.kt, android-components/components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1859585
=> Bug 1859585 - WebExtensionSupport should update installExtensions entries on AddonManagerDelegate.onReady calls

android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/private-browsing-web-api-fixes.js
https://bugzilla.mozilla.org/show_bug.cgi?id=1742344
=> Bug 1742344 - Unbreak imgur.io on Android in PBM

android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProvider.kt, android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProviderTest.kt
This commit assigns the lowest possible score to suggestions from `FxSuggestSuggestionProvider`, so that they'll be shown last in the awesomebar.
https://bugzilla.mozilla.org/show_bug.cgi?id=1861417
=> Bug 1861417 - Show sponsored and Wikipedia suggestions last in the awesomebar.

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataOnQuitTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadFileTypesTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataOnQuitTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ShareOverlayRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1863700
=> Bug 1863700 - Add more logs to functions related to download tests and other refactoring work

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
Replaced the add-on that required the most scrolling with one that's at the top of the list.
Also improved the scrolling method with the UISelector actions.
Ran the test 200 times on Firebase, with 0 failures. …
=> Bug 1857875 - Fix SettingsAddonsTest.noCrashWithAddonInstalledTest scrolling issue in add-ons list

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/strings.xml, fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenterTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1859393
=> Bug 1859393 - Add CFR when the first cookie banner gets cleared.

fenix/app/src/main/java/org/mozilla/fenix/search/SearchFragmentStore.kt, fenix/app/src/test/java/org/mozilla/fenix/search/SearchFragmentStoreTest.kt
This commit fixes an issue where it was possible for Firefox to show sponsored and non-sponsored suggestions if the user explicitly disabled and re-enabled the settings, and then unenrolled from the experiment. In that case, the `show{Non}SponsoredSuggestions` settings would still be `true` because they were user-set, even though `enableFxSuggest` was now `false`.
As of this commit, the `show{Non}SponsoredSuggestions` settings are only used if `enableFxSuggest` is `true`.
2. Click on the `firefoxci-taskcluster` group on the left to expand …
=> Bug 1863754 - Disable sponsored and non-sponsored suggestions when Firefox Suggest is disabled.

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1842154
=> Bug 1842154 - Disable failing notificationCanBeDismissedIfDownloadIsInterruptedTest UI test

taskcluster/ci/browsertime/kind.yml
This patch switches the browsertime tests to use the arm64 builds.
https://bugzilla.mozilla.org/show_bug.cgi?id=1865043
https://bugzilla.mozilla.org/show_bug.cgi?id=1865043
https://bugzilla.mozilla.org/show_bug.cgi?id=1865043
https://bugzilla.mozilla.org/show_bug.cgi?id=1865043
https://bugzilla.mozilla.org/show_bug.cgi?id=1865043
https://bugzilla.mozilla.org/show_bug.cgi?id=1865043
=> Bug 1865043 - Switch browsertime tests to use arm64 builds.

fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
To unblock the CI, these have been marked to not run.
Fix the tests and remove `@Ignore` with the mentioned bug.
https://bugzilla.mozilla.org/show_bug.cgi?id=1865226
=> Bug 1865226 - Ignore review checker store flaky tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt
New Firefox suggest related UI smoke tests.
Both UI tests successfully passed 100x on Firebase ✅ 
[List with all keywords](https://drive.google.com/file/d/1o2nLj1L1IAHZCSUL08QHd7sJCEpS8ZZ0/view) …
=> Bug 1864829 - New Firefox suggest related UI smoke tests

fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1865889
```
┌────────────┬─────────────────────┬───────────────┬─────────────────┐
│  MODEL_ID  │      MODEL_NAME     │ OS_VERSION_ID │ DEVICE_CAPACITY │
├────────────┼─────────────────────┼───────────────┼─────────────────┤
│ F01L       │ F-01L               │ 27            │ High            │
│ SH-01L     │ AQUOS sense2 SH-01L │ 28            │ High            │
│ a10        │ Galaxy A10          │ 29            │ High            │
│ b0q        │ Galaxy S22 Ultra    │ 33            │ High            │
│ b4q        │ Galaxy Z Flip4      │ 33            │ High            │
│ cactus     │ Redmi 6A            │ 27            │ High            │
│ dm3q       │ SM-S918U1           │ 33            │ High            │
│ gts8uwifi  │ Galaxy Tab S8 …
```
=> Bug 1865889 - Swap out Pixel2.arm [API 26] in robo-arm for Motorola G20

fenix/app/src/main/java/org/mozilla/fenix/compose/button/FloatingActionButton.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1865904
=> Bug 1865904 - Add correct default elevation to FAB

fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCase.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt, fenix/app/src/test/java/org/mozilla/fenix/components/bookmarks/BookmarksUseCaseTest.kt, fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1835525
=> Bug 1835525 - Bookmark saves to the last select folder

android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/AccountStorage.kt, android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FirefoxAccount.kt, android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt, android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
Include the exception message when reporting
FxaDeviceConstellationException.EnsureCapabilitiesFailed
(https://bugzilla.mozilla.org/show_bug.cgi?id=1865086)
Report restoring an FxA account that's not connected
(https://bugzilla.mozilla.org/show_bug.cgi?id=1864667)
Report a breadcrumb if we queue multiple auth recovery attempts at once
(https://bugzilla.mozilla.org/show_bug.cgi?id=1864994)
3. Click on the `build-apk-{fenix,focus,klar}-debug` task you're interested …
=> Bug 1865086 - More FxA error reporting

fenix/docs/Guide-to-merging-contributor-PRs.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1866260
=> Bug 1866260: Update guide to merging contributor PR and add the steps to replace Bors

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt
This fix keeps the Compose implementation parity with the non-Compose implementation. As a follow task I suggest we change the Collections icon tint to also look disabled - @MozillaNoah wdyt? …
=> Bug 1812732 - Prevent empty Collection being created in Compose Tabs Tray

taskcluster/ci/complete/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1867148
=> Bug 1867148 - Shorten the max runtime for complete jobs to 3min

fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt, fenix/app/src/main/java/org/mozilla/fenix/components/appstate/shopping/ShoppingState.kt, fenix/app/src/main/java/org/mozilla/fenix/components/appstate/shopping/ShoppingStateReducer.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt, fenix/app/src/test/java/org/mozilla/fenix/components/appstate/ShoppingActionTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddlewareTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
Use analysis status api to see if the product analysis is in progress and then show the progress bar
– Previously this state was being saved in `AppState`, it wasn't not needed as the API is providing that state. Remove all the actions and logic related to that. As a result, this will also result in the situation when one client starts the (re)analysis, and if another client opens the same product analysis, the reanalysis will be shown to be in progress since the API provides that.
– Add logic to fetch `analysisStatus` in `ReviewQualityCheckNetworkMiddleware` and update the state accordingly.
– Update the tests
– As a good side effect, the `ReviewQualityCheckTelemetryMiddleware` has been simplified as it doesn't need to rely on `AppStore` anymore but the action param guides it when to …
=> Bug 1861694 - Use analysis status to restore (re)analysis state

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt, android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegateTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionRuntime.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonFilePicker.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonFilePickerTest.kt, android-components/components/support/ktx/src/main/java/mozilla/components/support/ktx/android/net/Uri.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/strings.xml, fenix/app/src/main/res/xml/preferences.xml, fenix/app/src/test/java/org/mozilla/fenix/settings/SettingsFragmentTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1866293
=> Bug 1866293 - Add support for installing an add-on a from local file.

android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt, android-components/components/feature/addons/src/test/java/AddonManagerTest.kt, android-components/samples/browser/src/main/java/org/mozilla/samples/browser/addons/AddonsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1867297
=> Bug 1867297 - Remove the use of `BLOCKED_PERMISSIONS`

fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/RedesignToolbarFeature.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/static_strings.xml, fenix/app/src/main/res/xml/secret_settings_preferences.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1864759
=> Bug 1864759 - Add secret setting and nimbus flag for toolbar redesign

android-components/.buildconfig.yml, android-components/components/feature/fxsuggest/build.gradle, android-components/components/feature/fxsuggest/fxsuggest.fml.yaml, android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProvider.kt, android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProviderTest.kt, fenix/app/nimbus.fml.yaml
This commit adds the `suggestion-provider.available-suggestion-types` Nimbus variable, which holds a list of all available suggestion types that the `FxSuggestSuggestionProvider` can return. This lets us toggle suggestion types remotely as part of our experiments. …
=> Bug 1862536 - Add a Nimbus variable for Firefox Suggest providers.

android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonFilePicker.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1868197
=> Bug 1868197 - Remove onInstallationFailed callback from AddonFilePicker.

android-components/components/feature/addons/src/main/res/values/strings.xml, fenix/app/src/main/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragment.kt, fenix/app/src/main/res/layout/fragment_installed_add_on_details.xml, fenix/app/src/test/java/org/mozilla/fenix/addons/InstalledAddonDetailsFragmentTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1867498
=> Bug 1867498 - Add report add-on button in detail view

fenix/app/src/main/java/org/mozilla/fenix/debugsettings/data/DebugSettingsDataStore.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/static_strings.xml, fenix/app/src/main/res/xml/secret_settings_preferences.xml
After some iteration of exploring the use of the legacy Preferences API + AppState, I've opted to use DataStore here instead. With this approach, we'll have an API that's easy to consume in Compose while also not introducing a huge hack into SecretSettingsFragment in order to handle our use case of an observable preference.
[DataStore is currently being leveraged for Pocket](https://searchfox.org/mozilla-mobile/source/firefox-android/fenix/app/src/main/java/org/mozilla/fenix/datastore/DataStores.kt), so there is no library addition here.
Hopefully, this will serve as a potential migration path for the rest of our settings. 
In order to get the secret settings into the debug drawer, I'll likely need to convert all of them to Compose + DataStore.
- **Breaking Changes**: If this is a …
=> Bug 1864070 - Add secret setting to enable the debug drawer

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1862911
=> Bug 1862911 - Disable restartDownloadFromAppNotificationAfterConnectionIsInterruptedTest UI test

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt, docs/changelog.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1858947
=> Bug 1858947 - Expose Shopping API reportBackInStock to AC

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineView.kt, android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/NestedGeckoViewTest.kt, docs/changelog.md
~Fixed the current tests to pass. We have currently chosen not to
add new ones today after a large amount of investigation. Today, it
is too complicated in order to add something meaningful that would
test the effects of the patch and not the implementation.~
Fixed the current tests to pass.
The current tests are asserting implementation, so a new test was added
to test the behaviour by wrapping `NestedGeckoView` in a parent `View`
and counts the `onInterceptTouchEvent` calls it receives. When we are
in a gesture (starting with `ACTION_DOWN`) we deny the touch events to
the parent views until we receive a result from APZ.
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference …
=> Bug 1847305 - Fix blocked upward scrolling gestures on some pages

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
Add missing steps to `installAddonFromMainMenuTest` UI tests to match manual test steps, based on the toDoAutomation notes from TestRail.
Both tests successfully passed 100x on Firebase ✅ …
=> Bug 1868793 - Add missing step to installAddonFromMainMenuTest UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt
Device: Pixel 2 (Arm), Virtual, API Level 30 
Video of Firebase test run can be found here:
[view in firebase](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/9000795654531717728/details?stepId=bs.cde186f59ec8ccdf&testCaseId=3&tabId=video)
Test Stack Trace:
```
androidx.test.espresso.PerformException: Error performing 'single click' on view '(view.getContentDescription() to match resource id <2131952442>[mozac_feature_addons_install_addon_content_description] with value "Install Add-on" and is descendant of a view matching view.getId() is <2131296499/org.mozilla.fenix.debug:id/add_on_item> and (view.getParent() is an instance of android.view.ViewGroup and has a sibling matching (view is an instance of android.view.ViewGroup and has …
```
=> Bug 1868858 - Fix test failure SettingsAddonsTest.noCrashWithAddonInstalledTest

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataTest.kt
Add missing steps to deleteCookiesAndSiteDataTest UI tests to match manual test steps, based on the toDoAutomation notes from TestRail.
Both tests successfully passed 50x on Firebase ✅  …
=> Bug 1868557 - Add missing steps to deleteCookiesAndSiteDataTest UI tests

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/InstallationMethod.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtensionRuntime.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonFilePicker.kt, android-components/components/feature/addons/src/test/java/AddonManagerTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonFilePickerTest.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1868378
=> Bug 1868378 - Indicate the installation method when installing an add-on.

fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt
Pre-existing scheduled work is not stopped when FxSuggestion is disabled so this adds the stop.
https://bugzilla.mozilla.org/show_bug.cgi?id=1869049
=> Bug 1869049 - stop periodic ingestion when FxSuggest disabled

fenix/app/src/androidTest/java/org/mozilla/fenix/components/FontParserTest.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/fonts/FontEnumerationWorker.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/fonts/FontParser.kt
Unfortunately, the data we got back was flawed; and I hadn't noticed: the device information was present, but the font data was just populating the errors array instead of the fonts array. The FileInputStream on live devices doesn't support reset, so it's been replaced with two separate FileInputStreams.
Also bump the integer to cause another resubmission from Nightly users, and include the submission integer.
https://bugzilla.mozilla.org/show_bug.cgi?id=1868886
=> Bug 1868886: Fix Nightly Font Telemetry

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
Summary:
Didn't encounter any notable search suggestion related problems lately so I've tried to re-enable this test as well.
Successfully passed 100x on Firebase ✅ 
https://bugzilla.mozilla.org/show_bug.cgi?id=1807295
=> Bug 1807295 - Re-enable verifyShowSearchSuggestionsToggleTest UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/Constants.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt
Summary:
The test failed when attempting to bring forward again Fenix.
Instead of Fenix, the "Phone" app was restored, this mostly likely happened because this shard contained telephone redirect related UI tests (`telephoneLinkTest` & `telephoneLinkPWATest`) 
After investigating, if there is more that 1 app in the "Recent apps" tray, and you put an app in background using the "recent apps" button, and press it again, the second app will be resumed. (it does the trick only if you have one open app)
To overcome this problem, I've changed the way we bring Fenix forward, namely by clicking it in the "recent apps" tray.
The "Recent apps" tray will always display only 2 apps, even if previously were opened more than 2 .
Based on this, the index of the most recent app (Fenix) will always be 2, …
=> Bug 1854566 - Fix verifyCreditCardRedirectionsToAutofillSectionAfterInterruptionTest UI test

fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1869518
=> Bug 1869518 - Remove verifyShowSearchSuggestionsToggleTest running on legacy UI task

fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt, fenix/app/src/test/java/org/mozilla/fenix/settings/SettingsFragmentTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1868940
=> Bug 1868940 - Cannot install an add-on a from local file on Android <10.

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1813521
=> Bug 1813521 - Disable failing pauseResumeCancelDownloadTest UI test

fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt
Before, when the screen reader was used, all highlights were announced as static texts.
Now by using collectionInfo and collectionItemInfo,informations like location and the position of the highlight in the list and the size of the list are announced for each category of highlights and for each highlight.
https://github.com/mozilla-mobile/firefox-android/assets/122524342/bafd4170-d3d9-454c-a7c9-975937382094
https://github.com/mozilla-mobile/firefox-android/assets/122524342/68bf9438-c310-44ba-a140-3aac5b043acf …
=> Bug 1857553 - [a11y] Mark up the Review Checker highlights as lists.

android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/Exceptions.kt, android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1869134
=> Bug 1869134 - Don't crash on SyncScopedKeyMissingInServerResponse

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HomeScreenTest.kt
Summary:
This UI test was refactored to use Compose in #1162 but it was disabled because it was failing afterwards (not sure what the cause was, don't have any Firebase runs to check)
Decided to do a status check and it seems that the test is now working properly, successfully passed 100x on Firebase ✅ 
5. The APK …
=> Bug 1830005 - Re-enable addPrivateBrowsingShortcutFromHomeScreenCFRTest UI test

focus-android/automation/taskcluster/androidTest/ui-test.sh
Taskcluster Task ui-test-apk-focus-arm-beta is failing because the new pipeline script , testrail.py that creates TestRail milestones is looking for the wrong .env file for the env vars - test_dashboard.env instead of execution_metadata.env, resulting in the env vars being empty when checked.
We need to update the env file to execution_metadata.env to fix this.
https://bugzilla.mozilla.org/show_bug.cgi?id=1870677
=> Bug 1870677 - Fix failing task ui-test-apk-focus-arm-beta

android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestIngestionWorker.kt, android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestStorage.kt, android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestIngestionWorkerTest.kt, android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestStorageTest.kt, fenix/app/src/main/java/org/mozilla/fenix/components/Components.kt, fenix/app/src/main/java/org/mozilla/fenix/components/FxSuggest.kt
This commit adds a `handleSuggestExceptions` helper to `FxSuggestStorage` that catches and reports `SuggestApiException`s from the Suggest Rust component. `handleSuggestExceptions` works like the existing `handle{Fxa, Places}Exceptions` helpers.
`FxSuggestIngestionWorker`'s retry behavior is unchanged: if ingestion fails, the exception will now be reported, but the operation will still be rescheduled using `WorkManager`'s retry mechanism, as before.
3. Click on …
=> Bug 1869225 - Catch `SuggestApiException`s.

focus-android/app/metrics.yaml
This essentially reverts 1216dfff92897e998b15b1c99398e644453dd620 (in parts). The metrics was added to all pings a while back to aid validation. This is now not needed anymore. …
=> Bug 1864645 - Focus: Do not send legacy ID in other built-in pings

android-components/samples/browser/src/main/res/layout/activity_add_on_details.xml
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking issues. **See:** https://github.com/mozilla-mobile/reference-browser/pull/2625
https://bugzilla.mozilla.org/show_bug.cgi?id=1870668
=> Bug 1870668 - Remove the `mozac_feature_addons_authors` string

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SponsoredShortcutsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuHomepageRobot.kt
Summary:
This UI test was disabled due to the [HomeActivity ANR](https://bugzilla.mozilla.org/show_bug.cgi?id=1807268).
Based on the logs and videos the problems seem to be occurring after performing the long click on the sponsored shortcut using BySelector.
The video shows that the long click is performed, on the other hand, the logs don't contain any info about this action.
Another worth mentioning matter would be that the java.lang.SecurityException: Calling from not trusted UID! at android.app.UiAutomationConnection.throwIfCalledByNotTrustedUidLocked(UiAutomationConnection.java:525) is constantly displayed in the logs before the test fails. (seems to be part of the UiAutomationConnection class in the Android framework. It is a method used for security checks, specifically to ensure …
=> Bug 1807268 - Re-enable openSponsoredShortcutsSettingsOptionTest UI test

android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt, android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt, docs/changelog.md
Do the same thing as https://github.com/mozilla-mobile/firefox-android/blob/main/fenix/app/src/main/java/org/mozilla/fenix/customtabs/CustomTabToolbarMenu.kt#L53
It's not possbile to test `share action uses updated url` , because Context.share is a extension function and use default parameter. Reference: https://github.com/mockito/mockito-kotlin/issues/240 and https://github.com/mozilla-mobile/android-components/pull/9420#discussion_r560275546 …
=> Bug 1831803 - Use getter to access CustomTabSessionState

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/translate/GeckoTranslationUtils.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationError.kt
This patch defines different possible translation errors, how they map from GeckoView, and how they map to errors we display.
https://bugzilla.mozilla.org/show_bug.cgi?id=1862263
=> Bug 1862263 - Translations Error Support

fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugDrawer.kt, fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugOverlay.kt, fenix/app/src/main/res/layout/activity_home.xml
https://github.com/mozilla-mobile/firefox-android/assets/87384386/053fc60a-55fe-427d-bd0f-a272c36eea38
https://bugzilla.mozilla.org/show_bug.cgi?id=1864072
=> Bug 1864072 - Create initial drawer UI

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/DataGenerationHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/FirefoxSuggestTest.kt
Based on this [suggestion](https://github.com/mozilla-mobile/firefox-android/pull/4546#pullrequestreview-1744598867):
- Created a map for sponsored/non sponsored suggestions which will be randomly used in the UI tests
- Created `getSponsoredFxSuggestPlaceHolder` helper to help us properly check the sponsored suggestions links (some of the links contain a placeholder `%YYYYMMDDHH%`)
All 7 UI tests successfully passed 100x on Firebase ✅  …
=> Bug 1868371 - Add more test data to Fx suggest related UI tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SponsoredShortcutsTest.kt
Summary:
This UI test was disabled due to the [HomeActivity ANR](https://bugzilla.mozilla.org/show_bug.cgi?id=1807268).
With the changes made in #4921 to the long click on the sponsored shortcut, now it works properly.
Successfully passed 200x on Firebase ✅ 
5. The APK links should be on the right side of the screen, …
=> Bug 1807268 - Re-enable openSponsorsAndYourPrivacyOptionTest UI test

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1872777
=> Bug 1872777 - Update LeakCanary to version 2.13

fenix/app/src/main/java/org/mozilla/fenix/library/bookmarks/BookmarkFragmentInteractor.kt
Bookmark open telemetry wasn't being fired on most common use case for opening bookmarks.
https://bugzilla.mozilla.org/show_bug.cgi?id=1836167
=> Bug 1836167 - Fix Bookmark Open telemetry

android-components/components/browser/menu/src/main/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItem.kt, android-components/components/browser/menu/src/test/java/mozilla/components/browser/menu/item/WebExtensionBrowserMenuItemTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1806838
=> Bug 1806838 - Update extension icon when invalidate is called.

fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/debugsettings/store/DebugDrawerAction.kt, fenix/app/src/main/java/org/mozilla/fenix/debugsettings/store/DebugDrawerState.kt, fenix/app/src/main/java/org/mozilla/fenix/debugsettings/store/DebugDrawerStore.kt, fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugOverlay.kt, fenix/app/src/test/java/org/mozilla/fenix/debugsettings/DebugDrawerStoreTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1864073
=> Bug 1864073 - Stand up debug drawer Store and State

fenix/app/metrics.yaml, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/FeatureSettingsHelperDelegate.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/HomeActivityTestRule.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MainMenuTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarMenuController.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarMenu.kt, fenix/app/src/main/res/values/strings.xml, fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarMenuControllerTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1868989
=> Bug 1868989 - Translations UI Add Translate Page Browser Menu Button.

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/NestedGeckoView.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/NestedGeckoViewTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1872170
=> Bug 1872170 - Fix Pull to Refresh triggered after an upward overscroll on a page

android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1864890
=> Bug 1864890 - fix home button margin on display toolbar

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt, android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/translate/GeckoTranslationUtils.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationError.kt
This bug takes the named AC `TranslationError` and ensures that all translation calls to the Gecko engine translate to this type of error.
https://bugzilla.mozilla.org/show_bug.cgi?id=1872703
=> Bug 1872703 - Named Translation Errors

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsSearchTest.kt
Summary:
In some cases the UI test was flaky because no suggestions were displayed, most likely caused by [1813587](https://bugzilla.mozilla.org/show_bug.cgi?id=1813587) which is still very easily reproducible.
While manually trying different scenarios, I've noticed that when using DuckDuckGo or Wikipedia the search suggestions are immediately displayed compared to Google.
Based on what I've discussed with @mcarare , there seems to be an app services worker that periodically retrieves the suggestions, locally saves them and afterwards get displayed.
I think there might be some delays related to the Google search suggestions, so I've added a couple of steps in the UI test to use DuckDuckGo instead. ✅  successfully passed 200x on Firebase.
- **Breaking Changes**: If this is a breaking …
=> Bug 1807295 - Fix verifyShowSearchSuggestionsToggleTest UI test

fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BottomToolbarContainerView.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/NavigationBar.kt, fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
Top | Bottom
--- | --- 
https://bugzilla.mozilla.org/show_bug.cgi?id=1868260
=> Bug 1868260 – Sync navbar position with toolbar

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerBlockerTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NavigationToolbarRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Summary:
The implementation of the feature was changed in #4398 and mostly everything related to the automated tests were removed.
Created 2 new automated smoke tests for the new implementation of the feature:
- `verifyCookieBannerBlockerSettingsOptionTest` ✅ successfully passed 100x on Firebase
- `verifyCFRAfterBlockingTheCookieBanner` (using a website listed in the [cookie banner rule list](https://github.com/mozilla/cookie-banner-rules-list/blob/main/cookie-banner-rules-list.json#L800)) ✅ successfully passed 150x on Firebase
As the feature is not available yet on RC builds I had to add a running condition for these UI tests.
Also, the banner detection mechanism improved over the last couple of months meaning that an older issue was fixed …
=> Bug 1873200 - New cookie banner blocker UI smoke tests

fenix/app/src/main/java/org/mozilla/fenix/components/IntentProcessors.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1873375
=> Bug 1873375 - Should open shared search terms in private mode if 'Open links in a private tab' is set.

fenix/app/src/main/java/org/mozilla/fenix/compose/LinkText.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt, fenix/app/src/main/res/values/strings.xml
This patch aims to improve a11y experience when accessing links present in bodies of text. When we have a link text element, we now indicate that there are links present in it and upon double tapping, if there is only one link, that one will be opened, if there are multiple ones, a dialog is open from where the user can access any of the links present in the text. This behavior tries to follow the default Talkback a11y one where the user can access links from a text in case they are annotated as URLs.
This solution makes all the links in a text accessible and also improves accessibility for lower version devices.
Review checker was chosen to showcase thise due the text with two links, but this solution applies to all places wher `LinkText` is used.
| Talkback | Our Solution |
| …
=> Bug 1857850 - [a11y] Improve experience when accessing links in text

fenix/app/build.gradle, fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugDrawer.kt, fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/DebugOverlay.kt, fenix/app/src/main/java/org/mozilla/fenix/debugsettings/ui/FenixOverlay.kt, fenix/app/src/main/res/values/strings.xml, fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
The logic to connect the UI to the navigation middleware will added in the next ticket, [Bug 864076](https://bugzilla.mozilla.org/show_bug.cgi?id=1864076).
https://github.com/mozilla-mobile/firefox-android/assets/87384386/f5842db7-819b-42e4-9239-10f236b697a7
5. The APK links should be on the right side of the screen, …
=> Bug 1864078 - Create debug drawer navigation UI

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAdvancedTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsRobot.kt
Summary:
In #3602 the Youtube related links were changed to the Android Youtube Scheme URL because in some cases the UI tests ran on non US located devices which led to the cookie banners being displayed, causing failures.
This UI test was flaky because the "Open links in apps" banner  wasn't displayed sometimes.
From my point of view, the Android Youtube Scheme URL `vnd.youtube` wasn't always properly recognized, so I've switched the link in this particular case to `m.youtube.com`
Even though it might display the cookie banner (if the UI test runs on a non US device) it will not have any impact in this case, the "Open links in apps"  banner will be properly displayed, as it will display Youtube's cookie banner not the Google's banner (the later being displayed when trying to access …
=> Bug 1858874 - Fix goToSettingsFromOpenLinksInAppCFRTest UI test

android-components/components/feature/downloads/README.md, android-components/components/feature/downloads/src/main/AndroidManifest.xml, android-components/samples/browser/src/main/AndroidManifest.xml, fenix/app/src/main/AndroidManifest.xml, focus-android/app/src/main/AndroidManifest.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1874124
=> Bug 1874124 - Add foregroundServiceType for DownloadService and FOREGROUND_SERVICE_DATA_SYNC permission.

android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineMiddleware.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TranslationsState.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddlewareTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationOperation.kt
This patch adds the additional state information of `supportedLanguages` and `translationError` to `TranslationsState`. The `supportedLanguages` are the languages the translation engine supports for translating for use in UI dropdowns. `translationError` is any error that occurred relating to translating.
`supportedLanguages` is currently set via an action that indicates the intention to translate on the new `EngineMiddleware` addition of `TranslationsMiddleware`. This patch also adds a new `TranslationOperation` of `FETCH_TO_AND_FROM_LANGUAGES` to indicate the process of getting `supportedLanguages`.
`translationError` is added to the `TranslationsState` to store errors as they arise. `TranslateExceptionAction` is also refactored from using the generic `Throwable` to the new …
=> Bug 1873511 - New `supportedLanguages` and `translationError` on TranslationsState, with `TranslateExceptionAction` Refactor

android-components/components/feature/media/src/main/java/mozilla/components/feature/media/middleware/RecordingDevicesMiddleware.kt
See https://bugzilla.mozilla.org/show_bug.cgi?id=1854936#c3
https://bugzilla.mozilla.org/show_bug.cgi?id=1854936
=> Bug 1854936 - Update notification reminder delay to 5 min instead of 5 sec

fenix/app/build.gradle, fenix/benchmark/build.gradle, fenix/benchmark/src/main/java/org/mozilla/fenix/benchmark/BaselineProfilesStartupBenchmark.kt, fenix/benchmark/src/main/java/org/mozilla/fenix/benchmark/baselineprofile/StartupOnlyBaselineProfileGenerator.kt, fenix/build.gradle
This PR adds baseline profiles generator, startup metric benchmark to see the difference between startup timings with/out baseline profiles. The goal is to test the change in startup timings in nightly. 
The metrics to consider:
– [Google Play Vitals - Nightly - Slow Cold Start](https://play.google.com/console/u/0/developers/7083182635971239206/app/4975374341268119750/vitals/metrics/details?peersetKey=1%3A37fd48e7&metric=COLD_STARTUP_TIME&days=28)
– [Glean - cold_x_app_to_first_frame](https://dictionary.telemetry.mozilla.org/apps/fenix?page=1&search=perf.startup) - I think it's interesting to monitor other first frame metrics along with `cold_main_app_to_first_frame` as the benefits can be in other metrics as well since the startup path has common elements.
| Benchmark …
=> Bug 1807350 - Baseline profiles for nightly

fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/ext/Activity.kt, fenix/app/src/main/res/navigation/nav_graph.xml, fenix/app/src/test/java/org/mozilla/fenix/customtabs/ExternalAppBrowserActivityTest.kt
Step 2 from [Bug 1865306 - RFC Custom Tabs](https://github.com/mozilla-mobile/firefox-android/pull/4732/files)
https://bugzilla.mozilla.org/show_bug.cgi?id=1870232
=> Bug 1870232 - Delegate the Activity's getNavDirections() functionality

android-components/components/feature/prompts/src/main/res/values/strings.xml, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1862738
=> Bug 1862738 - Put credential management strings before translation

fenix/app/src/main/java/org/mozilla/fenix/compose/SwitchWithLabel.kt, fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationOptionsDialog.kt, fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSettings.kt, fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSwitchItem.kt, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1871408
=> Bug 1871408 - Translations UI Add Messages Under On Toggles

docs/changelog.md, fenix/app/nimbus.fml.yaml, fenix/app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
This PR is of O(_n_) [complexity](https://www.egorand.dev/the-big-o-of-code-reviews/).
The NimbusSetup file is mostly untested, and the Nimbus API's `recordIsReady` function records internal-to-nimbus Glean events. The `recordIsReady` function is tested [here](https://github.com/mozilla/application-services/pull/6063/files#diff-3d95777c584e63ddf89922d9a523258d2b5490f0e140db2fb3579c7dc07a6f50).
Depends on code from mozilla/application-services#6063 — should be in Nightly 01/20/24. You can build this locally before this day by checking out and using a local copy of application-services.
1. …
=> Bug 1875515 - record Nimbus is_ready event

fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/customtabs/ExternalAppBrowserFragment.kt
=> Bug 1873991 - Fix customtab crash when nav bar is enabled

android-components/.editorconfig, fenix/.editorconfig, focus-android/.editorconfig
https://bugzilla.mozilla.org/show_bug.cgi?id=1875923
=> Bug 1875923 - Update max_line_length in editorconfig to match detekt

fenix/app/src/main/java/org/mozilla/fenix/ext/View.kt, fenix/app/src/main/java/org/mozilla/fenix/home/toolbar/SearchSelectorBinding.kt
The touching area for search engine icon (Google by default) from the search bar was only 28dp.
To Increase tap area to reach the minimum accessibility touch target size of 48dp, it was used TouchDelegate. This way there are no visual changes.
Other notes:
For Android 9 and earlier versions, Accessibility Scanner will not detect that we used TouchDelegate to enlarge touch targets to an appropriate size. So the changes can be seen with Accessibility Scanner on devices with android 10 +. 
More on [support.google.com](https://support.google.com/accessibility/android/answer/7101858?hl=en#zippy=%2Ccompose%2Cview:~:text=Accessibility%20Scanner%20can%20detect%20and%20account%20for%20the%20use%20of%C2%A0TouchDelegate%C2%A0only%20when%20running%20on%20Android%2010%20and%20later.%20On%20earlier%20An …
=> Bug 1838580 - [a11y] Increase tap area for search engine icon

android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesStorage.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1875891
=> Bug 1875891 - Adding MalformedInputException to catch list of handlePlacesExceptions.

android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksUseCases.kt, android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksUseCasesTest.kt
[Screen_recording_20240124_153659.webm](https://github.com/mozilla-mobile/firefox-android/assets/6579541/8111d5ed-e0d6-44e0-9b97-5d0b6e7f3b89)
https://bugzilla.mozilla.org/show_bug.cgi?id=1875087
=> Bug 1875087 - Do no intercept content urls in applinks

android-components/.editorconfig, android-components/ktlint-baseline.xml, fenix/.editorconfig, fenix/ktlint-baseline.xml, focus-android/.editorconfig, focus-android/build.gradle, focus-android/ktlint-baseline.xml
Updated ktlint-baseline with the current warnings suppressed until we can find a good time to run `ktlintFormat` globally on the entire project.
Filed BZ-1876836 as a follow-up to remove the baseline file in the future. …
=> Bug 1876419 - Move comment from editorconfig files

android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml, android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt, android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
Reverting mozilla-mobile/firefox-android#5141 as this patch has created more bugs, see: 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1875933, 
- https://bugzilla.mozilla.org/show_bug.cgi?id=1875788
https://bugzilla.mozilla.org/show_bug.cgi?id=1812843
https://bugzilla.mozilla.org/show_bug.cgi?id=1812843
https://bugzilla.mozilla.org/show_bug.cgi?id=1812843
https://bugzilla.mozilla.org/show_bug.cgi?id=1812843
https://bugzilla.mozilla.org/show_bug.cgi?id=1812843
=> Revert "Bug 1812843 - Increased the width for a CustomTabsToolbarFeature action button"

android-components/.editorconfig, fenix/.editorconfig, focus-android/.editorconfig
Reverts mozilla-mobile/firefox-android#5250
https://bugzilla.mozilla.org/show_bug.cgi?id=1875923
https://bugzilla.mozilla.org/show_bug.cgi?id=1875923
=> Revert "Bug 1875923 - Update max_line_length in editorconfig to match detekt"

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
Summary:
- As part of the Android test hardening, to ease the debugging process, I've added test logs to the `CollectionRobot`
- Also converted the private variables to functions so they don't get initialized
- Removed unused functions
- Use where applicable the functions from the `MatcherHelper` to avoid adding unnecessary logs 
- ❗There is [this](https://github.com/mozilla-mobile/firefox-android/pull/5313/files#diff-1f0f53606bb4c1c9a89ce422b9ac691fb4b2064d76f6e90cbf3f51ed96ba5d06R173) `verifySnackBarText` function which  actually doesn't assert anything, only waits for an item containing text.
Will do a separate refactoring related to these snackbar verifications as we have a function in `TestHelper` which is only partially used in the project and have a couple more individual functions …
=> Bug 1876700 - Add more test logs to CollectionRobot

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
Summary:
- As part of the Android test hardening, to ease the debugging process, I've added test logs to the ComposeTabDrawerRobot
https://bugzilla.mozilla.org/show_bug.cgi?id=1876720
=> Bug 1876720 - Add more test logs to ComposeTabDrawerRobot

fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/TabPreview.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/ToolbarIntegration.kt, fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultToolbarIntegrationTest.kt
Old | New
--- | --- 
https://bugzilla.mozilla.org/show_bug.cgi?id=1864760
=> Bug 1864760 - Hide toolbar actions in BaseBrowserFragment toolbar

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1876596
=> Bug 1876596 - Add probe for debug drawer secret setting

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
Summary:
- The problem seem to be happening when trying to click the close button of the open tab (`closeTab`)
- To overcome this problem before performing the click, I've added a wait for the button to exist and an assertion
- To be 100% sure that it works properly, I've removed the RetryRule and the UI test successfully passed 200x on Firebase ✅ 
4. Click on `View task in …
=> Bug 1844252 - Fix verifyVideoPlaybackSystemNotificationTest UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeBookmarksTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BookmarksRobot.kt
Summary:
- As part of the Android test hardening, I've removed the redundant assertion functions
- Removed some unused functions
- Switched to use `verifySnackBarText` from `TestHelper` in the bookmarks related UI tests as it looks I've overlooked it in the previous PR
5. The APK links should be on the right side of …
=> Bug 1877938 - Remove redundant assertion functions from BookmarksRobot

taskcluster/ci/browsertime/kind.yml
This patch disables a failing android test on this branch.
https://bugzilla.mozilla.org/show_bug.cgi?id=1682027
=> Bug 1682027 - Disable failing facebook android test.

android-components/components/feature/search/src/main/java/mozilla/components/feature/search/telemetry/SerpTelemetryRepository.kt, fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/static_strings.xml, fenix/app/src/main/res/xml/secret_settings_preferences.xml, focus-android/app/src/main/java/org/mozilla/focus/settings/advanced/SecretSettingsFragment.kt, focus-android/app/src/main/java/org/mozilla/focus/settings/advanced/SharedPreferenceUpdater.kt, focus-android/app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt, focus-android/app/src/main/java/org/mozilla/focus/utils/Settings.kt, focus-android/app/src/main/res/values/preference_keys.xml, focus-android/app/src/main/res/values/static_strings.xml, focus-android/app/src/main/res/xml/secret_settings.xml
| Fenix  | Focus |
| ------------- | ------------- |
| <img src="https://github.com/mozilla-mobile/firefox-android/assets/29518411/504d1bfa-152a-4cea-a4b0-492bba968cd4" width="400" height="800">  |  <img src="https://github.com/mozilla-mobile/firefox-android/assets/29518411/143ef205-ed03-42b8-924c-d2d5d3b3bf1b" width="400" height="800"> |
4. Click on `View task in Taskcluster` in the …
=> Bug 1868539 - Add method of changing remote server url

android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/manifest/WebAppManifestParser.kt, fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Based on my understanding that `ExternalAppBrowserActivity` should handle its own theming via the web manifest, I _think_ the issue that we are seeing (with the multiple bugs related to the status bar icons not being visible) is due to additional theming provided by the `HomeActivity` parent class (potentially another symptom of the coupled nature between Home and External App Browser). 
For now, I have gated these checks to make it explicit this is not required in External App browser usage. Ongoing refactoring of the `HomeActivity` will remove these, along with the other `ExternalAppBrowserActivity` gates.
I think there is a **separate issue** being [reported](https://bugzilla.mozilla.org/show_bug.cgi?id=1814646) in that Custom Tabs do not sync with the browser theme (light/dark) (see …
=> Bug 1813875 - Prevent the inherited theming implementation being applied to Custom Tabs views

fenix/app/build.gradle
This was previously generated as a side effect, and fails with the new AGP version. See also https://github.com/mozilla-mobile/fenix/issues/14175.
=> Bug 1870050 - Properly define buildConfigField SUPPORTED_LOCALE_ARRAY

android-components/components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/SvgIconDecoder.kt, android-components/components/support/images/src/main/java/mozilla/components/support/images/decoder/AndroidImageDecoder.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1874522
=> Bug 1874522 - Catch OOM, set desired size and disable coil-kt cache in SVG decoder

taskcluster/ci/release-notify-promote/kind.yml
Donal noticed this today.
https://bugzilla.mozilla.org/show_bug.cgi?id=1567912
=> Bug 1567912 - Add signing-bundle as a dependency for notify-promote

fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BottomToolbarContainerView.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/NavigationBar.kt, fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
I reused some of the classes already masterfully crafted by @MozillaNoah  for the nav bar as well :)
Old | New
--- | --- 
https://bugzilla.mozilla.org/show_bug.cgi?id=1874943
=> Bug 1874943 - Add a tab counter UI element

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/FindInPageRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1877945
=> Bug 1877945 - Remove redundant assertion functions from FindInPageRobot

android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/AbstractFetchDownloadService.kt, android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/AbstractFetchDownloadServiceTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1876806
=> Bug 1876806 - Do not remove downloaded files in private tabs after deleting browsing data

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt, fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt, fenix/app/src/main/java/org/mozilla/fenix/telemetry/TelemetryMiddleware.kt, fenix/app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
This commit:
* Sends the new `awesomebar.{engagement, abandonment}` events when the user finishes interacting with the awesomebar. These events match [iOS's events of the same name](https://github.com/mozilla-mobile/firefox-ios/pull/18452), and Desktop's `urlbar.{engagement, abandonment}` events.
* Removes the `engagement_abandoned` extra key for the `awesomebar.{sponsored, non_sponsored}_suggestion_impressed` events, since they're specific to AMP and Wikipedia suggestions, and are subsumed by the new events.
This is the first step toward unifying our awesomebar search telemetry on all our platforms.
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the …
=> Bug 1878434 - Add the `awesomebar.{engagement, abandonment}` events.

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CollectionRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1879027
=> Bug 1879027 - Add missing pairs of logs to CollectionRobot

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
Summary:
- Removed the redundant assertion functions
- Removed unused functions
- Converted the private variables to functions so they don't get initialized
- Added test logs …
=> Bug 1879072 - Add test logs to HomeScreenRobot

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestSetup.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BookmarksTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/BrowsingErrorPagesTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CollectionTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CookieBannerBlockerTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt
Added the API level condition and re-ran the tests on the legacy API devices: [matrix link](https://console.firebase.google.com/project/moz-fenix/testlab/histories/bh.66b7091e15d53d45/matrices/8612533797408958851/details?stepId=bs.750faaf3927d91c9&testCaseId=1).
Everything passed. …
=> Bug 1878868 - Create TestSetup helper: Test classes A-C (fix for legacy APIs)

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
Summary:
Added missing pairs of logs to `ComposeTabDrawerRobot`
https://bugzilla.mozilla.org/show_bug.cgi?id=1879308
=> Bug 1879308 - Add missing pairs of logs to ComposeTabDrawerRobot

android-components/components/browser/menu/src/main/java/mozilla/components/browser/menu/WebExtensionBrowserMenuBuilder.kt, android-components/components/browser/menu/src/main/res/values/strings.xml, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1870319
=> Bug 1870319 - Announce title in add-ons sub-menu

fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1879583
=> Bug 1879583 - Change the default for pull-to-refresh to enabled

docs/rfcs/0001-rfc-process.md
This reverts commit e1e6e86bf6525a123518919bfc620108396ad3dc.
After discussion, it was agreed that updates to existing RFCs are not a pattern we want to accept. Any changes to process will be captured in additional documents. …
=> Revert "Bug 1833666 - Update original RFC guidelines with stakeholders"

android-components/components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt, android-components/components/feature/session/src/test/java/mozilla/components/feature/session/SessionUseCasesTest.kt, docs/changelog.md, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CrashReportingTest.kt
When we have an existing `engineSession` we use an optimized route to load the url without needing to dispatch the load action. This is still a valid performance improvement to make page loads faster.
However, in this code path we do not end up update the url in the state until we get back a response from the Engine. This gives a perceived performance loss of slow browsing. Updating the url gives UI components an immediate update which reflects a change that would have been entered by the user.
It was considered if we should do this in a middleware, but since this is an optimized route, we should not wait for the middleware to process the action before we perform the state update.
[Screen_recording_20240131_171947.webm](https://github.com/mozilla-mobile/firefox-android/assets/1370580/63b16 …
=> Bug 1868469 - Update the url immediately for existing engineSession

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
Summary:
- Added pairs of test logs to the `NotificationRobot`
- Converted the private variables to functions so they don't get initialised
https://bugzilla.mozilla.org/show_bug.cgi?id=1880047
=> Bug 1880047 - Add missing pairs of logs to NotificationRobot

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/PwaRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ReaderViewRobot.kt
Summary:
- Added pairs of test logs to the `PwaRobot`
- Added pairs of test logs to the `ReaderViewRobot`
- Remove redundant assertion functions from `ReaderViewRobot`
https://bugzilla.mozilla.org/show_bug.cgi?id=1880064
=> Bug 1880064 - Add logs to ReaderViewRobot

fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1880150
=> Bug 1880150 - Do not wait for attribution before dismissing splash screen

android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddlewareTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationPageSettingOperation.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationPageSettings.kt
The goal of this bug is to have a way to update page settings.
It adds:
* A new action, `UpdatePageSettingAction`
* This action has four options:
* `UPDATE_ALWAYS_OFFER_POPUP`
* `UPDATE_ALWAYS_TRANSLATE_LANGUAGE`
* `UPDATE_NEVER_TRANSLATE_LANGUAGE`
* `UPDATE_NEVER_TRANSLATE_SITE`
* Each operation eagerly sets the new setting on the browser store, then
sends the request to the engine. If setting on the engine fails, then
they will re-request the page settings in order to remain in-sync.
2. Click on the `firefoxci-taskcluster` group on the …
=>  Bug 1877203 - Update Translations Page Settings

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/RecentlyClosedTabsRobot.kt
Summary:
- Added pairs of test logs to the `RecentlyClosedTabsRobot`
- Converted the private variables to functions so they don't get initialised
https://bugzilla.mozilla.org/show_bug.cgi?id=1880221
=> Bug 1880221 - Add logs to RecentlyClosedTabsRobot

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAccessibilityRobot.kt
Summary:
- Added pairs of test logs to the SettingsSubMenuAccessibilityRobot
- Removed the redundant assertion functions from SettingsSubMenuAccessibilityRobot
https://bugzilla.mozilla.org/show_bug.cgi?id=1880466
=> Bug 1880466 - Add logs to SettingsSubMenuAccessibilityRobot

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerAddonDetailedMenuRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt
Summary:
- Added pairs of test logs to the `SettingsSubMenuAddonsManagerAddonDetailedMenuRobot`
- Added pairs of test logs to the `SettingsSubMenuAddonsManagerRobot`
- Removed the redundant assertion functions from `SettingsSubMenuAddonsManagerRobot`
5. The APK links should be on the right side of the screen, named …
=> Bug 1880620 - Add logs to SettingsSubMenuAddonsManagerRobot

android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt
Relates to [Bug 1880476](https://bugzilla.mozilla.org/show_bug.cgi?id=1880476).
According to [The Big O of Code Reviews](https://www.egorand.dev/the-big-o-of-code-reviews/), this is a O(_1_) change.
Automated inlining of a duplicated property. …
=> Bug 1880476 — Remove redundant nimbusFeature in NimbusMessagingStorage

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataOnQuitRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1880827
=> Bug 1880827 - Add test logs to SettingsSubMenuDeleteBrowsingDataOnQuitRobot

android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt, android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingFragment.kt
Relates to [Bug 1880476](https://bugzilla.mozilla.org/show_bug.cgi?id=1880476).
According to [The Big O of Code Reviews](https://www.egorand.dev/the-big-o-of-code-reviews/), this is a O(_n_) change.
This PR is the second part of a Nimbus improvement in the `NimbusMessagingHelper`, which adds JEXL caching to that class, rather than forcing clients to implement their own caching.
The NimbusMessagingHelper also grew a `destroy` method which calls the Rust drop methods on the native peers. This fixes a small, but long standing memory leak.
2. …
=> Bug 1880476 — Remove redundant caching and destroy jexl helper after use

android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProvider.kt, android-components/components/feature/awesomebar/src/test/java/mozilla/components/feature/awesomebar/provider/SessionSuggestionProviderTest.kt
Original:
----------
With patch:
https://bugzilla.mozilla.org/show_bug.cgi?id=1880829
=> Bug 1880829 - Restrict suggest to show a single open tab suggestion for identical tabs

taskcluster/ci/ui-test-apk/kind.yml
The update from a previous PR to decouple the `ui-test-apk` `Taskcluster` task was reverted, causing the task to call an old python script `testrail.py` that has since been renamed to `testrail_main.py`.
Moreover, other changes that decoupled that script from ui-test-apk have been reverted and need to be changed back.
The changes include removing the following from `focus-arm-beta` and `fenix-arm-beta`:
- removing call to `testrail.py`
- removing `extra.notify slackBlocks`
- removing `secret` fetching for `testrailCredentials`
2. Click on …
=> Bug 1880912 - Remove TestRail Script and Dependencies from ui-test-apk TC Task

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDeleteBrowsingDataRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1881010
=> Bug 1881010 - Add logs to SettingsSubMenuDeleteBrowsingDataRobot

android-components/components/tooling/fetch-tests/src/main/java/mozilla/components/tooling/fetch/tests/FetchTestCases.kt, android-components/components/tooling/lint/src/main/java/mozilla/components/tooling/lint/ConceptFetchDetector.kt, android-components/components/tooling/lint/src/main/java/mozilla/components/tooling/lint/LintIssueRegistry.kt, android-components/components/tooling/lint/src/test/java/mozilla/components/tooling/lint/ConceptFetchDetectorTest.kt, docs/changelog.md
In BZ-1839067, we fixed a multiple cases were streams werepotentially leaking resources. As a follow-up, we are adding a lint check that now helps to identify possible missing calls to close those resources.
The implementation is heavily relied on from [`com.android.tools.lint.checks.CleanupDetector`][0] in the AOSP project, so little cleanup is done to change the code from it's original source if we need to reference it later.
Some other references that were quite helpful for this work, were the [Android Lint API Guide][1] and the examples in the [Data Flow Analyzer][2].
Kudos to @jackyzy823 for doing the initial work in BZ-1839067 to start this off.
[0]: https://cs.android.com/android-studio/platform/tools/base/+/mirror-goog-studio-main:lint/libs/lint-checks/src/main/java/com/android/too …
=> Bug 1872235 - Add lint detector for missing Response#close 

android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt, android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt
Relates to [Bug 1880476](https://bugzilla.mozilla.org/show_bug.cgi?id=1880476).
According to [The Big O of Code Reviews](https://www.egorand.dev/the-big-o-of-code-reviews/), this is a O(_n_) change.
This moves the filtering of expired and interacted with messages for a given surface from the only-done-once `getMessages()` method to done-every-time a message is asked for. Given that expiry and interactions are based on stored state, these should be done each time, and removes some checking needed to be done in the surfaces. …
=> Bug 1880476 — NimbusMessaging: Move filtering to getNextMessage

fenix/app/src/main/res/values/strings.xml
⚠️ https://github.com/mozilla-mobile/firefox-android/pull/5666 should be reviewed before this as the string numbering is continued from there 
ℹ️  Changes from experiment Doc:
- **Branch D**
- Copy changed from “600” to “700” for Fenix based on the real number of extensions available: 782
- “PDF’s” was changed to “PDFs”
- **Branch C**   
- The period after “Firefox privacy notice” has been omitted …
=> Bug 1881016 - Added experimental onboarding strings for Nimbus treatments C & D

android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingController.kt, android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt, android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingControllerTest.kt, android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt, fenix/app/src/test/java/org/mozilla/fenix/messaging/DefaultMessageControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/messaging/state/MessagingMiddlewareTest.kt
Relates to [Bug 1880476](https://bugzilla.mozilla.org/show_bug.cgi?id=1880476).
According to [The Big O of Code Reviews](https://www.egorand.dev/the-big-o-of-code-reviews/), this is a O(_n_) change.
This PR moves the generated Glean events for message display (message_shown and exposure events) into a single place. This should reduce the disparity between these events down to zero.
`getNextMessage` now only emits exposure events when the message is a control message.
2. Click on the `firefoxci-taskcluster` group on the left to expand all …
=> Bug 1880476 — Refactor onMessageDisplayed bookkeeping

taskcluster/ci/browsertime/kind.yml
This patch changes the web-de test to bild-de since the web-de test can no longer be recorded due to a cookie banner. See bug 1880115.
https://bugzilla.mozilla.org/show_bug.cgi?id=1881976
=> Bug 1881976 - Replace web-de with bild-de pageload test.

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt, fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
Details in the bug.
https://bugzilla.mozilla.org/show_bug.cgi?id=1881703
=> Bug 1881703 - Notify app store of mode change from TabsTray

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestSetup.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeBookmarksTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeCollectionTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeContextMenusTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHistoryTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeHomeScreenTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeMediaNotificationTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeNavigationToolbarTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataOnQuitTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTopSitesTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1879525
=> Bug 1879525 - Create TestSetup helper: Compose Test classes

fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1878921
=> Bug 1878921 - Translations CouldNotLoadLanguagesError UI "Try Again"

android-components/components/service/nimbus/messaging.fml.yaml, android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/Message.kt, android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt, android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingControllerTest.kt, android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt, fenix/app/messaging-evergreen-messages.fml.yaml, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusMessagingHomescreenTest.kt, fenix/app/src/test/java/org/mozilla/fenix/components/AppStoreTest.kt, fenix/app/src/test/java/org/mozilla/fenix/messaging/DefaultMessageControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/messaging/state/MessagingMiddlewareTest.kt, fenix/app/src/test/java/org/mozilla/fenix/messaging/state/MessagingReducerTest.kt
Relates to [Bug 1880483](https://bugzilla.mozilla.org/show_bug.cgi?id=1880483).
According to [The Big O of Code Reviews](https://www.egorand.dev/the-big-o-of-code-reviews/), this is a O(_n_) change.
This is a breaking change. It is one of two breaking changes outline in the [Transition Phase 1](https://docs.google.com/document/d/1m6hBG7rjut1Q84Wy9SxxTz8bEXlFkoV-H4GMzZfZ4pY/edit#heading=h.mhha8y8yhj1n) of the Mobile Messaging Go Forward plan.
This changes the `trigger` key to `trigger-if-all` to document that all triggers in this list must evaluate to true.
It also adds `exclude-if-any`, a list of triggers which, if any are true will exclude the message.
This will remove the need for triggers like `I_AM_NOT_BROWSER_DEFAULT`.
~~It should not land until user-research (@El and @roseanne) have …
=> Bug 1880483 — Add inverse triggers to messaging component

android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonsManagementFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1870339
=> Bug 1870339 - Make list of add-ons more accessible

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt
Temporarily disabling these auto-fill view tests until test assets are updated. They will then require updating the scroll gesture to keep from scrolling past the elements we are asserting exist. …
=> Bug 1882170 - Disable Auto-Fill View Tests After Address Fields Were Consolidated

fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1880284
=> Bug 1880284 - Show keyboard after voice input

fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/TabPreview.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/tabstrip/TabStrip.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/tabstrip/TabStripCard.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/tabstrip/TabStripState.kt, fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/home/ToolbarView.kt, fenix/app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/CustomizationFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/layout/fragment_browser.xml, fenix/app/src/main/res/layout/fragment_home.xml, fenix/app/src/main/res/values-sw600dp/dimens.xml, fenix/app/src/main/res/values/dimens.xml, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/static_strings.xml, fenix/app/src/main/res/xml/customization_preferences.xml, fenix/app/src/main/res/xml/secret_settings_preferences.xml, fenix/app/src/test/java/org/mozilla/fenix/browser/tabstrip/TabStripStateTest.kt, fenix/app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
– Add Secret Settiings - "Enable Tab Strip" that's visible only on tablets.
– Display open tabs in a Tab Strip above toolbar
– Add Ability to add a new tab and close tabs.
While these are not features of the Tab Strip UI, these are changes are in Settings when tab strip is enabled:
– toolbar customization in Settings is not shown as Toolbar defaults to Top.
– Swipe tab gesture to switch tabs in settings is not shown as it is disabled.
– Update toolbar position based on form factor. This required replacing usages of `settings.shouldUseBottomToolbar` to `settings.toolbarPosition`. 
– `ToolbarPosition` is defaults to `TOP` when it's a tablet. This is done to simplify the implementation.
– Add dimensions to help update layouts and positioning logic
– Display TabStrip on `HomeFragment` and …
=> Bug 1875465 - Add tab strip for tablets

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuOpenLinksInAppsRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1882264
=> Bug 1882264 - Add logs to SettingsSubMenuOpenLinksInAppsRobot

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuPrivateBrowsingRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1882272
=> Bug 1882272 - Add logs to SettingsSubMenuPrivateBrowsingRobot

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuSitePermissionsRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1882732
=> Bug 1882732 - Add logs to SettingsSubMenuSitePermissionsRobot

android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt, android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt, fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
Fix non-private mode:
---
Fix private mode:
🍦 for those curious, the ice cream in the article is vanilla and chocolate chips. Arguably not really a 'flavour', it's vanilla ice cream with a topping... …
=> Bug 1882308 - Updated custom tab to support private mode

fenix/app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1882914
=> Bug 1882914 - Add `iconOnColorDisabled` color token

android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestStorage.kt
This is not used yet, but we're planning on using it to store persistent data that shouldn't be cleared with the cache.
https://bugzilla.mozilla.org/show_bug.cgi?id=1879649
=> Bug 1879649 - Set the data path for the Suggest component

focus-android/app/src/androidTest/java/org/mozilla/focus/activity/SettingsGeneralTest.kt
This will need to be uplifted so we have a match of running smoke tests on all branches.
https://bugzilla.mozilla.org/show_bug.cgi?id=1883319
=> Bug 1883319 - Focus: tag englishSystemLocaleTest as smoke UI test

android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/FxaDeviceConstellation.kt, android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/AppServicesStateMachineChecker.kt, android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt
See https://bugzilla.mozilla.org/show_bug.cgi?id=1883412 for details.
- Don't assume that all `Event.Progress.FailedToRecoverFromAuthenticationProblem` events come from `AuthenticationError`
- Updated who sends events to the state machine checker in the case of `finalizeDevice`:
- `finalizeDevice` now sends the event in the case of succesfull calls and auth errors.
- `FxaAccountManager` now sends the event in the case of other errors. …
=> Bug 1883412 - Fxa state machine fixes

fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/TranslationsBinding.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/DefaultToolbarMenu.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1877277
=> Bug 1877277 - Translations add Check for isTranslationsEngineSupported

fenix/app/src/main/java/org/mozilla/fenix/components/UrlRequestInterceptor.kt, fenix/app/src/test/java/org/mozilla/fenix/components/UrlRequestInterceptorTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1875668
=> Bug 1875668 - Bypass cache when intercepting URL requests

README.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1883700
=> Bug 1883700 - Add monorepo migration announcement link to Readme

fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/tabstrip/TabStrip.kt, fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppAction.kt, fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppState.kt, fenix/app/src/main/java/org/mozilla/fenix/components/appstate/AppStoreReducer.kt, fenix/app/src/main/java/org/mozilla/fenix/ext/Context.kt, fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/test/java/org/mozilla/fenix/components/appstate/TabStripActionTest.kt
Details in the bug
– Extract common undo snackbar message utility
– Use that in existing places
– Add callbacks for `onCloseTab(private)` in `TabStrip`
– display snackbar using the callbacks and the utility function
There's a scenario where BrowserFragment navigates to Home when all tabs are closed. To "remember"/"know" to show the snackbar, `HomeScreenViewModel` is used as it's Activity scoped. …
=> Bug 1882106 - Show undo snackbar when tab is closed via tab strip

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestSetup.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1883870
=> Bug 1883870 - Improve test logs in bookmarks and downloads storage deletion in UI test

android-components/components/browser/icons/build.gradle, android-components/components/browser/icons/src/main/java/mozilla/components/browser/icons/decoder/SvgIconDecoder.kt, android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
1. Use AndriodSVG directly
It is safe to use AndroidSVG , because it is the dependency of coil-svg
Since android-components has its own cache mechanism , using coil-kt is just bloating.
2. Catch OOM error just like https://github.com/mozilla-mobile/firefox-android/blob/76213dc84f49a0400e009ea06e3d09fd3ad68ded/android-components/components/support/images/src/main/java/mozilla/components/support/images/decoder/AndroidImageDecoder.kt#L36
3. Set target bitmap size according to desiredSize to avoid svg too large which could also cause OOM
The code is **largely borrowed** from  https://github.com/coil-kt/coil/blob/2.4.0/coil-svg/src/main/java/coil/decode/SvgDecoder.kt with some fixed options.
( **However  I'm not sure if this patch will really fix the bug. and also i'm not sure if the bug was …
=> Bug 1874522 - Repalce coil-kt with AndroidSVG

fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1883418
=> Bug 1883418 - Translate icon is should be visible on Private Browsing Mode

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/PDFViewerTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/CustomTabRobot.kt
The `openInApp` button was removed from the PDFViewer context and the tests need to have reference to that element removed.
There is one test for that element that needs to be deleted and 2 references in other Robots that need updated.
Changes:
* Deleting `verifyPDFViewerOpenInAppButtonTest`
* Removing unused import for `itemWithResIdAndText` in `PDFViewerTest.kt`
* Deleting element reference in `verifyPDFReaderToolbarItems` from `BrowserRobot.kt`
* Deleting element reference in `verifyPDFReaderToolbarItems` from `CustomTabRobot.kt`
2. Click …
=> Bug 1884154 - Remove openInApp Button Reference from UI Tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt
Summary:
- The UI test was flaky when trying to verify that the normal browsing tabs list containing a tab exists
- This happened because sometimes the tab wasn't displayed right away in the tabs tray meaning that the empty tabs tray was actually displayed
- To overcome this problem, I've added a step to wait for the empty tabs tray list to not exist before trying to assert the tabs tray list containing a tab
✅ The UI test successfully passed 200x on Firebase
3. …
=> Bug 1846707 - Fix closeAllTabsTest UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/TabDrawerRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1884329
=> Bug 1884329 - Add logs to TabDrawerRobot

android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt, android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/RemoteTabsStorage.kt, android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/RemoteTabsStorageTest.kt, android-components/components/feature/syncedtabs/src/main/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorage.kt, android-components/components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/helper/SyncedTabsProvider.kt, android-components/components/feature/syncedtabs/src/test/java/mozilla/components/feature/syncedtabs/storage/SyncedTabsStorageTest.kt, fenix/app/src/main/java/org/mozilla/fenix/components/BackgroundServices.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/TabSorter.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/ext/TabSessionState.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/syncedtabs/SyncedTabs.kt, fenix/app/src/test/java/org/mozilla/fenix/sync/ext/SyncedDeviceTabsTest.kt
This approach seems like a reasonable first step and we can do further cleanups in followups.
https://bugzilla.mozilla.org/show_bug.cgi?id=1879332
=> Bug 1879332 - ensure synced tabs includes the inactive property

android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt
This bug slightly adjusts the reducer to set `isOfferTranslate` to false once a translation occurs.
https://bugzilla.mozilla.org/show_bug.cgi?id=1884459
=> Bug 1884459 - Prevent Offers to Translate after a Translation Occurs

fenix/app/src/main/java/org/mozilla/fenix/components/UrlRequestInterceptor.kt, fenix/app/src/test/java/org/mozilla/fenix/components/UrlRequestInterceptorTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1884666
=> Bug 1884666 - Only add Google additional header in search, preferences and webhp urls

android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProvider.kt, android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProviderTest.kt
To consistent with Desktop, we want to limit the number of sponsored/nonsponsored suggestion to be 1.
https://bugzilla.mozilla.org/show_bug.cgi?id=1884822
=>  Bug 1884822 - Suggest: Limit returned suggestion to 1

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/MockWebExtension.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt, android-components/components/feature/addons/src/test/java/AddonTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1882404
=> Bug 1882404 - Expose granted permissions on AC.

taskcluster/ci/ui-test-apk/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1885946
Beta Flank configuration (Fenix) https://github.com/mozilla-mobile/firefox-android/blob/releases_v125/fenix/automation/taskcluster/androidTest/flank-arm-beta.yml
Beta Flank configuration (Focus) https://github.com/mozilla-mobile/firefox-android/blob/releases_v125/focus-android/automation/taskcluster/androidTest/flank-arm-beta.yml
Older shell script was doing a direct assignment of configuration based on parameter `arm-beta-tests` passed in from `ui-test-apk` kind.yml
https://github.com/mozilla-mobile/firefox-android/blob/47e42ede7190947891ec2276601462d01af771e7/fenix/automation/taskcluster/androidTest/ui-test.sh#L83
Newer Python script doesn't do that as it just takes in the portion of the Flank configuration file name …
=> Bug 1885946 - Fix Fenix/Focus beta test run calls in ui-tests-apk configuration

android-components/components/support/remotesettings/src/main/java/mozilla/components/support/remotesettings/RemoteSettingsClient.kt
=> Bug 1886730 - catch NLP during RemoteSetting getRecords() failure

android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt
Differential Revision: https://phabricator.services.mozilla.com/D206558
=> Bug 1875111 - Show keyboard when acquiring focus in edit toolbar.

fenix/app/src/main/res/values-night/colors.xml
Before the fix, Accessibility Scanner was showing the color contrast
between text color and the background color as insufficient.
With the modification made the accessibility scanner shows the
problem as fixed. The color that was used for the fix is the closest to
the one before that can satisfy the contrast required.
[Link to the patch on phabricator](https://phabricator.services.mozilla.com/D206365)
3. Click on the `build-apk-{fenix,focus,klar}-debug` task …
=> Bug 1876719 - [a11y] Increasing contrast for collection's dialog buttons
