monorepo-migration/sync-ac.sh
I was getting fed up of manually creating a merge commit message. Let's get that done automatically 🙂
=> sync-ac: Generate merge commit message automatically

.taskcluster.yml, taskcluster/ac_taskgraph/loader/build_config.py, taskcluster/ac_taskgraph/release_promotion.py, taskcluster/ci/build/kind.yml, taskcluster/ci/github-release/kind.yml
Tested on staging at https://firefox-ci-tc.services.mozilla.com/tasks/groups/T1cHe7oqROKKeKlhJbq3jg
=> Bug 1786780 - Migrate release android-components jobs

monorepo-migration/sync-ac.sh
=> sync-ac: Let script safely create ac-prep branch

.git-blame-ignore-revs
=> Move .git-ignore-blame-revs to the top-level and update the commit sha

.github/workflows/sync-strings.yml
=> Temporarily change Sync String actions to run every 15 minutes

monorepo-migration/generate-replace-message-expressions.py, monorepo-migration/sync-focus.sh
=> Bug 1797244 - Add script for syncing Focus into the monorepo

android-components/docs/index.md
Still just trying to get this green. Getting close...
=> Docs: Fix blog post include on main page

docs/_config.yml
We're also doing this to test the pages build.
=> Docs: Clean up jekyll config

docs/_config.yml
=> Update the source directory in docs/_config.yml

docs/contribute/release_checklist.md, docs/index.md
=> Docs: Fix paths in release_checklist.md and index.md

android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt, docs/changelog.md
=> Bug 1798359 - Have TCP as the default cookie policy.

taskcluster/ac_taskgraph/loader/build_config.py
=> Uplift 106 - Check the correct file path when returning a list of AC files changed  in build_config.py

taskcluster/ac_taskgraph/loader/build_config.py
=> Uplift 107 - Check the correct file path when returning a list of AC files changed in build_config.py

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/EngineStateReducer.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/feature/session/src/main/java/mozilla/components/feature/session/SessionUseCases.kt, docs/changelog.md
Fenix PR https://github.com/mozilla-mobile/fenix/pull/27525
=> Bug 1796482 - Allow for notifying consumers on unsuccessful Save to PDF requests

docs/components.md
=> Fix more links to point to new repo where applicable

android-components/buildSrc/src/main/java/Gecko.kt
=> Update GeckoView (Release) to 107.0.20221107173030

taskcluster/ac_taskgraph/target_tasks.py, taskcluster/ci/trigger-nightly/kind.yml
=> Bug 1791748 - Fix trigger-nightly task after repository move

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoSitePermissionsStorage.kt, android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegate.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/permission/GeckoSitePermissionsStorageTest.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/GeckoWebNotificationDelegateTest.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webnotifications/MockWebNotification.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/permission/SitePermissionsStorage.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webnotifications/WebNotification.kt, android-components/components/feature/sitepermissions/src/androidTest/java/mozilla/components/feature/sitepermissions/db/OnDeviceSitePermissionsStorageTest.kt, android-components/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/OnDiskSitePermissionsStorage.kt, android-components/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/SitePermissionsFeature.kt, android-components/components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/OnDiskSitePermissionsStorageTest.kt, android-components/components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/SitePermissionsFeatureTest.kt, android-components/components/feature/webnotifications/src/main/java/mozilla/components/feature/webnotifications/WebNotificationFeature.kt, android-components/components/feature/webnotifications/src/test/java/mozilla/components/feature/webnotifications/NativeNotificationBridgeTest.kt, android-components/components/feature/webnotifications/src/test/java/mozilla/components/feature/webnotifications/WebNotificationFeatureTest.kt
=> Improve site permissions APIs

taskcluster/ac_taskgraph/target_tasks.py
We're not running on github-release events so don't need to look for them.
Ported from https://github.com/mozilla-mobile/android-components/pull/12786
=> RELENG-207 - Drop obsolete code looking for github-release graphs

android-components/components/feature/media/src/main/java/mozilla/components/feature/media/service/MediaSessionServiceDelegate.kt
=> Bug 1796353 - Cancel media notification explicitly on service shutdown.

android-components/buildSrc/src/main/java/Gecko.kt
=>  Update GeckoView (Beta) to 108.0.20221117185908.

.github/workflows/ac-create-release.yml, .github/workflows/ac-update-geckoview.yml
=> Bug 1800542 - part 7: Bump relbot from 4.0.1 to 4.0.2

.mergify.yml
Tested this in the mergify config editor using #192 and #193.
=> Bug 1800542 - part 8: Fix mergify autoland of Gecko.kt updates in release branches

android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestions.kt, android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchActionProvider.kt, android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt, docs/changelog.md
=> Bug 1800700 - Add default search suggest header

android-components/components/lib/crash/src/test/java/mozilla/components/lib/crash/CrashReporterTest.kt
The test was failing intermittently because `recordCrashBreadcrumb` now runs in a coroutine context.  Make sure to run that context before checking the results.
=> Bug 1801611: Fix CrashReporterTest

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
=> Upgrade Application Services to v96.0.1

android-components/components/compose/awesomebar/src/main/java/mozilla/components/compose/browser/awesomebar/internal/Suggestions.kt, android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchActionProvider.kt, android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchSuggestionProvider.kt, docs/changelog.md
Reverts mozilla-mobile/firefox-android#205
=> Revert "Bug 1800700 - Add default search suggest header"

.taskcluster.yml, taskcluster/ac_taskgraph/loader/build_config.py
For more info about the performance improvement: [bug 1788606 comment 12](https://bugzilla.mozilla.org/show_bug.cgi?id=1788606#c12) and https://github.com/taskcluster/taskgraph/pull/160.
=> Bug 1788606 - Decision task: let docker-worker cache the gradle cache

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/permission/GeckoSitePermissionsStorage.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/permission/GeckoSitePermissionsStorageTest.kt, android-components/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/OnDiskSitePermissionsStorage.kt, android-components/components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/OnDiskSitePermissionsStorageTest.kt, docs/changelog.md
=> Bug 1801648 - Fix autoplay settings are not getting updated in private mode

android-components/buildSrc/src/main/java/Gecko.kt
=>  Update GeckoView (Release) to 108.0.20221205155917

taskcluster/ci/complete/kind.yml
=> Bug 1796658 (followup): update notification recipients

focus-android/app/build.gradle, focus-android/build.gradle, focus-android/gradle.properties, focus-android/service-telemetry/build.gradle, focus-android/settings.gradle
⚠️ Do not land. This PR will be merged on Tuesday, December 13th 2022. This is part of the migration of focus to the monorepo.
=> Bug 1804716 - Consume AC via gradle build with relative path in Focus

android-components/plugins/dependencies/settings.gradle, android-components/plugins/publicsuffixlist/settings.gradle, focus-android/build.gradle, focus-android/buildSrc/src/main/java/Config.kt
=> Bug 1805946 - Ensure Glean and Nimbus gradle plugins are consuming the latest version

.github/workflows/ac-create-release.yml, .github/workflows/ac-update-geckoview.yml
Real change is in https://github.com/mozilla-mobile/relbot/pull/98
=> Bug 1800542 - part 10: Bump relbot from 5.0.1 to 5.0.2

.github/workflows/ac-sync-strings.yml, .github/workflows/focus-sync-strings.yml
=> Bug 1797245 - Bump the versions for the Sync Strings GitHub actions

taskcluster/ci/build-apk/kind.yml, taskcluster/ci/signing-apk/kind.yml
=> Bug 1805383 - Change treeherder platform for focus build/signing

focus-android/app/src/main/java/org/mozilla/focus/widget/TelemetrySwitchPreference.kt
Uplifting as part of https://github.com/mozilla-mobile/firefox-android/pull/371.
=> Bug 1805184 - Enable or disable Glean collection and upload immediately.

android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, docs/changelog.md
=> Bug 1806435 - Add CookieBannerHandlingMode.DETECT_ONLY

focus-android/app/build.gradle, focus-android/app/src/main/java/org/mozilla/focus/fragment/about/AboutFragment.kt, focus-android/buildSrc/src/main/java/Config.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1805553
=> Bug 1805553 - Include git revision in About Fragment

taskcluster/ci/release-notify-push/kind.yml
Per https://bugzilla.mozilla.org/show_bug.cgi?id=1806884#c5, make the body of the email self contained instead of a continuation of the subject.
=> Bug 1806884: tweak release push notification message

android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/CFRPopupContent.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1808033
=> Bug 1808033 - Add content description for Dismiss Button in CFRPopupContent

focus-android/app/metrics.yaml, focus-android/app/src/main/java/org/mozilla/focus/telemetry/GleanMetricsService.kt
=> Bug 1803358 - Add telemetry to check if notifications are allowed for Focus

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/BrowserStateReducer.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/CookieBannerStateReducer.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/CustomTabSessionState.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/SessionState.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TabSessionState.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/CookieBannerActionTest.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, docs/changelog.md
=> Bug 1797568 - Expose delegates for observing cookie banner handling events

android-components/components/support/utils/src/main/java/mozilla/components/support/utils/ManufacturerCodes.kt, android-components/components/support/utils/src/test/java/mozilla/components/support/utils/ManufacturerCodesTest.kt
=> Upstream checking for device manufacturer for LG devices.

.github/workflows/ac-sync-strings.yml, .github/workflows/focus-sync-strings.yml
=> No issue - Bump fenix-beta-version to 4.2.2 and add workflow dispatch for sync string actions

focus-android/app/src/androidTest/java/org/mozilla/focus/activity/DownloadFileTest.kt, focus-android/app/src/androidTest/java/org/mozilla/focus/helpers/StringsHelper.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1809619
=> Bug 1809619 - Fix expected results on downloadAndOpenPdfFileTest

android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/injections.js, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/shims.js, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1743614-storytel.com-flex-min-width.css, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/injections/css/bug1768243-cloud.google.com-allow-table-scrolling.css, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-analytics-and-tag-manager.js, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/google-ima.js, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/shims/microsoftVirtualAssistant.js
r? @wisniewskit 
https://bugzilla.mozilla.org/show_bug.cgi?id=1805407
=> Bug 1805407 - Ship v110.0.0 of the WebCompat System Addon.

focus-android/app/src/androidTest/assets/cross-site-cookies.html, focus-android/app/src/androidTest/assets/same-site-cookies.html, focus-android/app/src/androidTest/java/org/mozilla/focus/activity/SettingsPrivacyTest.kt, focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/BrowserRobot.kt, focus-android/app/src/androidTest/java/org/mozilla/focus/activity/robots/SettingsPrivacyMenuRobot.kt
Switched the test page to new local assets, and added some new test coverage for all the options.
https://bugzilla.mozilla.org/show_bug.cgi?id=1808672
=> Bug 1808672 - adding local assets for cookie settings UI tests, improved coverage

.mergify.yml, .taskcluster.yml, taskcluster/android_taskgraph/transforms/complete.py, taskcluster/ci/complete/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1810150
=> Bug 1810150 - don't run pull-request task graphs when we already have a push graph

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/cookiebanners/GeckoCookieBannersStorage.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1809921
=> Bug 1809921 - Address crash when visit internal sites like about config when cookie banner is ON

android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehavior.kt, android-components/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/behavior/BrowserToolbarBehaviorTest.kt, android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadDialogFragment.kt, android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt, android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ext/DownloadState.kt, android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/ui/DownloaderAppAdapter.kt, android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/DownloadsFeatureTest.kt, android-components/components/feature/downloads/src/test/java/mozilla/components/feature/downloads/ext/DownloadStateKtTest.kt, docs/changelog.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1783561
=> Bug 1783561 - Allow clients better styling and control of the download dialogs

focus-android/app/build.gradle
=> Update implementation of dependency

docs/changelog.md
Followup to https://github.com/mozilla-mobile/firefox-android/pull/578 
=> Clean changelog following revert of downloads changes

focus-android/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1811490
=> Bug 1811490 - Add < at the start of each of the localization comment

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt, android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicy.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/ext/TrackingProtectionPolicyKtTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/SettingsTest.kt, docs/changelog.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1810743
=> Bug 1810743 - Expose detect-only setting in AC

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1810743
=> Bug 1810743 - Add cookieBannerHandlingDetectOnlyMode as part of the defaultSettings

android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/DownloadsFeature.kt, android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/manager/FetchDownloadManager.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1796348
=> Bug 1796348 - Add post notification permission requirement for downloads.

.github/workflows/focus-update-nimbus-experiments.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1797245
=> Bug 1797245 - Use the same branch names for the update nimbus experiments action

focus-android/app/src/main/java/org/mozilla/focus/browser/integration/FullScreenIntegration.kt, focus-android/app/src/main/res/values/strings.xml, focus-android/app/src/test/java/org/mozilla/focus/browser/integration/FullScreenIntegrationTest.kt
=> Show snackbar when entering fullscreen mode

.github/workflows/ac-sync-strings.yml, .github/workflows/focus-sync-strings.yml
@gabrielluong 
I've tested these on my fork. I would merge this only after we make sure that the current version of the uplift action works (it can be done manually), but it's up to you.
https://bugzilla.mozilla.org/show_bug.cgi?id=1814338
=> Bug 1814338 - Use v3 of sync-string-actions

.github/workflows/ac-sync-strings.yml, .github/workflows/focus-sync-strings.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1814338
=> Bug 1814338 - Fix commit message in uplift strings workflow, only copy localized files

android-components/components/support/utils/src/main/java/mozilla/components/support/utils/DownloadUtils.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1792926
=> Bug 1792926 - After downloading, the download name was fixed. Check if the string is empty.

android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/CFRPopupFullscreenLayout.kt, android-components/components/compose/cfr/src/main/java/mozilla/components/compose/cfr/helper/DisplayOrientationListener.kt, android-components/components/compose/cfr/src/test/java/mozilla/components/compose/cfr/CFRPopupFullscreenLayoutTest.kt, android-components/components/compose/cfr/src/test/java/mozilla/components/compose/cfr/helper/DisplayOrientationListenerTest.kt, docs/changelog.md
Testing the result with the TCP CFR configured with all alignments:
|  | cfr aligned to the center of the entire toolbar |  cfr aligned to the start of the lock icon | cfr indicator aligned to the middle of the lock icon |
| --- | --- | --- | --- |
| | <video src=https://user-images.githubusercontent.com/11428869/211756362-a201c67c-f222-420e-9418-1e88c411ff23.mp4 /> | <video src=https://user-images.githubusercontent.com/11428869/211756448-5f8ffd3d-fdee-4cf5-82f7-e7936ae85b34.mp4 /> | <video src=https://user-images.githubusercontent.com/11428869/211756608-57d2b04a-e9da-431e-a05b-99891ca07afd.mp4 /> |
- **Milestone**: Make sure issues closed by this pull request are added to the [milestone](https://github.com/mozilla-mobile/android-components/milestones) of the version currently in …
=> Bug 1809592 - CFR alignment polish

taskcluster/android_taskgraph/target_tasks.py
Backports https://github.com/mozilla-mobile/fenix/blob/65949d1b7267027a3b70107a1395701d13c966df/taskcluster/fenix_taskgraph/target_tasks.py#L103-L119
Fixes: 
```
[task 2023-02-14T09:02:11.029Z] 2023-02-14 09:02:11,029 - INFO - Generating target task set
[task 2023-02-14T09:02:11.035Z] Traceback (most recent call last):
[task 2023-02-14T09:02:11.035Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/main.py", line 753, in main
[task 2023-02-14T09:02:11.036Z]     args.command(vars(args))
[task 2023-02-14T09:02:11.037Z]   File "/builds/worker/.local/lib/python3.8/site-packages/taskgraph/main.py", line 626, in decision
[task 2023-02-14T09:02:11.037Z]     taskgraph_decision(options)
[task 2023-02-14T09:02:11.038Z]   File …
```
=> Bug 1808606 - part 7 & 8: Add missing target task

.github/workflows/fenix-sync-strings.yml
CC @gabrielluong 
https://bugzilla.mozilla.org/show_bug.cgi?id=1814338
=> Bug 1814338 - Update l10n sync workflow for Fenix to match other products

taskcluster/android_taskgraph/transforms/signing_apk.py, taskcluster/ci/signing-apk/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1816787
=> Bug 1816787 - Update treeherder.platform for fenix signing-apk tasks

.github/workflows/ac-sync-strings.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1811383
=> Bug 1811383: Update ac_sync_strings to read correct version number

.github/workflows/ac-sync-strings.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1811383
=> Bug 1811383 - fix spelling for uses

fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/browser/BrowserTabsAdapter.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/static_strings.xml, fenix/app/src/main/res/xml/secret_settings_preferences.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1815968
=> Bug 1815968 - Add secret setting to Tabs Tray to Compose

focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1816908
=> Bug 1816908 - The search via the widget's microphone should open a w tab containing the search term.

taskcluster/ci/ui-test-apk/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1816967
=> Bug 1816967 - Simplify and generalize slack notify for ui-test-apk kind

.cron.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1817052
https://bugzilla.mozilla.org/show_bug.cgi?id=1817052
=> Bug 1817052 - Build Android nightlies 6 hours after Desktop's

.github/workflows/ac-sync-strings.yml, .github/workflows/fenix-sync-strings.yml, .github/workflows/focus-sync-strings.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1817439
=> Bug 1817439 - l10n workflows: use github-actions[bot] as authorfor uplift (sync) workflows

fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt, fenix/app/src/test/java/org/mozilla/fenix/search/SearchDialogFragmentTest.kt
=> Add FLAG_SECURE to SearchDialogFragment

fenix/README.md, fenix/app/build.gradle, fenix/settings.gradle, focus-android/README.md, focus-android/app/build.gradle, focus-android/settings.gradle
https://bugzilla.mozilla.org/show_bug.cgi?id=1815939
=> Bug 1815939 - Clean up AC autopublish code in Fenix and Focus

fenix/app/src/androidTest/assets/pages/creditCardForm.html, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/MatcherHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAutofillRobot.kt
Bug 1818196 - Part 2: New credit cards autofill related UI tests
Summary:
- Created new UI tests to improve the "Full functional" test suite coverage:
`verifyCreditCardCannotBeSavedWithoutCardNumberTest ` ✅ successfully passed 100x on Firebase
`verifyCreditCardCannotBeSavedWithoutNameOnCardTest ` ✅ successfully passed 100x on Firebase
`verifyMultipleCreditCardsCanBeSavedTest ` ✅ successfully passed 100x on Firebase
`verifyDoNotSaveCreditCardFromFormTest ` ✅ successfully passed 100x on Firebase
`verifySaveCreditCardFromFormTest ` ✅ successfully passed 100x on Firebase
`verifyCancelCreditCardUpdatePromptTest ` ✅ successfully passed 100x on Firebase
`verifyConfirmCreditCardUpdatePromptTest ` ✅ successfully passed 100x on Firebase
`verifySavedCreditCardsRedirectionToAutofillAfterInterruptionTe …
=> Bug 1818196 - Part 2: New credit cards autofill related UI tests 

taskcluster/ci/build-apk/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1819578
=> Bug 1819578 - Fix fenix android test debug shipping product

fenix/app/src/main/java/org/mozilla/fenix/gleanplumb/MessageNotificationWorker.kt
Fixes [Bug 1819914](https://bugzilla.mozilla.org/show_bug.cgi?id=1819914).
https://bugzilla.mozilla.org/show_bug.cgi?id=1819914
=> Bug 1819914 - Call ensureMarketingChannelExists in MessageNotificationWorker

android-components/plugins/dependencies/src/main/java/Gecko.kt
=> Update GeckoView (Release) to 111.0.20230306162820

android-components/components/lib/crash/build.gradle, android-components/components/lib/crash/docs/metrics.md, android-components/components/lib/crash/metrics.yaml, android-components/components/lib/crash/pings.yaml, android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/Crash.kt, android-components/components/lib/crash/src/main/java/mozilla/components/lib/crash/service/GleanCrashReporterService.kt, android-components/components/lib/crash/src/test/java/mozilla/components/lib/crash/service/GleanCrashReporterServiceTest.kt, android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt, docs/changelog.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1811928
https://bugzilla.mozilla.org/show_bug.cgi?id=1810951
=> Bug 1810951 - Implement Glean-based crash pings in lib-crash

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddToHomeScreenTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1820961
=> Bug 1820961 - Add smoke test annotation to mainMenuAddToHomeScreenTest and addPrivateBrowsingShortcutTest UI tests

fenix/.experimenter.yaml, fenix/app/metrics.yaml, fenix/app/pings.yaml, fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/ActivationPing.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricsUtils.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationLifecycleObserver.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationPing.kt, fenix/app/src/test/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationPingTest.kt, fenix/nimbus.fml.yaml
=> Bug 1817029 - Add the client-deduplication ping (#861) BACKPORT

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/home/TabCounterView.kt, fenix/app/src/test/java/org/mozilla/fenix/home/TabCounterViewTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1822181
=> Bug 1822181 - Refactor TabCounterBuilder to TabCounterView

fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlController.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFinishViewHolder.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolder.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/interactor/OnboardingInteractor.kt, fenix/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFinishViewHolderTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingPrivacyNoticeViewHolderTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1822378
=> Bug 1822378 - Refactor OnboardingInteractor into its own file

fenix/app/src/main/java/org/mozilla/fenix/widget/VoiceSearchActivity.kt
This was likely automatically imported by mistake
https://bugzilla.mozilla.org/show_bug.cgi?id=1822392
=> Bug 1822392 - Remove stray GMS reference for annotation

fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayController.kt, fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1812862
=> Bug 1812862 - Switch browsing mode on tab selected

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt, fenix/buildSrc/src/main/java/FenixDependencies.kt, focus-android/buildSrc/src/main/java/FocusDependencies.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1822804
https://bugzilla.mozilla.org/show_bug.cgi?id=1822804
=> Bug 1822804 - Update jna to version 5.13.0

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/home/ToolbarView.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1822601
=> Bug 1822601 - Refactor toolbar related logic into a ToolbarView

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/clientdeduplication/ClientDeduplicationPing.kt
=> Bug 1822283 - Fix race condition for Ad IDs

fenix/docs/Crash-Monitoring.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1823860
=> Bug 1823860 - Update crash monitoring docs to create a bugzilla report from Socorro

fenix/app/src/main/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorage.kt, fenix/app/src/test/java/org/mozilla/fenix/gleanplumb/NimbusMessagingStorageTest.kt
Reverts mozilla-mobile/firefox-android#1322
=> Revert "Bug 1822899 - Limit Nimbus message display count to max display count (backport #1291)"

fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1821722
=> Bug 1821722 - Update juno onboarding strings

fenix/app/src/main/java/org/mozilla/fenix/settings/deletebrowsingdata/DeleteBrowsingDataFragment.kt
This may be a possible fix for this crash: https://crash-stats.mozilla.org/report/index/a42f6990-a965-4578-b56d-ed4870230315 
I can't reproduce the bug. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1822620
=> Bug 1822620 -A possible fix for NullPointerException.

fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt
This is a refactor of a previous bug fix on fenix regarding adding unit tests that cover multi selection of tabs.
[Check this comment for more details](https://github.com/mozilla-mobile/fenix/pull/28800#discussion_r1103154918)
https://bugzilla.mozilla.org/show_bug.cgi?id=1814506
=> Bug 1814506 - Verify TabsTrayAction with CaptureActionsMiddleware

fenix/app/src/main/java/org/mozilla/fenix/experiments/NimbusSetup.kt
[Bug 1804115](https://bugzilla.mozilla.org/show_bug.cgi?id=1804115).
https://bugzilla.mozilla.org/show_bug.cgi?id=1804115
=> Bug 1804115 Catch errors thrown in the error reporter

fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt, fenix/app/src/test/java/org/mozilla/fenix/browser/BrowserFragmentTest.kt
* I couldn't find any apparent automated tests for checking presence of features in different channels
https://bugzilla.mozilla.org/show_bug.cgi?id=1826091
=> Bug 1826091 - Enable Pull to Refresh in release

focus-android/gradle.properties
https://bugzilla.mozilla.org/show_bug.cgi?id=1826176
=> Bug 1826176 - Syncronize Focus jvmargs with AC.

fenix/app/nimbus.fml.yaml, fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/experiments/view/ResearchSurfaceSurvey.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1821475
=> Bug 1821475 - Show research surface when survey message is available

android-components/components/service/nimbus/src/main/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorage.kt, android-components/components/service/nimbus/src/test/java/mozilla/components/service/nimbus/messaging/NimbusMessagingStorageTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1826880
=> Bug 1826880 - Filter next message with MessageSurfaceId if current message is control

android-components/components/browser/errorpages/src/main/res/values/strings.xml, android-components/components/feature/prompts/src/main/res/values/strings.xml, docs/changelog.md, fenix/app/src/main/res/values/strings.xml, focus-android/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1827217
=> Bug 1827217 - Start the Nightly 114 development cycle

android-components/plugins/dependencies/src/main/java/Gecko.kt
=> Update GeckoView (Nightly) to 114.0.20230410150526.

fenix/app/src/androidTest/assets/pages/htmlControls.html, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SitePermissionsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/BrowserRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1827844
=> Bug 1827844 - Adds file upload permission smoke test

android-components/components/service/nimbus/metrics.yaml, fenix/app/metrics.yaml
https://bugzilla.mozilla.org/show_bug.cgi?id=1828947
=> Bug 1828947 - Update notification email for permanent telemetry collections

fenix/app/src/main/java/org/mozilla/fenix/compose/DropdownMenu.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTray.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayFragment.kt
Added multi tab selection banner UI.
| V2 Light | V3 Light |
| --- | --- |
| ![v2Light](https://user-images.githubusercontent.com/35462038/230622204-65a0add9-cad5-44e2-9f1b-6c1e64193ed5.png) | ![debugLight](https://user-images.githubusercontent.com/35462038/230622227-a3d8df54-8317-4dbe-9502-e73f0afba604.png) |
| --- | --- |
| V2 Dark | V3 Dark |
| --- | --- |
| ![v2Dark](https://user-images.githubusercontent.com/35462038/230622298-c80d69bf-d7b1-448c-9396-e15d8617d4de.png) | ![debugDark](https://user-images.githubusercontent.com/35462038/230622325-d6fd1004-6775-4af9-8209-42fc075b4731.png) |
- **Breaking Changes**: If this is a breaking Android Components change, please push a draft PR on [Reference Browser](https://github.com/mozilla-mobile/reference-browser) to address the breaking …
=> Bug 1816522 - Add multi selection banner UI

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt, fenix/buildSrc/src/main/java/FenixDependencies.kt, focus-android/buildSrc/src/main/java/FocusDependencies.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1830601
https://bugzilla.mozilla.org/show_bug.cgi?id=1830601
https://bugzilla.mozilla.org/show_bug.cgi?id=1830601
https://bugzilla.mozilla.org/show_bug.cgi?id=1830601
https://bugzilla.mozilla.org/show_bug.cgi?id=1830601
https://bugzilla.mozilla.org/show_bug.cgi?id=1830601
=> Bug 1830601 - Update Robolectric to version 4.10.1

taskcluster/ci/beetmover/kind.yml, taskcluster/ci/release-notify-push/kind.yml, taskcluster/ci/release-notify-ship/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1831316
https://bugzilla.mozilla.org/show_bug.cgi?id=1831316
https://bugzilla.mozilla.org/show_bug.cgi?id=1831316
=> Bug 1831316 - Publish AC to Maven during the ship phase

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt, fenix/buildSrc/src/main/java/FenixDependencies.kt, focus-android/buildSrc/src/main/java/FocusDependencies.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1831239
https://bugzilla.mozilla.org/show_bug.cgi?id=1831239
=> Bug 1831239 - Update Kotlin to version 1.8.21 and AGP to version 7.4.2

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt, focus-android/buildSrc/src/main/java/FocusDependencies.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1831546
https://bugzilla.mozilla.org/show_bug.cgi?id=1831546
=> Bug 1831546 - Update AndroidX Browser to version 1.5.0

docs/changelog.md, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1831901
=> Bug 1831901 - Start the Nightly 115 development cycle

android-components/plugins/dependencies/src/main/java/Gecko.kt
=> Update GeckoView (Nightly) to 115.0.20230508173503

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1832638
https://bugzilla.mozilla.org/show_bug.cgi?id=1832638
=> Bug 1832638 - Update Kotlin Serialization to version 1.5.1

fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, focus-android/app/src/main/java/org/mozilla/focus/activity/MainActivity.kt
Fixes [Bug 1832066](https://bugzilla.mozilla.org/show_bug.cgi?id=1832066).
https://bugzilla.mozilla.org/show_bug.cgi?id=1832066
=> Bug 1832066 Initialize nimbus-cli tooling

fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapper.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/NotificationPermissionDialogScreen.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPage.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingPageState.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/UpgradeOnboarding.kt, fenix/app/src/test/java/org/mozilla/fenix/onboarding/view/JunoOnboardingMapperTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1833118
=> Bug 1833118 - Rename OnboardingPageState `image` to `imageRes` and update class desc @param to @property

fenix/buildSrc/src/main/java/FenixDependencies.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1833292
https://bugzilla.mozilla.org/show_bug.cgi?id=1833292
=> Bug 1833292 - Update Google Accompanist to version 0.30.1

fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml, fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1833627
https://bugzilla.mozilla.org/show_bug.cgi?id=1833627
https://bugzilla.mozilla.org/show_bug.cgi?id=1833627
=> Bug 1833627 - Add replacement API 27 device to UI test configurations

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeTabbedBrowsingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ComposeTabDrawerRobot.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/DropdownMenu.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayBanner.kt, fenix/app/src/main/java/org/mozilla/fenix/tabstray/TabsTrayTestTag.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1832606
=> Bug 1832606 - Convert `closeAllTabsTest` and add test tags

android-components/components/support/webextensions/src/test/java/mozilla/components/support/webextensions/WebExtensionSupportTest.kt, android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1834328
=> Bug 1834328 - Upgrade Mockito to latest version.

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/NimbusEventTest.kt, fenix/app/src/test/java/org/mozilla/fenix/search/SearchDialogFragmentTest.kt, fenix/app/src/test/java/org/mozilla/fenix/tabstray/DefaultTabsTrayControllerTest.kt, fenix/buildSrc/src/main/java/FenixDependencies.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1834746
=> Bug 1834746 - Upgrade Mockk to latest version.

android-components/components/support/ktx/build.gradle
Dependencies are already defined in L55 - L57
https://bugzilla.mozilla.org/show_bug.cgi?id=1818729
=> Bug 1818729 - Removed duplicate dependencies

taskcluster/ci/config.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1805651
=> Bug 1805651 - fix index-path-regexes

focus-android/app/build.gradle
https://bugzilla.mozilla.org/show_bug.cgi?id=1834924
=> Bug 1834924 - Add documentation to the generated LocalesList.

fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/home/HomeMenuView.kt, fenix/app/src/main/java/org/mozilla/fenix/home/Mode.kt, fenix/app/src/main/java/org/mozilla/fenix/home/TabCounterView.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlAdapter.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlInteractor.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/SessionControlView.kt, fenix/app/src/main/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFinishViewHolder.kt, fenix/app/src/main/java/org/mozilla/fenix/home/toolbar/ToolbarController.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingAccountObserver.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingStore.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/controller/OnboardingController.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/interactor/OnboardingInteractor.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingAdapter.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/view/OnboardingView.kt, fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/search/toolbar/SearchSelectorController.kt, fenix/app/src/main/res/navigation/nav_graph.xml, fenix/app/src/test/java/org/mozilla/fenix/components/AppStoreTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/HomeMenuViewTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/ModeTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/SessionControlInteractorTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/TabCounterViewTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/recentvisits/interactor/RecentVisitsInteractorTest.kt, fenix/app/src/test/java/org/mozilla/fenix/home/sessioncontrol/viewholders/onboarding/OnboardingFinishViewHolderTest.kt, fenix/app/src/test/java/org/mozilla/fenix/onboarding/DefaultOnboardingControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/onboarding/DefaultOnboardingInteractorTest.kt, fenix/app/src/test/java/org/mozilla/fenix/onboarding/OnboardingAccountObserverTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1809998
=> Bug 1809998 - Refactor Onboarding into its own fragment

fenix/app/src/main/java/org/mozilla/fenix/HomeActivity.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/AdjustMetricsService.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/Event.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/GrowthDataWorker.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricsMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricsStorage.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/test/java/org/mozilla/fenix/components/metrics/DefaultMetricsStorageTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1830401
=> Bug 1830401 - add Adjust event for Activated Users

fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1837258
=> Bug 1837258 – explain placeholder inside a string comment

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HistoryRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1837149
=> Bug 1837149 - New search history UI tests

fenix/app/src/main/java/org/mozilla/fenix/session/VisibilityLifecycleCallback.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1823367
=> Bug 1823367 - When closing Fenix in private mode, the ETP setting should have the default value.

fenix/app/build.gradle, fenix/benchmark/build.gradle, fenix/build.gradle, fenix/mozilla-detekt-rules/build.gradle, fenix/mozilla-lint-rules/build.gradle, fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1837107
=> Bug 1837107 - Unify FenixDependencies with AC's DependenciesPlugin

fenix/app/.experimenter.yaml, fenix/app/nimbus.fml.yaml
https://bugzilla.mozilla.org/show_bug.cgi?id=1840091
=> Bug 1840091 - Add shopping experience feature flag

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/AddLoginFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/EditLoginFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/logins/fragment/LoginDetailFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1836164
=> Bug 1836164 - New growth telemetry for credential management

android-components/components/support/ktx/src/main/res/values/strings.xml, docs/changelog.md, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1841651
=> Bug 1841651 - Start the Nightly 117 development cycle

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt, focus-android/app/build.gradle, focus-android/plugins/focusdependencies/src/main/java/FocusDependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1841081
https://bugzilla.mozilla.org/show_bug.cgi?id=1841081
https://bugzilla.mozilla.org/show_bug.cgi?id=1841081
=> Bug 1841081 - Update Kotlin Coroutines to version 1.7.2

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/MainMenuTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1842768
=> Bug 1842768 - Enable 'Report site issue' related tests

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SearchTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1843864
=> Bug 1843864 - Fenix: Add tests for unified search bar placeholder

android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/SyncFacts.kt, android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/FxaAccountManager.kt, fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt, fenix/app/src/main/java/org/mozilla/fenix/home/HomeMenu.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1841156
=> Bug 1841156 - new event telemetry in settings

android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/facts/LoginAutofillDialogFacts.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/login/LoginPicker.kt, fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/MetricController.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/SettingsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/logins/controller/LoginsListController.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1841152
=> Bug 1841152 - New event telemetry in credential management.

android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/update/UpdateAttemptStorageTest.kt, android-components/components/feature/sitepermissions/src/test/java/mozilla/components/feature/sitepermissions/OnDiskSitePermissionsStorageTest.kt, android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1845525
=> Bug 1845525 - Upgrade Room to latest version.

fenix/app/src/main/java/org/mozilla/fenix/settings/search/SaveSearchEngineFragment.kt, fenix/app/src/main/res/layout/fragment_save_search_engine.xml, fenix/app/src/main/res/values/strings.xml
Add a field to the "save search engine" fragment to allow users to add a custom URL to provide search auto-suggestions. If this field is left blank, the custom search engine feature will function exactly as it did before this change.
I don't know if you'd like a changelog entry for this. Please let me know.
* Previous attempt at this same PR: https://github.com/mozilla-mobile/fenix/pull/25402
* Original GitHub issue: https://github.com/mozilla-mobile/fenix/issues/7866.
* Bugzilla: https://bugzilla.mozilla.org/show_bug.cgi?id=1807573
2. Click …
=> Bug 1807573 - Add field to set custom search engine suggestion URL

docs/changelog.md, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1846280
=> Bug 1846280: Start the 118 development cycle

fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductReviewLoading.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt
– Figma and animation css in BZ. 
https://github.com/mozilla-mobile/firefox-android/assets/38040960/5aadcd0d-6b80-4bb0-9f7b-382a622eac05
https://bugzilla.mozilla.org/show_bug.cgi?id=1845255
=> Bug 1845255 - Add loading UI for review quality check

android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/CreditCardsAddressesStorage.kt, android-components/components/concept/storage/src/test/java/mozilla/components/concept/storage/CreditCardEntryTest.kt, android-components/components/service/sync-autofill/src/main/java/mozilla/components/service/sync/autofill/GeckoCreditCardsAddressesStorageDelegate.kt, android-components/components/service/sync-autofill/src/test/java/mozilla/components/service/sync/autofill/GeckoCreditCardsAddressesStorageDelegateTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1839158
=> Bug 1839158 - Ignore invalid credit card save requests

android-components/components/feature/addons/src/main/res/values/strings.xml
This string was introduced in https://github.com/mozilla-mobile/firefox-android/pull/3089
- ~~[ ] **Tests**: This PR includes thorough tests or an explanation of why it does not~~
1. Click on …
=> Bug 1845823 - Fixup l10n comment

fenix/app/src/main/java/org/mozilla/fenix/theme/ThemeManager.kt, fenix/app/src/main/res/drawable/felt_private_home_background_gradient.xml, fenix/app/src/main/res/values/styles.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1845234
=> Bug 1845234 - Adds a new background gradient for TPBM

fenix/app/src/main/java/org/mozilla/fenix/share/SaveToPDFMiddleware.kt, fenix/app/src/main/res/layout/fenix_snackbar.xml, fenix/app/src/main/res/values/strings.xml, fenix/app/src/test/java/org/mozilla/fenix/share/SaveToPDFMiddlewareTest.kt
Full printing error should be "Unable to print this page". Added a new string and deprecated the prior string.
https://bugzilla.mozilla.org/show_bug.cgi?id=1846515
=> Bug 1846515 - Update Print Error Snackbar

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/shopping/GeckoProductAnalysis.kt, android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineSession.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/shopping/ProductAnalysis.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt, docs/changelog.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1840692
=> Bug 1840692 - Expose Request Analysis Fakespot API

README.md
Updated Focus download link in `README.md`
https://bugzilla.mozilla.org/show_bug.cgi?id=1848208
=> Bug 1848208 - Update Focus Download Link in README.md

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/UpgradingUsersOnboardingTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/HomeScreenRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1848144
=> Bug 1848144 - Onboarding tests TestRail Matching

fenix/app/src/main/res/raw/initial_experiments.json
=> Bug 1848819 - Sync initial experiment from main to v116

fenix/app/src/main/java/org/mozilla/fenix/ext/NavController.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1842039
=> Bug 1842039 - Submit caught exception for IllegalArgumentException when navigating.

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSearchTest.kt
Bug 1847560 - New unified history search UI tests
The newly created UI tests successfully passed 100x on Firebase ✅ 
https://bugzilla.mozilla.org/show_bug.cgi?id=1847560
=> Bug 1847560 - New unified history search UI tests

android-components/components/lib/dataprotect/src/main/java/mozilla/components/lib/dataprotect/Keystore.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1842596
=> Bug 1842596 - Recover from UnrecoverableKeyException when retrieving sync key

fenix/app/src/main/res/layout/fragment_save_search_engine.xml, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1849326
=> Bug 1849326 - Use https in @string/search_add_custom_engine_suggest_string_example

android-components/components/feature/awesomebar/src/main/java/mozilla/components/feature/awesomebar/provider/SearchEngineSuggestionProvider.kt, fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt, fenix/app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt
Reverts mozilla-mobile/firefox-android#3401
https://bugzilla.mozilla.org/show_bug.cgi?id=1844960
https://bugzilla.mozilla.org/show_bug.cgi?id=1844960
=> Revert "Bug 1844960 - Bookmark suggestions should appear unconcerned with the  search suggestions setting."

fenix/app/.experimenter.yaml, fenix/app/nimbus.fml.yaml, fenix/app/src/androidTest/java/org/mozilla/fenix/extensions/ExtensionProcessTest.kt, fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1850280
=> Bug 1850280 - Control extensions process rollout with Nimbus

android-components/build.gradle, android-components/components/feature/addons/build.gradle, android-components/components/feature/app-links/build.gradle, android-components/components/feature/containers/build.gradle, android-components/components/feature/downloads/build.gradle, android-components/components/feature/logins/build.gradle, android-components/components/feature/pwa/build.gradle, android-components/components/feature/recentlyclosed/build.gradle, android-components/components/feature/share/build.gradle, android-components/components/feature/sitepermissions/build.gradle, android-components/components/feature/tab-collections/build.gradle, android-components/components/feature/top-sites/build.gradle, android-components/components/lib/crash/build.gradle, android-components/components/service/pocket/build.gradle, android-components/components/ui/tabcounter/build.gradle, android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt, fenix/build.gradle, focus-android/build.gradle
https://bugzilla.mozilla.org/show_bug.cgi?id=1847996
=> Bug 1847996 - Migrate from kapt to KSP

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1851961
=> Bug 1851961 - Upgrade compose to version 1.5.1

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/AddressAutofillTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSmokeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CreditCardAutofillTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/LoginsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsCustomizeTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsGeneralTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsHomepageTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SmokeTest.kt
For more information please see this [document](https://docs.google.com/document/d/1BBcRbNUITvDod5nih7r1-nmYzfCAnPlXcoltBCFiG2o/edit#heading=h.i26ccowgusqi)
5. The APK links should be on the right side of the screen, named for …
=> Bug 1850730 - General settings TestRail matching

taskcluster/android_taskgraph/transforms/upstream_artifacts.py
https://bugzilla.mozilla.org/show_bug.cgi?id=1825116
=> Bug 1825116 - add missing MPL header to upstream_artifacts transform

fenix/app/src/main/res/values/strings.xml
Flod manually fixed this on the l10n side, just need to land this on our side.
https://bugzilla.mozilla.org/show_bug.cgi?id=1845232
=> Bug 1845232 - Removes whitespace

fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckFooter.kt, fenix/app/src/main/res/values/strings.xml
This fix is to address a [localization conflict](https://github.com/mozilla-l10n/android-l10n/pull/682). 
https://bugzilla.mozilla.org/show_bug.cgi?id=1853421
=> Bug 1853421 - Fix shopping footer string

android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/aboutConfigPrefs.js, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/aboutConfigPrefs.json, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/experiment-apis/aboutConfigPrefsChild.js, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/lib/injections.js, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/lib/shims.js, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
This is a follow-up to https://github.com/mozilla-mobile/firefox-android/pull/3624 to address some potential inefficiencies.
https://bugzilla.mozilla.org/show_bug.cgi?id=1853013
=> Bug 1853013 - Ship 118.3.0 of feature-webcompat

fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckScaffold.kt, fenix/app/src/main/res/values/strings.xml
Update content description string for shopping experience.
https://bugzilla.mozilla.org/show_bug.cgi?id=1840090
=> Bug 1840090 - Update content description string for shopping experience

android-components/build.gradle, android-components/components/feature/fxsuggest/build.gradle, android-components/publish.gradle, android-components/samples/browser/build.gradle, android-components/samples/compose-browser/build.gradle, android-components/samples/crash/build.gradle, android-components/samples/dataprotect/build.gradle, android-components/samples/firefox-accounts/build.gradle, android-components/samples/glean/build.gradle, android-components/samples/glean/samples-glean-library/build.gradle, android-components/samples/sync-logins/build.gradle, android-components/samples/sync/build.gradle, android-components/samples/toolbar/build.gradle, android-components/substitute-local-ac.gradle, fenix/app/build.gradle, focus-android/app/build.gradle
https://bugzilla.mozilla.org/show_bug.cgi?id=1849833
=> Bug 1849833 - Fix warnings and deprecations in build files.

fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml, fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1854570
=> Bug 1854570 - Restore Pixel 3 for legacy and robo UI tests

android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestIngestionScheduler.kt, fenix/.buildconfig.yml, fenix/app/.experimenter.yaml, fenix/app/build.gradle, fenix/app/nimbus.fml.yaml, fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt, fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt, fenix/app/src/main/java/org/mozilla/fenix/components/Components.kt, fenix/app/src/main/java/org/mozilla/fenix/components/FxSuggest.kt, fenix/app/src/main/java/org/mozilla/fenix/search/awesomebar/AwesomeBarView.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/SecretSettingsFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/search/SearchEngineFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/static_strings.xml, fenix/app/src/main/res/values/strings.xml, fenix/app/src/main/res/xml/search_settings_preferences.xml, fenix/app/src/main/res/xml/secret_settings_preferences.xml, fenix/app/src/test/java/org/mozilla/fenix/search/awesomebar/AwesomeBarViewTest.kt, fenix/app/src/test/java/org/mozilla/fenix/settings/search/SearchEngineFragmentTest.kt
This PR integrates the Firefox Suggest Android component added in bug 1850296 into Fenix, and adds:
* A Nimbus feature for Firefox Suggest.
* A secret setting to enable the Firefox Suggest feature, only visible on the debug channel.
* Search settings for toggling sponsored and non-sponsored suggestions, only visible when the Firefox Suggest feature is enabled.
When the feature is enabled, Fenix will ingest new suggestions in the background, show the new Search settings, and show matching suggestions in the awesomebar depending on those Search settings.
1. Click on `Checks` at the top of …
=> Bug 1851268 - Show Firefox Suggest search suggestions in Fenix.

fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckCards.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckInfoCard.kt
Details in the bug.
https://bugzilla.mozilla.org/show_bug.cgi?id=1854631
=> Bug 1854631 - Refactor review checker info card

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeContextMenusTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ComposeSettingsDeleteBrowsingDataOnQuitTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/ContextMenusTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/CustomTabsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadFileTypesTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/DownloadTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsDeleteBrowsingDataOnQuitTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/DownloadRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/NotificationRobot.kt
Doc for reference: https://docs.google.com/document/d/16bsZs0udA1fqyuXER_QvN-YLHqD2Vml0hEca3UHlDy0/edit#heading=h.i26ccowgusqi
https://bugzilla.mozilla.org/show_bug.cgi?id=1853639
=> Bug 1853639 - Downloads TestRail matching

fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckScaffold.kt, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1852928
=> Bug 1852928 - Update review quality check bottom sheet header

fenix/app/src/main/java/org/mozilla/fenix/utils/ClipboardHandler.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/ToolbarPopupWindow.kt
Reverts mozilla-mobile/firefox-android#820
https://bugzilla.mozilla.org/show_bug.cgi?id=1810044
=> Revert "Bug 1810044 1810045 - Delay reading clipboard and allow to paste non url"

android-components/components/feature/media/src/main/java/mozilla/components/feature/media/fullscreen/MediaSessionFullscreenFeature.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1838541
=> Bug 1838541: Changed distinctUntilChanged for MediaSessionFullScreenFeature

fenix/app/.experimenter.yaml
https://bugzilla.mozilla.org/show_bug.cgi?id=1856537
=> Bug 1856537 - Sync `fenix/app/.experimenter.yaml` with latest nimbus config

fenix/app/src/main/java/org/mozilla/fenix/compose/tabstray/TabGridItem.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1854644
=> Bug 1854644 - Undo button from tabs tray should work.

fenix/app/src/main/java/org/mozilla/fenix/library/downloads/DownloadFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1854385
=> Bug 1854385 - When accessing files from downloads that cannot be opened, a snack bar with an error message should appear.

fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1857283
https://bugzilla.mozilla.org/show_bug.cgi?id=1857283
https://bugzilla.mozilla.org/show_bug.cgi?id=1857283
=> Bug 1857283 - Swap blueline with oriole in flank-arm-robo-test configuration

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarCFRPresenter.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ReviewQualityCheckFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/di/ReviewQualityCheckMiddlewareProvider.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/NoAnalysis.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysis.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckCards.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckSettingsCard.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddlewareTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckTelemetryMiddlewareTest.kt, fenix/app/tags.yaml
Added telemetry events for Review quality check feature. See [this document](https://docs.google.com/spreadsheets/d/1IVDm72fXuUsXV_h9fpNJ4y8VfAl2r334Hm7c1Shm1Gc/edit#gid=818994546) for more info about the events.
cc @perrymcmanis144  …
=> Bug 1843508 - Add review quality check feature telemetry events

fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNavigationMiddleware.kt
Updated "review_checker" with "our_mission" from the shopping feature "Powered by" url.
https://bugzilla.mozilla.org/show_bug.cgi?id=1857117
=> Bug 1857117 - Update review quality check "Powered by" url

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1857563
=> Bug 1857563 - Update Mockito to version 5.6.0

android-components/components/ui/icons/src/main/res/drawable/mozac_ic_dropdown_arrow.xml, android-components/components/ui/icons/src/main/res/drawable/mozac_ic_translate_24.xml, fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/interactor/BrowserToolbarInteractor.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/button/Button.kt, fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogBottomSheet.kt, fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt, fenix/app/src/main/res/navigation/nav_graph.xml, fenix/app/src/main/res/values/static_strings.xml, fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarControllerTest.kt, fenix/app/src/test/java/org/mozilla/fenix/components/toolbar/DefaultBrowserToolbarInteractorTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1857139
=> Bug 1857139 - Add translation bottom sheet boilerplate

android-components/.buildconfig.yml, android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtension.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/GeckoWebExtensionTest.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/webextension/MockWebExtension.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/webextension/WebExtension.kt, android-components/components/feature/addons/build.gradle, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/Addon.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/AddonManager.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/amo/AMOAddonsProvider.kt, android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/ui/AddonsManagerAdapter.kt, android-components/components/feature/addons/src/test/java/AddonManagerTest.kt, android-components/components/feature/addons/src/test/java/AddonTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/amo/AMOAddonsProviderTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/AddonsManagerAdapterTest.kt, android-components/components/feature/addons/src/test/java/mozilla/components/feature/addons/ui/ExtensionsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt, fenix/app/src/main/java/org/mozilla/fenix/extension/WebExtensionPromptFeature.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1850674
=> Bug 1850674 - Add extra add-on metadata

android-components/components/feature/fxsuggest/src/main/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProvider.kt, android-components/components/feature/fxsuggest/src/test/java/mozilla/components/feature/fxsuggest/FxSuggestSuggestionProviderTest.kt
This commit fixes the breaking change introduced in mozilla/application-services#5867.
=> No bug - Update uses of `SuggestionQuery` in Firefox Suggest.

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1858422
=> Bug 1858422 - Upgrade zxing to latest version.

android-components/components/feature/addons/src/main/java/mozilla/components/feature/addons/update/AddonUpdater.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1859494
=> Bug 1859494 - Rename a boolean variable in `AddonUdpater` and add some more comments

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1859936
=> Bug 1859936 - Update Firebase Cloud Messaging to version 23.3.0

focus-android/app/src/androidTest/java/org/mozilla/focus/activity/SearchTest.kt
Summary:
The UI tests seem to have run on a FR locale device, displayed Google's cookie banner causing the failures 
Verify the page content of the Google search page isn't a really good practice, and it is unnecessary in our case.
Removed `verifyPageContent` and used `verifyPageURL` instead. (Even if the cookie banner is displayed the URL will contain the default search engines name, in our case Google)
It successfully passed locally as well as on Firebase (100x) ✅ 
2. Click on the `firefoxci-taskcluster` group on the left to expand all …
=> Bug 1860467 - Fix testSearchBarShowsSearchTermOnEdit UI test

fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/Pipfile, fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/Pipfile.lock, fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/conftest.py, fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/models/__init__.py, fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/models/models.py, fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/tests/test_survey_messages.py
[JIRA Ticket](https://mozilla-hub.atlassian.net/browse/EXP-3954)
https://bugzilla.mozilla.org/show_bug.cgi?id=1859881
=> Bug 1859881 - Add enrollment telemetry verification tests to integration test suite

docs/changelog.md, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1860605
=> Bug 1860605 - Start the 121 development cycle

fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1861242
=> Bug 1861242 - Strings for add-ons general availability Nimbus message.

fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt, fenix/app/src/main/java/org/mozilla/fenix/components/metrics/InstallReferrerMetricsService.kt, fenix/app/src/test/java/org/mozilla/fenix/components/metrics/InstallReferrerMetricsServiceTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1860133
=> Bug 1860133 - Report Meta attribution from the Play Store referrer

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/SettingsAddonsTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuAddonsManagerRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ThreeDotMenuMainRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1861647
=> Bug 1861647 - Fenix: Add new Addons high priority tests

android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/data/ua_overrides.js, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/lib/ua_helpers.js, android-components/components/feature/webcompat/src/main/assets/extensions/webcompat/manifest.json
r? @wisniewskit
https://bugzilla.mozilla.org/show_bug.cgi?id=1862225
https://bugzilla.mozilla.org/show_bug.cgi?id=1862225
https://bugzilla.mozilla.org/show_bug.cgi?id=1862225
https://bugzilla.mozilla.org/show_bug.cgi?id=1862225
https://bugzilla.mozilla.org/show_bug.cgi?id=1862225
=> Bug 1862225 - Update for tesco.com override

taskcluster/ci/push-apk/kind.yml, taskcluster/ci/push-bundle/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1567912
=> Bug 1567912 - Switch pushed Fenix Beta/Release to AAB builds

android-components/components/browser/storage-sync/src/main/java/mozilla/components/browser/storage/sync/PlacesHistoryStorage.kt, android-components/components/browser/storage-sync/src/test/java/mozilla/components/browser/storage/sync/PlacesHistoryStorageTest.kt, android-components/components/concept/storage/src/main/java/mozilla/components/concept/storage/HistoryStorage.kt, android-components/components/feature/session/src/test/java/mozilla/components/feature/session/HistoryDelegateTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1862350
=> Bug 1862350 - Remove old History delete APIs

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/HistoryTest.kt
New high priority history UI test ✅ successfully passed 100x on Firebase
https://bugzilla.mozilla.org/show_bug.cgi?id=1862926
=> Bug 1862926 - New high priority history UI test

fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckContextualOnboarding.kt, fenix/app/src/main/res/values/strings.xml
Talked with Delphine about this. Just cleaning up an unused & untranslated string. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1861732
=> Bug 1861732 - Clean up shopping onboarding caption strings

fenix/app/src/main/java/org/mozilla/fenix/components/metrics/InstallReferrerMetricsService.kt, fenix/app/src/test/java/org/mozilla/fenix/components/metrics/InstallReferrerMetricsServiceTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1863603
=> Bug 1863603 - Add handling of Meta attribution in percent format

fenix/app/nimbus.fml.yaml
https://bugzilla.mozilla.org/show_bug.cgi?id=1864403
=> Bug 1864403 - Enable product recommendations for developer builds

fenix/automation/taskcluster/androidTest/flank-arm-legacy-api-tests.yml, fenix/automation/taskcluster/androidTest/flank-arm-robo-test.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1865317
=> Bug 1865317 - Add correct API for redfin AVD

android-components/components/feature/addons/src/main/res/values/strings.xml, android-components/components/feature/prompts/src/main/res/values/strings.xml, docs/changelog.md, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1865648
=> Bug 1865648 - Start the 122 development cycle

android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1856470
=> Bug 1856470 - Add EMAIL filter to TrackingCategory for tracker protection

taskcluster/ci/build-apk/kind.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1825116
=> Bug 1825116 - Consolidate attributes in build-apk kind.yml

fenix/app/src/main/java/org/mozilla/fenix/components/metrics/fonts/FontEnumerationWorker.kt
Use the GLEAN-generated metric, and submit the ping.
https://bugzilla.mozilla.org/show_bug.cgi?id=1867619
=> Bug 1867619: Fix the font list telemetry ping r?tlong

fenix/app/src/main/java/org/mozilla/fenix/messaging/MessageNotificationWorker.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1868315
=> Bug 1868315 - Update MessageNotificationWorker to use 'CoroutineWorker' instead of 'Worker'

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1868434
=> Bug 1868434 - Update Firebase Cloud Messaging to version 23.3.1

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngine.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/Settings.kt, android-components/samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt, docs/changelog.md, fenix/app/src/androidTest/assets/pages/global_privacy_control.html, fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestAssetHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/GlobalPrivacyControlTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionRobot.kt, fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt, fenix/app/src/main/java/org/mozilla/fenix/settings/TrackingProtectionFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/Settings.kt, fenix/app/src/main/res/values/preference_keys.xml, fenix/app/src/main/res/values/strings.xml, fenix/app/src/main/res/xml/tracking_protection_preferences.xml, focus-android/app/src/androidTest/assets/global_privacy_control.html, focus-android/app/src/androidTest/java/org/mozilla/focus/privacy/GlobalPrivacyControlTest.kt
https://www.figma.com/file/RyIADLmC3B0BIS9jSiAti3/Settings?node-id=0%3A2212&mode=dev#629804471
The option is available regardless of the selected ETP option
https://bugzilla.mozilla.org/show_bug.cgi?id=1865357
=> Bug 1865357 - Add Global Privacy Control settings

fenix/app/src/main/java/org/mozilla/fenix/FeatureFlags.kt
Manual uplift due to conflict.
=> Bug 1868683 - Turn on Meta attribution telemetry for all builds

fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1868323
=> Bug 1868323 - Use typographical quotes

fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/EnumMapper.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapper.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckNetworkMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/middleware/ReviewQualityCheckService.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckAction.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckState.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStore.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ProductAnalysisError.kt, fenix/app/src/main/java/org/mozilla/fenix/shopping/ui/ReviewQualityCheckBottomSheet.kt, fenix/app/src/main/res/values/strings.xml, fenix/app/src/test/java/org/mozilla/fenix/shopping/fake/FakeReviewQualityCheckService.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/EnumMapperTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/middleware/ProductAnalysisMapperTest.kt, fenix/app/src/test/java/org/mozilla/fenix/shopping/store/ReviewQualityCheckStoreTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1858948
=> Bug 1858948 - Add shopping NotAvailable product state

fenix/app/src/main/res/values/strings.xml
This was accidentally changed in #4808, reverting that bit. 
https://bugzilla.mozilla.org/show_bug.cgi?id=1866113
=> Bug 1866113 - Unchange changed string

fenix/app/src/androidTest/java/org/mozilla/fenix/experimentintegration/conftest.py
[JIRA Ticket](https://mozilla-hub.atlassian.net/browse/ECTEEN-79)
https://bugzilla.mozilla.org/show_bug.cgi?id=1869867
=> Bug 1869867 - Update experimentation test suite to support smoke tests that don't use the message feature

fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1866113
=> Bug 1866113 - Update analysis in progress string comment

android-components/components/feature/addons/src/main/res/values/strings.xml, docs/changelog.md, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1870647
=> Bug 1870647 - Start the Nightly 123 development cycle

android-components/components/support/utils/src/main/java/mozilla/components/support/utils/SafeIntent.kt, fenix/app/metrics.yaml, fenix/app/src/main/java/org/mozilla/fenix/IntentReceiverActivity.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1871548
=> Bug 1871548 - Add telemetry for Open PDF in Fenix

fenix/app/nimbus.fml.yaml, fenix/app/src/androidTest/java/org/mozilla/fenix/extensions/ExtensionProcessTest.kt, fenix/app/src/main/java/org/mozilla/fenix/gecko/GeckoProvider.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1867597
=> Bug 1867597 - Enable extensions process unconditionally

fenix/docs/Acronym-dictionary.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1873277
=> Bug 1873277 - Update acronym dictionary

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1873280
=> Bug 1873280 - Update Firebase Cloud Messaging to version 23.4.0

android-components/components/feature/prompts/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1862190
=> Bug 1862190: Add detailed description for dialog message

android-components/components/feature/media/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1862190
=> Bug 1862190: Format string to remove double space

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/request/RequestInterceptor.kt, fenix/app/src/main/java/org/mozilla/fenix/AppRequestInterceptor.kt, fenix/app/src/main/java/org/mozilla/fenix/components/Services.kt, fenix/app/src/main/java/org/mozilla/fenix/components/UrlRequestInterceptor.kt, fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogController.kt, fenix/app/src/test/java/org/mozilla/fenix/components/UrlRequestInterceptorTest.kt, fenix/app/src/test/java/org/mozilla/fenix/search/SearchDialogControllerTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1866133
=> Bug 1866133 - Add additional headers for Google search

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/wallpapers/WallpapersUseCases.kt
– Add wallpaper URL in debug builds so this issue can be reproduced in debug builds and is highlighted by strict mode using this snippet in app build.gradle. 
```
if (isDebug) {
buildConfigField 'String', 'WALLPAPER_URL', '"https://assets.mozilla.net/mobile-wallpapers/android"'
} else {
try {
def token = new File("${rootDir}/.wallpaper_url").text.trim()
buildConfigField 'String', 'WALLPAPER_URL', '"' + token + '"'
println "(Added from .wallpaper_url file)"
} catch (FileNotFoundException ignored) {
buildConfigField 'String', 'WALLPAPER_URL', '""'
println("--")
}
}
```
– Use Fragment view's `lifecycleScope` instead of `runBlocking` so the main thread is not blocked. Also, in case the app enters paused state or changes configuration while the wallpapers are being loaded, this would cancel …
=> Bug 1828927 - Fix apply wallpaper anr

fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1828927
=> Bug 1828927 - Remove accidental debug logs

fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BottomToolbarContainerView.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/NavigationBar.kt, fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1868262
=> Bug 1868262 - Add menu button to nav toolbar

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1874880
=> Bug 1874880 - Update Mockito to version 5.9.0

fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarController.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/interactor/BrowserToolbarInteractor.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1870939
=> Bug 1870939 - Add Share Page to PageActions in Toolbar

fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1874298
=> Bug 1874298 - Add Reload Page action to PageActions in Toolbar

focus-android/app/src/main/res/values/strings.xml
See https://github.com/mozilla-l10n/android-l10n/pull/725
https://bugzilla.mozilla.org/show_bug.cgi?id=1843057
=> Bug 1843057 - Remove previous string comment.

android-components/.config.yml, android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt, focus-android/app/build.gradle
https://bugzilla.mozilla.org/show_bug.cgi?id=1844317
=> Bug 1844317 - Target SDK 34 in Fenix

fenix/automation/taskcluster/androidTest/testrail.py, focus-android/automation/taskcluster/androidTest/testrail.py
Caught by `ruff`.
https://bugzilla.mozilla.org/show_bug.cgi?id=1867539
=> Bug 1867539 - fix exception formatting in testrail script

docs/changelog.md, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1875869
=> Bug 1875869 - Start the Nightly 124 development cycle

docs/changelog.md
Missed adding a changelog to the previous commit.
https://bugzilla.mozilla.org/show_bug.cgi?id=1850006
=> Bug 1850006 - Update changelog.

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/prompt/GeckoPromptDelegate.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/prompt/PromptRequest.kt, android-components/components/feature/prompts/src/androidTest/java/mozilla/components/feature/prompts/file/OnDeviceFilePickerTest.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/PromptFeature.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FilePicker.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FileUploadsDirCleaner.kt, android-components/components/feature/prompts/src/main/java/mozilla/components/feature/prompts/file/FileUploadsDirCleanerMiddleware.kt, android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/PromptFeatureTest.kt, android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/FilePickerTest.kt, android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/FileUploadsDirCleanerMiddlewareTest.kt, android-components/components/feature/prompts/src/test/java/mozilla/components/feature/prompts/file/FileUploadsDirCleanerTest.kt, android-components/samples/browser/src/main/java/org/mozilla/samples/browser/BaseBrowserFragment.kt, android-components/samples/browser/src/main/java/org/mozilla/samples/browser/DefaultComponents.kt, docs/changelog.md, fenix/app/src/main/java/org/mozilla/fenix/FenixApplication.kt, fenix/app/src/main/java/org/mozilla/fenix/addons/AddonPopupBaseFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/components/Core.kt, focus-android/app/src/main/java/org/mozilla/focus/Components.kt, focus-android/app/src/main/java/org/mozilla/focus/FocusApplication.kt, focus-android/app/src/main/java/org/mozilla/focus/fragment/BrowserFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1860472
=> Bug 1860472 - Periodically clean the Uploads cacheDir.

android-components/components/feature/media/src/main/java/mozilla/components/feature/media/middleware/RecordingDevicesMiddleware.kt, android-components/components/feature/media/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1875382
=> Bug 1875382: add ending punctuation & change strings ids

android-components/components/feature/app-links/src/main/java/mozilla/components/feature/app/links/AppLinksInterceptor.kt, android-components/components/feature/app-links/src/test/java/mozilla/components/feature/app/links/AppLinksInterceptorTest.kt
Most of the changes in the test file is due to ktlint issue.
https://bugzilla.mozilla.org/show_bug.cgi?id=1877039
=> Bug 1877039 - Do not attempt to trigger external app if new request was too soon

android-components/components/feature/prompts/src/main/res/values/strings.xml, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1876794
=> Bug 1876794 - Fixes in A-C and Fenix strings

android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/SuspendMiddleware.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/SuspendMiddlewareTest.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TrimMemoryMiddlewareTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1812359
=> CI for Bug 1812359

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1877885
=> Bug 1877885 - Update Detekt to version 1.23.5

android-components/components/feature/addons/build.gradle, android-components/components/feature/containers/build.gradle, android-components/components/feature/downloads/build.gradle, android-components/components/feature/downloads/src/androidTest/java/mozilla/components/feature/downloads/OnDeviceDownloadStorageTest.kt, android-components/components/feature/downloads/src/main/java/mozilla/components/feature/downloads/db/DownloadsDatabase.kt, android-components/components/feature/logins/build.gradle, android-components/components/feature/logins/src/androidTest/java/mozilla/components/feature/logins/LoginExceptionStorageTest.kt, android-components/components/feature/pwa/build.gradle, android-components/components/feature/pwa/src/androidTest/java/mozilla/components/feature/pwa/db/ManifestDatabaseMigrationTest.kt, android-components/components/feature/pwa/src/main/java/mozilla/components/feature/pwa/db/ManifestDatabase.kt, android-components/components/feature/recentlyclosed/build.gradle, android-components/components/feature/share/build.gradle, android-components/components/feature/share/src/main/java/mozilla/components/feature/share/db/RecentAppsDatabase.kt, android-components/components/feature/sitepermissions/build.gradle, android-components/components/feature/sitepermissions/src/androidTest/java/mozilla/components/feature/sitepermissions/db/OnDeviceSitePermissionsStorageTest.kt, android-components/components/feature/sitepermissions/src/main/java/mozilla/components/feature/sitepermissions/db/SitePermissionsDatabase.kt, android-components/components/feature/tab-collections/build.gradle, android-components/components/feature/top-sites/build.gradle, android-components/components/feature/top-sites/src/androidTest/java/mozilla/components/feature/top/sites/OnDevicePinnedSitesStorageTest.kt, android-components/components/feature/top-sites/src/main/java/mozilla/components/feature/top/sites/db/TopSiteDatabase.kt, android-components/components/service/pocket/build.gradle, android-components/components/service/pocket/src/androidTest/java/mozilla/components/service/pocket/stories/db/PocketRecommendationsDatabaseTest.kt, android-components/components/service/pocket/src/main/java/mozilla/components/service/pocket/stories/db/PocketRecommendationsDatabase.kt, android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1845496
https://bugzilla.mozilla.org/show_bug.cgi?id=1847999
=> Bug 1847999 - Switch to generating Kotlin code for Room.

fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1873486
=> Bug 1873486 - Update mockk to version 1.13.9

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1880152
=> Bug 1880152 - Update Firebase Cloud Messaging to version 23.4.1

fenix/plugins/fenixdependencies/src/main/java/FenixDependenciesPlugin.kt, focus-android/plugins/focusdependencies/src/main/java/FocusDependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1880494
=> Bug 1880494 - Update JUnit5 to version 5.10.2

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1880511
=> Bug 1880511 - Update Kotlin Coroutines to version 1.8.0

focus-android/app/src/main/res/values/strings.xml
Updating description based on [this discussion](https://github.com/mozilla-l10n/android-l10n/pull/737#pullrequestreview-1878741110).
cc: @Delphine 
https://bugzilla.mozilla.org/show_bug.cgi?id=1875379
=> Bug 1875379 - Fix ambiguity in string description.

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SearchRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1880808
=> Bug 1880808 - Add logs to SearchRobot

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuCustomizeRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1880812
=> Bug 1880812 - Add logs to SettingsSubMenuCustomizeRobot

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuDataCollectionRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1880821
=> Bug 1880821 - Add test logs to SettingsSubMenuDataCollectionRobot

docs/changelog.md, fenix/app/src/main/res/values/strings.xml
https://bugzilla.mozilla.org/show_bug.cgi?id=1880999
=> Bug 1880999 - Start the Nightly 125 development cycle

.cron.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1881066
https://bugzilla.mozilla.org/show_bug.cgi?id=1881066
=> Bug 1881066 - Unschedule screenshots cron

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1881733
=> Bug 1881733 - Add logs to SettingsSubMenuLoginsAndPasswordsSavedLoginsRobot

android-components/plugins/dependencies/src/main/java/DependenciesPlugin.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1881347
=> Bug 1881347 - Update Compose Compiler to version 1.5.10

android-components/components/browser/engine-gecko/src/main/java/mozilla/components/browser/engine/gecko/GeckoEngineSession.kt, android-components/components/browser/engine-gecko/src/test/java/mozilla/components/browser/engine/gecko/GeckoEngineSessionTest.kt, android-components/components/browser/engine-system/src/main/java/mozilla/components/browser/engine/system/SystemEngineView.kt, android-components/components/browser/engine-system/src/test/java/mozilla/components/browser/engine/system/SystemEngineViewTest.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/EngineObserver.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/ContentStateReducer.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/ContentActionTest.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/EngineObserverTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/EngineSession.kt, android-components/components/concept/engine/src/test/java/mozilla/components/concept/engine/EngineSessionTest.kt, android-components/config/detekt-baseline.xml, android-components/plugins/dependencies/src/main/java/Gecko.kt, docs/changelog.md
Also fixes breaking changes introduced in ~~[D180685](https://phabricator.services.mozilla.com/D180685)~~ ~~[D193211](https://phabricator.services.mozilla.com/D193211)~~ [D199568](https://phabricator.services.mozilla.com/D199568) …
=> Bug 1804636 - Allow search terms to be refined in content

android-components/components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt, android-components/components/concept/toolbar/src/test/java/mozilla/components/concept/toolbar/ActionButtonTest.kt, docs/changelog.md, fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/TranslationsBinding.kt, fenix/app/src/main/res/values/strings.xml, fenix/app/src/test/java/org/mozilla/fenix/browser/TranslationsBindingTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1875817
=> Bug 1875817 - Translations Integration Toolbar Showing

android-components/components/service/firefox-accounts/src/main/java/mozilla/components/service/fxa/manager/AppServicesStateMachineChecker.kt
This should prevent some Sentry errors from the state machine checker code ([for example](https://mozilla.sentry.io/discover/fenix-nightly:0782af89b92442878a2a8ccfaac90ce0/?field=title&field=release&field=environment&field=user.display&field=timestamp&name=fxa-state-machine-checker%3A+handle_public_event+called+with+non-terminal+internal+state%3A+CheckAthorizationStatus+%28CheckAthori...&project=6295546&query=issue%3AFENIX-NIGHTLY-A2W&sort=-timestamp&statsPeriod=90d&yAxis=count%28%29))
2. Click on the `firefoxci-taskcluster` group on the …
=> Bug 1882136 - Fxa state machine checker fix

android-components/.config.yml, android-components/build.gradle, android-components/components/tooling/detekt/build.gradle, android-components/components/tooling/lint/build.gradle, fenix/app/build.gradle, fenix/benchmark/build.gradle, fenix/build.gradle, fenix/mozilla-lint-rules/build.gradle, focus-android/app/build.gradle, focus-android/build.gradle, shared-settings.gradle
https://bugzilla.mozilla.org/show_bug.cgi?id=1882134
=> Bug 1882134 - Use jvmToolchain for setting target JVM version

android-components/components/browser/state/src/main/java/mozilla/components/browser/state/action/BrowserAction.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/reducer/TranslationsStateReducer.kt, android-components/components/browser/state/src/main/java/mozilla/components/browser/state/state/TranslationsBrowserState.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/action/TranslationsActionTest.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddlewareTest.kt, android-components/components/concept/engine/src/main/java/mozilla/components/concept/engine/translate/TranslationOperation.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1876820
=> Bug 1876820 - Add translation fetch downloaded languages action

fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationOptionsDialog.kt, fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSettings.kt, fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSwitchItem.kt, fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsBottomSheet.kt, fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogMiddleware.kt, fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationsDialogStore.kt, fenix/app/src/test/java/org/mozilla/fenix/translations/TranslationsDialogMiddlewareTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1856986
=> Bug 1856986 - Translations UI Integration Preference Logic - Page Settings

android-components/components/browser/state/src/main/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddleware.kt, android-components/components/browser/state/src/test/java/mozilla/components/browser/state/engine/middleware/TranslationsMiddlewareTest.kt
This bug adds:
* When `TranslateExpectedAction` occurs, then calculate the expected translations model download size.
More background: `TranslateExpectedAction` indicates we have a default `from` (page language) and a default `to` (user preferred) language to initialize the translations dialog with expected values.
This queries how large of a download the translation pair will be eagerly, so we have an initial value for the default recommendation. …
=> Bug 1882542 - Eagerly Calculate an Initial Translation Download Size

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/ShareOverlayRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1882976
=> Bug 1882976 - Add logs to ShareOverlayRobot

fenix/app/src/main/java/org/mozilla/fenix/translations/TranslationSettingsFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1881831
=> Bug 1881831 - Translations Integration - Add "Offer to translate when possible" Connection

.github/ISSUE_TEMPLATE/config.yml
https://bugzilla.mozilla.org/show_bug.cgi?id=1883703
=> Bug 1883703 - Direct contributors to Bugzilla for issue tracking

fenix/app/src/main/java/org/mozilla/fenix/browser/tabstrip/TabStrip.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1883621
=> Bug 1883621 - Add fade edge to long titles in tab strip

fenix/app/src/androidTest/java/org/mozilla/fenix/ui/EnhancedTrackingProtectionTest.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionExceptionsRobot.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/SettingsSubMenuEnhancedTrackingProtectionRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1881028
=> Bug 1881028 - Add logs to SettingsSubMenuEnhancedTrackingProtectionRobot

android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/BrowserToolbar.kt, android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/display/DisplayToolbar.kt, android-components/components/browser/toolbar/src/main/java/mozilla/components/browser/toolbar/edit/EditToolbar.kt, android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_displaytoolbar.xml, android-components/components/browser/toolbar/src/main/res/layout/mozac_browser_toolbar_edittoolbar.xml, android-components/components/browser/toolbar/src/main/res/values/dimens.xml, android-components/components/browser/toolbar/src/test/java/mozilla/components/browser/toolbar/BrowserToolbarTest.kt, android-components/components/concept/toolbar/src/main/java/mozilla/components/concept/toolbar/Toolbar.kt, android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt, android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/feature/CustomTabSessionTitleObserverTest.kt, android-components/components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarAutocompleteFeatureTest.kt, android-components/components/feature/toolbar/src/test/java/mozilla/components/feature/toolbar/ToolbarInteractorTest.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/BrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/BrowserToolbarView.kt, fenix/app/src/main/java/org/mozilla/fenix/search/SearchDialogFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/search/toolbar/ToolbarView.kt, fenix/app/src/main/java/org/mozilla/fenix/theme/FirefoxTheme.kt, fenix/app/src/main/res/drawable/search_old_url_background.xml, fenix/app/src/main/res/values-night/colors.xml, fenix/app/src/main/res/values/attrs.xml, fenix/app/src/main/res/values/colors.xml, fenix/app/src/main/res/values/styles.xml, fenix/app/src/test/java/org/mozilla/fenix/search/toolbar/ToolbarViewTest.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1874298
https://bugzilla.mozilla.org/show_bug.cgi?id=1870938
=> Bug 1870938 - Add display/edit toolbar separator and update url bar background

fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/browser/TabPreview.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/BottomToolbarContainerView.kt, fenix/app/src/main/java/org/mozilla/fenix/components/toolbar/navbar/NavigationBar.kt, fenix/app/src/main/java/org/mozilla/fenix/compose/LongPressIconButton.kt, fenix/app/src/main/java/org/mozilla/fenix/home/HomeFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1878827
=> Bug 1878827 - Add nav buttons click handling

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/TestHelper.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1885108
=> Bug 1885108 - Add logs to TestHelper

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/DataGenerationHelper.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1885123
=> Bug 1885123 - Add logs to DataGenerationHelper

fenix/app/src/androidTest/java/org/mozilla/fenix/helpers/AppAndSystemHelper.kt, fenix/app/src/androidTest/java/org/mozilla/fenix/ui/robots/PwaRobot.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1885160
=> Bug 1885160 - Add logs to AppAndSystemHelper

docs/contributing.md
https://bugzilla.mozilla.org/show_bug.cgi?id=1877307
=> Bug 1877307 - Fix broken link and title

fenix/app/src/main/java/org/mozilla/fenix/browser/BaseBrowserFragment.kt
https://bugzilla.mozilla.org/show_bug.cgi?id=1885399
=> Bug 1885399 - Fix clipping behaviour

android-components/components/feature/customtabs/src/main/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeature.kt, android-components/components/feature/customtabs/src/test/java/mozilla/components/feature/customtabs/CustomTabsToolbarFeatureTest.kt
Differential Revision: https://phabricator.services.mozilla.com/D205056
=> Uplift request: Bug 1886123 - Removed unnecessary setting of app dark mode which was causing theming

focus-android/app/src/main/java/org/mozilla/focus/widget/ResizableKeyboardCoordinatorLayout.kt
Phabricator Differential: https://phabricator.services.mozilla.com/D206005
=> Uplift request: Bug 1885095 - Do not propagate requestDisallowInterceptTouchEvent.

focus-android/app/src/main/java/org/mozilla/focus/widget/ResizableKeyboardCoordinatorLayout.kt
=> Uplift request 124: Bug 1885095 - Do not propagate requestDisallowInterceptTouchEvent.

fenix/app/src/main/java/org/mozilla/fenix/messaging/CustomAttributeProvider.kt
Differential Revision: https://phabricator.services.mozilla.com/D205337
=> Uplift request: Bug 1886769 - Add search widget installed custom attribute.

fenix/app/src/main/java/org/mozilla/fenix/home/intent/HomeDeepLinkIntentProcessor.kt, fenix/app/src/main/java/org/mozilla/fenix/onboarding/OnboardingFragment.kt, fenix/app/src/main/java/org/mozilla/fenix/utils/AddSearchWidgetPrompt.kt, fenix/app/src/test/java/org/mozilla/fenix/home/intent/HomeDeepLinkIntentProcessorTest.kt
Differential Revision: https://phabricator.services.mozilla.com/D205477
=> Uplift request: Bug 1886792 - Handle install_search_widget deeplink
